### ISSUE TITLE
StripeTerminalProvider causes app to get stuck on Expo loading screen in production mode

### ISSUE THREAD

**Issue by devardha** [stripe/stripe-terminal-react-native#362]
**Describe the bug**
Using `StripeTerminalProvider` causes the app to get stuck on the Expo loading screen. This only happens in production mode using `expo start --no-dev --minify`

**To Reproduce**
1. Create a new Expo project
`npx create-expo-app my-app`
2. Install Stripe Terminal SDK
`npm install @stripe/stripe-terminal-react-native`
3. Add `StripeTerminalProvider` to `App.js`
```jsx
import { useEffect } from "react";
import { StripeTerminalProvider } from "@stripe/stripe-terminal-react-native";
import { PermissionsAndroid } from "react-native";
import { Text, View } from "react-native";

export default function App() {
    const fetchTokenProvider = async () => {
        const response = await fetch("https://myapi.com/connection_token", {
            method: "GET",
	    headers: {
	        "Content-Type": "application/json",
	    },
        });
	
        const { secret } = await response.json();
	return secret;
    };

    useEffect(() => {
        async function init() {
            try {
	        PermissionsAndroid.requestMultiple([
		    PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT,
		    PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN,
		    PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
                ]).then((result) => {
		    if (
		        result["android.permission.BLUETOOTH_CONNECT"] &&
			result["android.permission.BLUETOOTH_SCAN"] &&
			result["android.permission.ACCESS_FINE_LOCATION"] &&
			"granted"
		    ) {
		        setPermissionsGranted({
			    permissionsGranted: true,
			});
		    } else {
		        console.error("error");
		    }
                });
	    } catch (e) {
                console.error(e);
	    }		
        }

        init();
    }, []);

    return (
        <StripeTerminalProvider
            logLevel="verbose"
	    tokenProvider={fetchTokenProvider}
	>
	    <View>
	        <Text>Hello, world!</Text>
	    </View>
	</StripeTerminalProvider>
    );
}
```
4. Run the application using production mode
`npx expo start --no-dev --minify`

**Expected behavior**
The application is stuck on the expo loading screen without any error messages

**Screenshots**
![Screenshot_20220707-162026_Expo_Go1](https://user-images.githubusercontent.com/59217768/178119687-5d70e39b-5d03-461f-9da3-7db871cfaadc.jpg)
![screenshot-terminal](https://user-images.githubusercontent.com/59217768/178119822-2e0b61f5-394a-4217-8fb6-100f5219c8bd.png)
The problem only occurs in production mode. If you run it in development mode using `npx expo run:android` everything works fine.

**Smartphone (please complete the following information):**

- Device: Android Virtual Device
- OS: Android 11
- Version: v0.0.1-beta.7

**Comment by jdivock-stripe** [comment]
Thanks for the report, we'll see if we can repro and surface an error.

**Comment by jdivock-stripe** [comment]
Hey @devardha it seems that trying to run it in the mode you're using is attempting to launch it through Expo Go which is not supported as our SDK relies on underlying native dependencies that must be built. We only support the `run:ios` and `run:android` targets as per https://docs.expo.dev/workflow/customizing/
