### ISSUE TITLE
Why cancel discovering for internet/smart reader ?

### ISSUE THREAD

**Issue by melarts** [stripe/stripe-terminal-react-native#363]
**Description**
In the [Javascript plugin](https://stripe.com/docs/terminal/references/api/js-sdk#discover-readers) you are able to launch a discovery twice and you don't need to cancel the discovery for Smart reader.

In [stripe-terminal-react-native](https://github.com/stripe/stripe-terminal-react-native) you can't do this because you will be receiving  when calling `discoverReaders` : `{"code": "Busy", "message": "Could not execute discoverReaders because the SDK is busy with another command: discoverReaders."}}`

Since we will be receiving only one update from `onUpdateDiscoveredReaders`, why should we be forced to call `cancelDiscovering` first if we want to trigger a new search for smart readers ?

**Additional context**

I've integrated both bluetooth and internet readers in my app, starting by the bluetooth one. And it seems to me, that contrary to the bluetooth reader, the smart one is not really still discovering/searching after receiving the first _onUpdateDiscoveredReaders_ listener update. I'm trying to face some UI problems because when you are discovering with the smart reader and receiving the reply we still display kind of loading style since we are supposed to be in discovering. But to me it is not true.

**Comment by jdivock-stripe** [comment]
Hi @melarts, thanks for the inquiry. The RN SDK is a bit of a departure from our JS SDK in that it simply acts as a bridge to our underlying mobile SDKs which do follow this divergent discovery pattern. The reasoning is it attempts to use the same pattern and rails as the discover operation for out bluetooth readers which do continually poll and look for new readers and must be cancelled. We're aware of this integration papercut and have tracked it internally in case we do try to alleviate this in a future breaking SDK upgrade. Thanks for the input!.
