### ISSUE TITLE
Location ID and Reader ID is null

### ISSUE THREAD

**Issue by abdul-rafeh** [stripe/stripe-terminal-react-native#366]
I've connected Stripe M2 reader to the sdk and the reader is discovered in onUpdateDiscoveredReaders method but its location ID and reader ID is null.

Has anyone faced this issue?

**Comment by bric-stripe** [comment]
@abdul-rafeh that's expected if the reader hasn't been connected to the account yet, or if switching from test mode to live mode. The reader only gets an ID and a location once it's been connected to. The reader returned after a successful connect should have its id and location id filled in and then future discovery's will return the reader with its location and id filled in.

To assist with identifying what location to register a new reader to you can use `getLocations` to list the locations for the account and get at the location id.

**Comment by abdul-rafeh** [comment]
What about device id? How can I retrieve that? Since location and device id are the two params required to connect with the device.

**Comment by bric-stripe** [comment]
The device id shouldn't be required to connect. The two connect params for a bluetooth reader expected are the location id and the reader object itself that was returned during onUpdateDiscoveredReaders: https://stripe.dev/stripe-terminal-react-native/api-reference/index.html#ConnectBluetoothReaderParams

**Comment by abdul-rafeh** [comment]
Thank you. It worked!
