### ISSUE TITLE
Reinitialize Stripe

### ISSUE THREAD

**Issue by mvincent7891** [stripe/stripe-terminal-react-native#369]
It is sometimes necessary in development as well as in production to switch the location of a device connected to a Stripe Terminal. This is mostly useful in development, but could be relevant in our production app as well for instance when training staff across locations. 

When this happens within the context of the app, I would like to re-initialize Stripe with the new `tokenProvider`, which requests a connection token for the new location. So far, I'm unable to figure out a way to handle the location change without completely restarting the app.

A great solution would just be a `reinitialize()` callback returned from `useStripeTerminal()`, or at least an automatic reinitialization if a change is detected for `tokenProvider`.

An alternative would just be to refetch the connection token if `tokenProvider` changes.

**Comment by jdivock-stripe** [comment]
Hey @mvincent7891 thanks for reaching out. If you look at the `dev-app` in our repo we have that set up to switch merchants on the fly for our own internal testing. While there are a number of patterns in that app you'd never want to deploy to production it does outline how to go about it. I think the key piece you're missing is a call to `clearCachedCredentials` when switching to a new merchant. You can see our call and surrounding logic [here](https://github.com/stripe/stripe-terminal-react-native/blob/5d54e5c3cd244892e71a0db90ed4b75475efa0a8/dev-app/src/App.tsx#L133). Let me know how that works out for you!

**Comment by mvincent7891** [comment]
That's perfect, will try that and report back. Thanks @jdivock-stripe!

**Comment by mvincent7891** [comment]
Works great!

**Comment by zameschua** [comment]
Hey @jdivock-stripe, sorry for commenting on such an old issue.

In the code example above, why is it calling `clearCachedCredentials()` right after `initialize()`?

The usage is pretty different from steps is described in the docs
https://docs.stripe.com/terminal/references/api/js-sdk#clear-cached-credentials
