### ISSUE TITLE
onFinishDiscoveringReaders not working

### ISSUE THREAD

**Issue by johndaskovsky** [stripe/stripe-terminal-react-native#370]
**Describe the bug**
onFinishDiscoveringReaders only fires when there is an error. When discovery is successful it does not run. I see didFinishDiscoveringReaders event called only once a device is connected.

**To Reproduce**

1. Run discoverReaders()
2. Test onFinishDiscoveringReaders with logging
3. No logs on successful discovery

**Expected behavior**
onFinishDiscoveringReaders should fire when discovery succeeds or fails

**Comment by jdivock-stripe** [comment]
Hi @johndaskovsky , thanks for the report. I'm having trouble reproducing, can you please fill out the questions that were in the template to provide me enough information to dig in here? mainly iOS or android?

**Comment by vivekvardhanadepu** [comment]
@jdivock-stripe you can try the example app and check the logs. It is the same for me. Only `didUpdateDiscoveredReaders` is getting called. I am using android 12 emulator

**Comment by parkerbo** [comment]
@vivekvardhanadepu I have experienced this as well, and onFinishDiscoveringReaders only fires when discovering is truly completed (when connected to a reader or if cancelDiscovering is called)

**Comment by billfinn-stripe** [comment]
Hi -- reader discovery can be considered a polling process. Discovery is only "finished" when it's canceled, encounters an error, or the application connects to a reader.

We did recently fix a bug for Android where the promise returned from `discoverReaders` was never resolving.

**Comment by vivekvardhanadepu** [comment]
> Hi -- reader discovery can be considered a polling process. Discovery is only "finished" when it's canceled, encounters an error, or the application connects to a reader.
> 
> We did recently fix a bug for Android where the promise returned from `discoverReaders` was never resolving.

Thanks!! I suggest this be mentioned in the docs
