### ISSUE TITLE
`discoverReaders` never resolves when successfull

### ISSUE THREAD

**Issue by melarts** [stripe/stripe-terminal-react-native#371]
**Describe the bug**

When I call `discoverReaders`, I **never receive the resolved promise** of this call even though I am receiving `didUpdateDiscoveredReaders` callback event.

However this is a problem because if I call `cancelDiscovering` and then try to call `discoverReaders` again, then I will this time get my promise resolved with and `error`.

```
{
    "code": "READER_ERROR.READER_BUSY",
    "message": "Could not execute discoverReaders because the SDK is busy with another command: discoverReaders."
}
```
**To reproduce**

(If it is useful)

- Device: Galaxy Tab S5e
- "react-native": "0.63.4"
- Gradle Plugin version 4.0.0
- Gradle version: 6.5
-  buildToolsVersion = "31.0.0"
- minSdkVersion = 21
-  compileSdkVersion = 31
- targetSdkVersion = 31
- supportLibVersion = "28.0.0"

**Comment by jdivock-stripe** [comment]
Hey @melarts thanks for the report. I'm unable to to reproduce this behavior in our dev-app, adding console statements shows our discover call to reliably resolve upon completion here https://github.com/stripe/stripe-terminal-react-native/blob/72798a4920a7980530502b097fc03eadccb76fbc/dev-app/src/screens/DiscoverReadersScreen.tsx#L143-L146

Is this an internet or a bluetooth discovery? Are you able to see this behavior when spinning our our example implementation or developer app?

**Comment by melarts** [comment]
Hello again !
Thanks for your quick reply. I try to test the behaviour on your example app and the same behaviour happened. I did not change any configuration to match my project setup.

https://github.com/stripe/stripe-terminal-react-native/blob/main/example-app/src/screens/DiscoverReadersScreen.tsx#L132

<img width="598" alt="image" src="https://user-images.githubusercontent.com/16417139/186212642-6954a0c6-1bec-4799-a60e-1f84c5b5b834.png">

I'm succeeded to have the "before" console.log obviously but not the "after".

And the problem is both for wifi and bluetooth readers.

**FYI, I reproduce only this behavior with Android, not iOS.**

**Comment by melarts** [comment]
Hi again @jdivock-stripe  ! Did you have some time to check if you reproduce the error on android too ?

**Comment by melarts** [comment]
Hi @billfinn-stripe and @bric-stripe, sorry again to bother, I am tagging you since I saw you had a recent activity in the other issues. I'm still blocked, does someone reproduce the issue ? Thanks in advance!

**Comment by billfinn-stripe** [comment]
Leaving this open until we release the fix.

**Comment by billfinn-stripe** [comment]
Please try with https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.9.

**Comment by melarts** [comment]
Hello thanks for the reply ! However I still don't understand the fix because there is a huge behavior difference between iOS and Android.

After your fix, the promise only resolves if we cancel the discovering. Whereas in iOS the promise resolves immediately to acknowledge that the discovering is successfull and has started. And this is the behavior on iOS.

**IOS**
https://user-images.githubusercontent.com/16417139/192743058-b1d9d2ae-c54b-46a5-b199-08a6ebc59599.mov

**ANDROID**
(sorry I did not manage to show a clear debugger)
https://user-images.githubusercontent.com/16417139/192744346-078d493b-b3c0-46aa-a5cd-4ee1cba7e276.mp4


Let me know if you need more details.

**Comment by billfinn-stripe** [comment]
Thanks for the extra info. Please try https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.10.

**Comment by melarts** [comment]
It is perfect. I changed the way my initial code was working with the new way of resolving the promise. Thanks a lot for your time!

**Comment by jackdewhurst** [comment]
This is still an issue on 0.0.1-beta.15, on the Android simulator at least. 

Works fine when setting `simulated: true` but setting it to `false` will cause the `discoverReaders` promise to hang indefinitely.

**Comment by jackdewhurst** [comment]
Actually the value of `simulated` makes no difference, `discoverReaders` will always hang on the android simulator. 

Incredibly annoying and I can't find any way to resolve it.

**Comment by viniciusteixeiradias** [comment]
It's not working for me... I followed the setup guide and the `discoverReaders` call hangs indefinitely.

Environment:
* Device: `iPhone 11`
* Stripe SDK: `@stripe/stripe-terminal-react-native@0.0.1-beta.23`
* Expo SDK: `~52.0.40`
* React Native: `0.76.7`

Stripe Terminal:
* BBPOS WisePad 3 ([see more](https://docs.stripe.com/terminal/payments/setup-reader/bbpos-wisepad3))

Steps to reproduce:
1. Create a new React Native app using Expo:
```bash
npx create-expo-app@latest --template blank-typescript
```
2. Install `@stripe/stripe-terminal-react-native`.
3. Initialize the SDK by calling `await initialize()`. **Obs:** I triggered this via a button before attempting to discover readers.
4. Follow the [official setup guide](https://docs.stripe.com/terminal/payments/connect-reader?terminal-sdk-platform=react-native&reader-type=bluetooth), starting from step `1: Discover Readers`.
5. When calling `discoverReader`s, it never resolves and appears to hang indefinitely.

Code:
```tsx
import { StyleSheet, Text, View, Button } from "react-native";
import {
  StripeTerminalProvider,
  useStripeTerminal,
} from "@stripe/stripe-terminal-react-native";

function PaymentScreen() {
  const { discoverReaders, initialize, isInitialized, loading } =
    useStripeTerminal({
      onUpdateDiscoveredReaders: (readers) => {
        console.warn("readers", readers);
      },
    });

  const onInitialize = async () => {
    const { reader, error } = await initialize();

    console.log("res -> ", reader, error); //  null undefined
  };

  const handleDiscoverReaders = async () => {
    if (!isInitialized) {
      return void console.error("Reader not initialized");
    }

    const { error } = await discoverReaders({
      discoveryMethod: "bluetoothScan",
    });

    if (error) {
      console.error("error", error);
    }
  };

  return (
    <View style={styles.container}>
      <Button title="Initialize" onPress={onInitialize} />
      {/* Wait for the reader to be initialized before discovering readers. */}
      <Button title="Discover Readers" onPress={handleDiscoverReaders} />
      {loading ? <Text>Loading...</Text> : <Text>Not Loading...</Text>}
    </View>
  );
}

export default function App() {
  const fetchTokenProvider = async () => {
    const res = await fetch(
      "https://d930-203-30-3-44.ngrok-free.app/connectionToken",
      {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        },
      },
    );

    return await res.json();
  };

  return (
    <StripeTerminalProvider
      logLevel="verbose"
      tokenProvider={fetchTokenProvider}
    >
      <PaymentScreen />
    </StripeTerminalProvider>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

**Comment by viniciusteixeiradias** [comment]
I was able to resolve the issue by updating my `Info.plist` with the following entries:
```xml
<key>UIBackgroundModes</key>
<array>
  <string>bluetooth-central</string>
</array>

<key>NSBluetoothAlwaysUsageDescription</key>
<string>This app requires Bluetooth to connect to payment readers.</string>

<key>NSBluetoothPeripheralUsageDescription</key>
<string>This app requires Bluetooth to connect to payment readers.</string>
```

However, I’d like to suggest reviewing the Stripe documentation ([official setup guide](https://docs.stripe.com/terminal/payments/connect-reader?terminal-sdk-platform=react-native&reader-type=bluetooth)). The current step-by-step guide was not very helpful. The setup process for the `BBPOS WisePad 3` feels inconsistent with the instructions provided.

Thanks!
