### ISSUE TITLE
Unsupported class file major version 60

### ISSUE THREAD

**Issue by harshVikramcrown** [stripe/stripe-terminal-react-native#378]
**Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 60**
This bug is coming on android platform only. i am using @stripe/stripe-terminal-react-native": "^0.0.1-beta.7" . after installation when i run on android i am getting below issue...

FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for JetifyTransform: /Users/macbook/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
         > Failed to transform '/Users/macbook/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 60. (Run with --stacktrace for more details.)

**To Reproduce**

1. Go to android studio
2. Click on Run to install app on emulator
3. Scroll down to bottom after finish processing

**Screenshots**

<img width="1418" alt="Screenshot 2022-09-12 at 11 51 58 AM" src="https://user-images.githubusercontent.com/78845393/189586897-df8e2db3-8084-434a-833d-babcb60afff2.png">

**Device config**

- Device: android emulator
- OS: macOS M1
- gradle wrapper - distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip
- build.gradle - classpath("com.android.tools.build:gradle:4.2.2")
- jdk version - Embedded jdk 11.0.11
- react native - 0.64.2

**Comment by billfinn-stripe** [comment]
Hi @harshVikramcrown -- please see https://github.com/stripe/stripe-terminal-android/issues/211, which is a related issue. Can you try updating your Android gradle plugin version? There's also a workaround suggested on that issue which is to add the moshi jar to the jettifier ignore list.

**Comment by harshVikramcrown** [comment]
> Hi @harshVikramcrown -- please see [stripe/stripe-terminal-android#211](https://github.com/stripe/stripe-terminal-android/issues/211), which is a related issue. Can you try updating your Android gradle plugin version? There's also a workaround suggested on that issue which is to add the moshi jar to the jettifier ignore list.

Thanks @billfinn-stripe 
After blocking the moshi jar by adding android.jetifier.blacklist=moshi-1.13.0.jar in gradle.properties , it's working fine.

**Comment by billfinn-stripe** [comment]
Great. I'm going to close this issue. Thanks.
