### ISSUE TITLE
Getting "No such payment_intent: 'pi_3LiNiUDBzg8BxVzZ0fADyJQb'" on retrievePaymentIntent

### ISSUE THREAD

**Issue by abdulrafeh857** [stripe/stripe-terminal-react-native#379]
**Describe the bug**
Getting "No such payment_intent: 'pi_3LiNiUDBzg8BxVzZ0fADyJQb'" on retrievePaymentIntent after creating the payment intent on server side.

**To Reproduce**
Steps to reproduce the behaviour:
 const { error } = await discoverReaders({
      discoveryMethod: 'bluetoothScan',
      simulated: true
    });
     const { reader, error } = await connectBluetoothReader({
      reader: data,
    });
const response = await createReaderIntentService(obj); // getting secret from server side 
const retrievedResponse = await retrievePaymentIntent(response?.client_secret);
  console.log('\n\n\n\n   retrievePaymentIntent response ', retrievedResponse);
  
 log:  {"error": {"code": "PAYMENT_ERROR.DECLINED_BY_STRIPE_API", "message": "No such payment_intent: 'pi_3LiNiUDBzg8BxVzZ0fADyJQb'"}, "paymentIntent": undefined}

**Expected behaviour**
Payment intent should be retrieved after creating it at backend and passing retrievePaymentIntent function client secret. 

**Screenshots**
![issueimg](https://user-images.githubusercontent.com/37897250/190501031-e244c24d-4b05-43ad-91eb-9b4ccd9f8651.jpeg)

**Smartphone (please complete the following information):**

- Device: Tecno camon 17 and huawei honor 7c
- OS: Android 12 and Android 8 
- WisePad3 BT Simulator

**Comment by billfinn-stripe** [comment]
Hi @abdulrafeh857 -- looking at our logs, it appears the Payment Intent was created under a different account that you were using to retrieve it. Please make sure that you're using the same secret key for creating connection tokens and creating Payment Intents in your backend. I'm going to optimistically close this issue.

**Comment by abdulrafeh857** [comment]
Hi, thanks for input, turns out that device was registered on main account and payment intent was created on a connected account. Thanks for pointing out.
