### ISSUE TITLE
onFinishDiscoveringReaders is not called

### ISSUE THREAD

**Issue by vivekvardhanadepu** [stripe/stripe-terminal-react-native#380]
How to provide timeout to discoverReaders function? If I don't pass any timeout, discoverReaders is not stopped i.e. `onFinishDiscoveringReaders` is not called. I am seeing indefinite logs of `didUpdateDiscoveredReaders` though

**Comment by rachelanordgren** [comment]
Did you resolve this issue? Seeing the same thing
