### ISSUE TITLE
iOS | onDidFinishInstallingUpdate callback | Result error object incorrect formatting

### ISSUE THREAD

**Issue by parkerbo** [stripe/stripe-terminal-react-native#384]
**Describe the bug**
When an error occurs during installing an update, the resulting error object on iOS is incorrectly formatted.

**To Reproduce**

1. Connect to a reader that has a required software update (simulated or physical). Ensure logLevel is set to "verbose"
2. While updating, turn off the physical reader or trigger an error with a simulated reader
3. See console, error object is shown and improperly formatted

Example: The error message is double nested, to access it requires setting a constant to `result.error?.error?.message`
```
 [Stripe terminal]: didFinishInstallingUpdate Object {
  "deviceSoftwareVersion": "2.01.00.15-SZZZ_Prod_US_v1-480001",
  "error": Object {
    "error": Object {
      "code": "ReaderSoftwareUpdateFailedBatteryLow",
      "message": "Updating the reader software failed because the reader's battery is too low. Charge the reader before trying again.",
    },
  },
  "estimatedUpdateTime": "estimate5To15Minutes",
  "requiredAt": "1664312899915",
}
```

**Expected behavior**
I expected the error object to look like it does on android, allowing access like so  `result.error?.message`
Example: 
```
 [Stripe terminal]: didFinishInstallingUpdate Object {
  "deviceSoftwareVersion": "2.01.00.15-SZZZ_Prod_US_v1-480001",
    "error": Object {
      "code": "ReaderSoftwareUpdateFailedBatteryLow",
      "message": "Updating the reader software failed because the reader's battery is too low. Charge the reader before trying again.",
    },
  "estimatedUpdateTime": "estimate5To15Minutes",
  "requiredAt": "1664312899915",
}
```

**Smartphone (please complete the following information):**

- Device: iPhone 13
- OS: iOS 16.0
- Expo: SDK 45

**Comment by bric-stripe** [comment]
thanks for reporting and sorry for the delay getting to this. #412 should fix up the unintentional double nesting there!
