### ISSUE TITLE
estimate as prefix for estimatedUpdateTime

### ISSUE THREAD

**Issue by vivekvardhanadepu** [stripe/stripe-terminal-react-native#388]
What is the reason behind adding `estimate` as prefix like estimate5To15Minutes?

**Comment by billfinn-stripe** [comment]
I don't think I'm understanding your question or problem. The `estimate` prefix is indicating that the time returned is an estimate. The underlying native SDK documentation can be found here:

https://stripe.dev/stripe-terminal-ios/docs/Enums/SCPUpdateTimeEstimate.html
https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.models/-reader-software-update/-update-time-estimate/index.html

**Comment by vivekvardhanadepu** [comment]
I am talking about this ` ReaderSoftwareUpdate.UpdateTimeEstimate.FIVE_TO_FIFTEEN_MINUTES -> "estimate5To15Minutes". ` why `estimate` is prepended to the value? it could be just `5To15Minutes`
