### ISSUE TITLE
initialization error

### ISSUE THREAD

**Issue by ParmarJigarr** [stripe/stripe-terminal-react-native#390]
Hello , 
  I am facing following  error in stripe terminal payment with React native in simulated mode .
  **Error: First initialize the Stripe Terminal SDK before performing any action**

 **Couldn't fetch connection token. Please check your tokenProvider method**

**tokenProvider is not a function**
  Hoping for quick response 

Thanks ,

**Comment by vivekvardhanadepu** [comment]
are you passing tokenProvider function? If so, could you please tell us how it looks?

**Comment by ParmarJigarr** [comment]
IN tokenProvider i am just directly passing secret key state variable !
Let me know what is correct way to pass tokenProvider !

**Comment by vivekvardhanadepu** [comment]
As the error states clearly, you need to pass a function which returns secret. like so,
```
 const tokenProvider = async () => {
    try {
      const res = await createStripeTokenApiCall();
      return res?.secret;
    } catch (err) {
      return '';
    }
  };
  ```
  then pass it to StripeTerminalProvider
  ```
  <StripeTerminalProvider
      tokenProvider={tokenProvider}>
      <App />
    </StripeTerminalProvider>
  ```

**Comment by ParmarJigarr** [comment]
Thanks for response and i had performed this step and working ,
But now as i shared all my code please see that , this is only executing handleDiscoverReaders function which is called in useEffect but after that not calling handleConnectBluetoothReader function at all 
Can you please help me , i am checking this is simulator with react native .

**Comment by ParmarJigarr** [comment]
Hello 
When i navigate first time in my payment screen i am getting " First initialize the Stripe Terminal SDK before performing any action" this error but after goback() i can not see this error 
Can you please help me for the same ?

Also i am getting below error while connecting to device (Simulated device)
code : "ConnectionTokenProviderCompletedWithError"
message: "Connecting to the reader failed because the app completed fetchConnectionToken with an error."

**Comment by vivekvardhanadepu** [comment]
@ParmarJigarr Have you gone through the `example-app`? That should answer many of your questions

**Comment by ParmarJigarr** [comment]
Yes i have checked that but can you please help to here to solve this issues ?

**Comment by nazli-stripe** [comment]
This page goes over each step of initializing the SDK https://stripe.com/docs/terminal/payments/setup-integration?terminal-sdk-platform=react-native#initialize, following this guide and modeling your code after could help with the errors
