### ISSUE TITLE
IOS | Crash the app while call discoverReader method of react native terminal SDK from IOS device

### ISSUE THREAD

**Issue by nirmalsolanki6** [stripe/stripe-terminal-react-native#398]
**Describe the bug**
I have created one application to make payments and added all required permissions Like Location, Bluetooth, etc. to discover readers and make payments I have used methods of react native stripe terminal. all methods are working fine on android devices but When I tried the [discoverReader ](https://stripe.com/docs/terminal/payments/connect-reader) method from IOS devices my app has been crashed. 

**To Reproduce**

For react native sample app
1. Clone and Run [react-native-stripe-terminal](https://stripe.com/docs/terminal/payments/connect-reader) app locally on ios devices
2. Click on the 'Discover Readers' action on the Terminal screen.

**Expected behavior**
I will get the BT reader's list while clicking on Discover Reader click.

**Screenshots**
![ios app crashed](https://user-images.githubusercontent.com/91239478/195534854-178f0e7b-622a-474e-97ab-48347aaa1349.gif)

**Smartphone (please complete the following information):**

- Device: iPhone6s, iPhone XR
- OS: 15.2 and 16.

**Comment by nirmalsolanki6** [comment]
Hi, Can you please give me an update on this issue?

**Comment by nirmalsolanki6** [comment]
Hi,
I have updated the react-native-stripe terminal version to `^0.0.1-beta.11` and IOS app crashed issue has been fixed.

**Comment by ParmarJigarr** [comment]
@nirmalsolanki6 I am also facing same issue and using version of ^0.0.1-beta.8 
With using ^0.0.1-beta.11 will be resolved ?

**Comment by ParmarJigarr** [comment]
It will work in version ^0.0.1-beta.10 ? @kevinlam92 @stripe-checker @janelle-stripe @nirmalsolanki6

**Comment by nirmalsolanki6** [comment]
@ParmarJigarr Yes with the version **^0.0.1-beta.11** will works. Not sure about version **^0.0.1-beta.10**

**Comment by ParmarJigarr** [comment]
@nirmalsolanki6 thanks for reply
 When i am using ^0.0.1-beta.11 and making build xcode is crashing but when i use ^0.0.1-beta.10 xcode is not crashing and build generate successful
is it possible to let me know with ^0.0.1-beta.10 ?

**Comment by nirmalsolanki6** [comment]
Sorry, @ParmarJigarr not sure about version **^0.0.1-beta.10**. Try with an updated version. And I have updated the version to  **^0.0.1-beta.11** seems it's working fine for me.
Which version of Xcode are you using??

**Comment by ParmarJigarr** [comment]
@nirmalsolanki6  I have xcode version with 13.1 
i had try with ^0.0.1-beta.11 but making xcode crash issue while making archive

**Comment by nirmalsolanki6** [comment]
OKay, @ParmarJigarr I have tried the latest version of Xcode and it works for me.

**Comment by ParmarJigarr** [comment]
Hello @nirmalsolanki6  can you please share your discoverReader method function or full .js file ?
Since i am still getting crash issue

**Comment by ParmarJigarr** [comment]
@nirmalsolanki6 Are you there ?

**Comment by ParmarJigarr** [comment]
Hello @nirmalsolanki6  can you please share your discoverReader method function or full .js file ?
Since i am still getting crash issue
