### ISSUE TITLE
Android | Getting error "PAYMENT_ERROR.DECLINED_BY_STRIPE_API" from react native SDK while doing payment.

### ISSUE THREAD

**Issue by nirmalsolanki6** [stripe/stripe-terminal-react-native#403]
**Describe the bug**
I connected the BT reader successfully to my app and then did a successful payment. after that, I removed my app from recent activities and I got the error "PAYMENT_ERROR.DECLINED_BY_STRIPE_API" on the createPaymentIntent method of react-native-stripe SDK.

**To Reproduce**

1. Connect Reader
2. Make payment once
3. Remove the app from recent activity
4. Open the app and try payment again
5. See an error on the createPaymentIntent method of react-native-stripe SDK.

**Expected behavior**
I will do the payment successfully.

**Screenshots**
![payment-error](https://user-images.githubusercontent.com/91239478/196163417-83e9eb60-dd59-4823-9faa-77ffb4791521.gif)

**Smartphone (please complete the following information):**

- Device: Samsung F23
- OS: Android 12

**Additional context**
Request Body

```
{
  "amount": 555,
  "applicationFeeAmount": 15.7745,
  "currency": "usd",
  "customer": "undefined",
  "paymentMethodTypes": [
    "card_present"
  ],
  "setupFutureUsage": "off_session"
}
```
Error

```
{
  "error": {
    "code": "PAYMENT_ERROR.DECLINED_BY_STRIPE_API",
    "message": "You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/."
  },
  "paymentIntent": "undefined"
}
```

**Comment by billfinn-stripe** [comment]
@nirmalsolanki6 -- can you reproduce the same on the example or dev applications?

Can you confirm that your implementation of `tokenProvider` that you pass to `StripeTerminalProvider` fetches a new connection token each time that it's invoked?

**Comment by nirmalsolanki6** [comment]
@billfinn-stripe  I have checked on the stripe sample dev app as well and on the dev app, it's working because when  I removed the dev app from recent activities and open again it asks me every time to discover and connect the reader.

In my case If the user connected once we do have not to ask the user to discover and connect the reader again. we have added code to check and connect the reader automatically.

`Can you confirm that your implementation of tokenProvider that you pass to StripeTerminalProvider fetches a new connection token each time that it's invoked?`

Yes, we do generate connection tokens every time when open the app.

**Comment by billfinn-stripe** [comment]
> In my case If the user connected once we do have not to ask the user to discover and connect the reader again. we have added code to check and connect the reader automatically.

Ah, ok. Are you sure your auto-discovery and auto-connect operations are completing successfully? The error you are seeing makes me think that the subsequent connection is failing. Can you check the `connectedReader` before trying to make a payment for the second time?

Also, if you're still running into problems, can you provide this filtered logcat output?

```
adb logcat -d | grep 'class=Terminal\b'
```

And, inline in the log, you can annotate when/where you're seeing the error.

**Comment by billfinn-stripe** [comment]
Great, I'm going to close this issue.

> Can you please revert me back to the ticket https://github.com/stripe/stripe-terminal-react-native/issues/398

I'm not able to look at this issue immediately, but I'd advice trying to reproduce the issue with the example application to make it easier for us to diagnose. If you find any new information, please add it to that issue.
