### ISSUE TITLE
Android | DiscoverReaders throws an error (SDK Busy) after disconnecting a reader.

### ISSUE THREAD

**Issue by nirmalsolanki6** [stripe/stripe-terminal-react-native#404]
**Describe the bug**
Calling `discoverReaders` method of react native SDK after disconnecting from a reader, and it's throwing an  error `Could not execute discoverReaders because the SDK is busy with another command: discoverReaders`

**To Reproduce**

1. Discover Reader
2. Connect with the Reader
3. Do a Payment
4. Disconnect Reader using the method `disconnectReader` of react native SDK.
5. Discover Reader again
6. See an error

**Expected behavior**
It will discover the reader sucessfully.

**Screenshots**
![SDK-Busy](https://user-images.githubusercontent.com/91239478/196194517-66d0d2da-8b45-4ead-b122-bdd1d3047172.gif)

**Smartphone (please complete the following information):**

- Device: Samsung F23
- OS: Android 12

**Additional context**
Same as ticket  #389

**Comment by billfinn-stripe** [comment]
Can you reproduce with the dev or example apps?

Using the dev app, I am able to:

1. Discover readers
2. Connect to a physical M2 reader
3. Collect a payment
4. Disconnect from the reader
5. Discover readers
6. Connect to the same physical M2 reader

Logcat logs:

```
$ adb logcat -d | grep 'class=Terminal\b'
10-17 12:34:36.871 19375 19435 D StripeTerminal: class=Terminal message=discoverReaders
10-17 12:34:38.752 19375 19476 D StripeTerminal: class=Terminal message=connectBluetoothReader serial_number=<redacted>
10-17 12:34:48.381 19375 19435 D StripeTerminal: class=Terminal message=createPaymentIntent
10-17 12:34:49.631 19375 19435 D StripeTerminal: class=Terminal message=collectPaymentMethod
10-17 12:34:54.219 19375 19435 D StripeTerminal: class=Terminal message=processPayment
10-17 12:34:57.114 19375 19435 D StripeTerminal: class=Terminal message=clearCachedCredentials
10-17 12:34:59.102 19375 19435 D StripeTerminal: class=Terminal message=disconnectReader
10-17 12:35:04.464 19375 19435 D StripeTerminal: class=Terminal message=discoverReaders
10-17 12:35:06.222 19375 19461 D StripeTerminal: class=Terminal message=connectBluetoothReader serial_number=<redacted>
```

**Comment by nirmalsolanki6** [comment]
HI, @billfinn-stripe Thanks for the help,  I have fixed the issue. I canceled the discovery while clicking on the `Discover Reader` action and it's fix my issue.
