### ISSUE TITLE
Read battery level and battery status

### ISSUE THREAD

**Issue by b13i** [stripe/stripe-terminal-react-native#408]
**Is your feature request related to a problem? Please describe.**
We deploy Stripe readers in a retail POS environment across multiple locations. While we strive to keep our readers plugged into the wall, sometimes electrical outlets become faulty or a plug is kicked loose. In these situations, our alerting does not kick in until the reader runs out of battery. We'd like to get ahead of this issue by reading the battery status and triggering an alert when it dips below a threshold.

**Describe the solution you'd like**
Expose reading the Stripe battery level and status from a BBPOS WisPOS E

**Describe alternatives you've considered**
Smart outlets/extensions that can alert on broken outlet statuses

**Comment by marvinklein** [comment]
The native SDK includes an [didReportBatteryLevel](https://stripe.dev/stripe-terminal-ios/docs/Protocols/SCPBluetoothReaderDelegate.html#/c:objc(pl)SCPBluetoothReaderDelegate(im)reader:didReportBatteryLevel:status:isCharging:) event. Are there plans to bubble this event to the javascript side in an upcoming version? If not, would you accept a PR for this? Thanks!

**Comment by nazli-stripe** [comment]
`Reader` object has `isCharging` and `batteryLevel` fields to display this information. Does that not satisfy this user case?

**Comment by nazli-stripe** [comment]
Ah I see. We don't have plans at the moment to add support for this unfortunately, but would always welcome a PR to add support for it!

**Comment by nazli-stripe** [comment]
@marvinklein @b13i we just released `beta.19` built on v3.6.0 native SDKs with the above fix. This release also adds the `onDidUpdateBatteryLevel` and a getter method to access `connectedReader` with real life battery updates
