### ISSUE TITLE
IOS - M2 reader connection attempt -> locationId is null

### ISSUE THREAD

**Issue by tikiwade** [stripe/stripe-terminal-react-native#409]
**Describe the bug**
I just started using this SDK a few days ago. I am create a React Native application for IOS and Android and I am using Expo. I have an iPhone (IOS 16.0.2) and have the app build installed on my phone in developer mode by following the instructions on the Expo website.

I have the discover readers working, and I have gotten the popup to pair with the M2, I have location services enabled on my phone and have my app set to allow location access when using my app. 

My M2 reader is brand new and the device information that the SDK is displaying in the console is as follows

[Stripe terminal]: didUpdateDiscoveredReaders Array [
  Object {
    "availableUpdate": null,
    "batteryLevel": 0.8700000047683716,
    "batteryStatus": "nominal",
    "deviceSoftwareVersion": "2.01.00.15-SZZZ_Prod_US_v1-480001",
    "deviceType": "stripeM2",
    "id": null,
    "ipAddress": null,
    "isCharging": false,
    "label": null,
    "location": null,
    "locationId": null,
    "locationStatus": "notSet",
    "serialNumber": "STRM26146045900",
    "simulated": false,
    "status": "offline",
  },
]

I am using discoveryMethod: 'bluetoothProximity' when calling discoverReaders.
In the response the location and locationId are null.

After I get the discoveredReader I call connectBluetoothReader with the reader object and the locationId from this reader object, which is null, and I get the following error:

connectBluetoothReader error: Object {
  "code": "BluetoothConnectionInvalidLocationIdParameter",
  "message": "The locationId parameter to BluetoothConnectionConfiguration is required but was not provided.",
}

**To Reproduce**

See above

**Expected behavior**
location and locationId to not be null in discoveredReaders

**Screenshots**
N/A

**Smartphone (please complete the following information):**

- Device: iPhone 12 Pro
- OS: 16.0.2

**Additional context**

**Comment by billfinn-stripe** [comment]
Hi @tikiwade -- please create a location, and pass its ID when connecting to the reader. Then, once the reader has been associated with a location, you can pass that same location ID on subsequent connection attempts.

See the [Manage locations](https://stripe.com/docs/terminal/fleet/locations) documentation for creating a location.

**Comment by tikiwade** [comment]
Thank you, that worked.
