### ISSUE TITLE
Application Crash when attempt for discover reader 

### ISSUE THREAD

**Issue by ParmarJigarr** [stripe/stripe-terminal-react-native#410]
Hello 
I Am Jigar from india so do not have physical device (Terminal Reader) , my client is from USA and he have Physical Reader
i am using React native language and below version of the SDK 
 "@stripe/stripe-terminal-react-native": "^0.0.1-beta.8",

I have done code in react native language with using simulated mode ( Since i do not have real reader ) and it is working fine please find below discover reader code i have using in simulated mode 
const handleDiscoverReaders = async () => {
    console.log("called handleDiscoverReaders ==> ")
    // The list of discovered readers is reported in the `didUpdateDiscoveredReaders` method
    // within the `useStripeTerminal` hook.
    const { error } = await discoverReaders({
      discoveryMethod: 'bluetoothScan',
      simulated: true
    });

    if (error) {
   
      Alert.alert(
        'Discover readers error: ',
        `${error.code}, ${error.message}`
      );
  
      console.log("error code ==>", error.code)
      console.log("error message ==>", error.message)
    }

  };
  
  Now i have just put simulated : false key to convert this code in Bluetooth mode 
  But my client is getting crash issue while discover reader
  
  Link we follow : https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=react-native&reader-type=bluetooth
  
  Note : I have shared both build i.e simulated mode and bluetooth mode , with testing simulated mode no crash issue ocuuring but getting crash in bluetooth method
  
  Please help me to resolve this issue 
  Thanks in advance

**Comment by ParmarJigarr** [comment]
Okay i will try with latest version

**Describe the bug**
Application crash while calling discovering reader method with bluetooth mode (simulated : false ), same code working of simulated mode (simulated : true ) !

**To Reproduce**
Steps to reproduce the behavior:

1. Go to call discover reader  app crash


**Expected behavior**
while calling discover reader need to display list of the reader to select and connect bluetooth reader.

**Comment by ParmarJigarr** [comment]
Hello @billfinn-stripe Any update on this ?

**Comment by ParmarJigarr** [comment]
@billfinn-stripe @stripe-checker @arekkubaczkowski @kevinlam92 Any update on this ?

**Comment by billfinn-stripe** [comment]
Hi @ParmarJigarr -- can you reproduce with the example application? If not, can you identify the differences between your application and the example application?

**Comment by ParmarJigarr** [comment]
@billfinn-stripe I have compare both code which are same
I want to let you know that i have also checked with simulated method and it is working totally fine ( discover , connect and payment ) and to convert simulated method to Bluetooth method i just change simulated : true to simulated : false and facing crash issue while discover reader , can you please help me to resolve this issue ?

**Comment by ParmarJigarr** [comment]
@billfinn-stripe any update on this ?
