### ISSUE TITLE
FeatureNotAvailableWithConnectedReader when calling collectPaymentMethod

### ISSUE THREAD

**Issue by tikiwade** [stripe/stripe-terminal-react-native#413]
**Describe the bug**
I am getting the following message in the console
{"code": "FeatureNotAvailableWithConnectedReader", "message": "This feature is currently not available for the selected reader."}
immediately after calling
await collectPaymentMethod()

**To Reproduce**
Discover readers ->connect to reader with location-> create paymentIntent using terminalSDK-> call collectPaymentMethod with the paymentIntent

error appears in console, see below. Note that the last 2 log lines are 1) the payment intent, 2) the error response from collectPaymentMethod.

 LOG  [Stripe terminal]: Connected to the reader:  {"availableUpdate": null, "batteryLevel": 0.8799999952316284, "batteryStatus": "nominal", "deviceSoftwareVersion": "2.01.00.16-SZZZ_Prod_US_v1-480001", "deviceType": "stripeM2", "id": "tmr_E2UVyQmPEDWRlE", "ipAddress": null, "isCharging": false, "label": null, "location": {"address": {"city": "Crystal", "country": "US", "line1": "4836", "line2": "Qual", "postalCode": "55429", "state": "Mn"}, "displayName": "Home ", "id": "tml_E2URAjgWTEAs3U", "livemode": true}, "locationId": "tml_E2URAjgWTEAs3U", "locationStatus": "set", "serialNumber": "STRM26146045900", "simulated": false, "status": "offline"}
 LOG  reader is connected
 LOG  [Stripe terminal]: didChangePaymentStatus notReady
 LOG  [Stripe terminal]: didChangePaymentStatus ready
 LOG  {"amount": 100, "charges": [], "created": "1667838494000", "currency": "usd", "id": "pi_3M1YBGHgbsR35CBO03hsScPw", "status": "requiresPaymentMethod"}
 LOG  {"code": "FeatureNotAvailableWithConnectedReader", "message": "This feature is currently not available for the selected reader."}

**Expected behavior**
To be able to progress to collecting the payment method.

**Screenshots**

**Stripe Terminal React Native SDK version**
"_id": "@stripe/stripe-terminal-react-native@0.0.1-beta.11",
using with Expo

**Smartphone (please complete the following information):**

- Device: iPhone 12Pro
- OS: 16.0.2

**Additional context**

**Comment by billfinn-stripe** [comment]
Hi @tikiwade -- can you show how you are invoking `collectPaymentMethod`? Are you passing a `tipEligibleAmount` parameter? If so, try removing it because the Stripe M2 readers do not support on-reader tipping.
