### ISSUE TITLE
[Android] `connecting`status never send on `onDidChangeConnectionStatus`

### ISSUE THREAD

**Issue by melarts** [stripe/stripe-terminal-react-native#416]
**Describe the bug**

When I call `connectInternetReader` and while the reader is connecting, when I listen to `onDidChangeConnectionStatus`, I never receive `connecting` status. It directly goes from `notConnected` to `connected`.

I only happen for Android. Working fine for iOS.

**To reproduce**

(If it is useful)

- Device: Galaxy Tab S5e
- "react-native": "0.63.4"
- Gradle Plugin version 4.0.0
- Gradle version: 6.5
-  buildToolsVersion = "31.0.0"
- minSdkVersion = 21
-  compileSdkVersion = 31
- targetSdkVersion = 31
- supportLibVersion = "28.0.0"

**Comment by melarts** [comment]
@nazli-stripe any news ?

**Comment by billfinn-stripe** [comment]
Note that the native Android SDK 2.20.0 will include the callback for "connecting" when connecting to internet readers. Once we update the RN SDK to depend on a native Android SDK >= 2.20.0, we can close this issue.

**Comment by nazli-stripe** [comment]
RN SDK now depends on Android SDK v2.20.1 with the latest release: https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.12
