### ISSUE TITLE
M2 Reader shows device connected but not getting success alert while connected 

### ISSUE THREAD

**Issue by ParmarJigarr** [stripe/stripe-terminal-react-native#417]
**Describe the bug**
We are trying to perform bluetooth method since we have m2 reader 
We have testing in simulated mode and working everything fine but after making simulated : false , it is not working as intended ! 
link which we are following : https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=react-native&reader-type=bluetooth

**To Reproduce**
We have can discoverReader method ( step 1) first , after discover method we getting list of reader and displaying those reader name is <Modal/> and on selection of the reader we are calling connectBluetoothReader method ( step 2) , m2 reader is showing device is connected since it is lighting but we are not getting success alert which we have code as per documentation 

**Expected behavior**
Need to get "Reader connected successfully" message we have add below the log as per documentation !

Code of the discover reader and connect reader is below 
  *********************************************
  const handleDiscoverReaders = async () => {
    console.log("called handleDiscoverReaders 1 ==> ")
    // The list of discovered readers is reported in the `didUpdateDiscoveredReaders` method
    // within the `useStripeTerminal` hook.
    const { error } = await discoverReaders({
      discoveryMethod: 'bluetoothProximity',
           simulated: true
    });

    if (error) {
      Alert.alert(
        'Discover readers error: ',
        `${error.code}, ${error.message}`
      );
    }
  };
  *********************************************
  const handleConnectBluetoothReader = async (item) => {
    const { reader, error } = await connectBluetoothReader({
      reader: item,
       locationId: item?.location?.id
    });
    if (error) {
      console.log('connectBluetoothReader error', error);
      Alert.alert(error.message);
      return;
    }
    setIsLoading(false)
    **Alert.alert(
      "GimmeFore",
      "Reader connected successfully",
      [
        { text: "OK", onPress: () => {
          payment()
        } }
      ]
    );**
    console.log('Reader connected successfully', reader);
  };

**Stripe Terminal React Native SDK version**

- 0.0.1-beta.10`

**Smartphone (please complete the following information):**

Please let us know what is the issue , we are not getting the alert which i have highlighted with bold text

**Comment by abdulrafeh857** [comment]
Hey i am getting the same issue. Can you tell how did you manage to resolve this?

**Comment by ParmarJigarr** [comment]
@abdulrafeh857 I have called handleConnectBluetoothReader() method inside onUpdateDiscoveredReaders ! since support was not answering me so i try this way and connect reader successfully 
check below code i have forcefully connect first reader from reader list since there is now any other ways i found 

onUpdateDiscoveredReaders: (readers) => {
       
        // After the SDK discovers a reader, your app can connect to it.
        // Here, we're automatically connecting to the first discovered reader.
       
        handleConnectBluetoothReader(readers[0]);
 
      },
