### ISSUE TITLE
need cancelPaymentIntent example

### ISSUE THREAD

**Issue by jietabb** [stripe/stripe-terminal-react-native#423]
during collecting payment intent, for the cancel case:
we need example for cancelPaymentIntent.

we had tried:
 1. call collectPaymentMethod to stop collecting payment intent.
 2. call terminal.cancelPaymentIntent to cancel payment intent
 but we got following error
run failed: terminal.cancelPaymentIntent:Could not execute cancelPaymentIntent because the SDK is busy with another command: collectPaymentMethod.

could you help us with this problem?
we would like a example with cancelling button during collecting payment

**Comment by billfinn-stripe** [comment]
Please try `cancelCollectPaymentMethod`. If you run the example app, start collecting a payment, and then press the back button, the payment collection process should cancel.

See:
https://github.com/stripe/stripe-terminal-react-native/blob/d874d85775b223daf069a0a0a690c156a0fce6d1/example-app/src/screens/CollectCardPaymentScreen.tsx#L67

**Comment by sohumango** [comment]
Thanks a lot for your answer.
We succeed with stopping collecting by cancelCollectPaymentMethod.
But, the payment intent was left with in "Incomplete" status.
Maybe the "Canceled" status is looking better.
So we want to call cancelPaymentIntent to change the status from "Incomplete" to  "Canceled"

**Comment by billfinn-stripe** [comment]
> So we want to call cancelPaymentIntent to change the status from "Incomplete" to "Canceled"

You can call `cancelPaymentIntent` passing in the Payment Intent's ID.

**Comment by billfinn-stripe** [comment]
Closing this as resolved. Feel free to reopen or create a new issue if your issue has not been addressed.
