### ISSUE TITLE
pod install is no longer working

### ISSUE THREAD

**Issue by plafferty64830** [stripe/stripe-terminal-react-native#435]
Hello,

I was working on the example app a few months back and I've just resumed work on it.
I'm unfortunately having issues with pod install.
Pod install works on other project so this suggests this is not an environment issue.

The error I am getting is as follows:

Ignoring json-2.6.3 because its extensions are not built. Try: gem pristine json --version 2.6.3
<internal:/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require': dlopen(/Users/plafferty/.gem/ruby/2.7.6/gems/date-3.3.3/lib/date_core.bundle, 0x0009): symbol not found in flat namespace '_rb_empty_keyword_given_p' - /Users/plafferty/.gem/ruby/2.7.6/gems/date-3.3.3/lib/date_core.bundle (LoadError)
        from <internal:/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from /Users/plafferty/.gem/ruby/2.7.6/gems/date-3.3.3/lib/date.rb:4:in `<top (required)>'
        from <internal:/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from <internal:/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/time.rb:4:in `<top (required)>'
        from <internal:/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from <internal:/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/activesupport-6.1.7/lib/active_support/xml_mini.rb:3:in `<top (required)>'
        from <internal:/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from <internal:/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/activesupport-6.1.7/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
        from <internal:/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from <internal:/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods.rb:9:in `<top (required)>'
        from <internal:/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from <internal:/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/bin/pod:36:in `<top (required)>'
        from /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod:25:in `load'
        from /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod:25:in `<main>'

**Comment by nazli-stripe** [comment]
hey @plafferty64830 this seems like a ruby issue, make sure the gems are installed for the ruby version you are using. The recommended `gem pristine json --version 2.6.3` command should help.
