### ISSUE TITLE
SDK is busy with collectPaymentMethod after failing it the first time

### ISSUE THREAD

**Issue by mihaildu** [stripe/stripe-terminal-react-native#450]
**Describe the bug**
When I run `collectPaymentMethod()` and it fails, I am not able to run any other SDK method. For example if I try `createPaymentIntent` I get this error message
```
Could not execute createPaymentIntent because the SDK is busy with another command: collectPaymentMethod.
```
I tried running `cancelCollectPaymentMethod` afterwards, by attaching it as event handler to a button, but I still get the error message above when trying to create a payment intent.

**To Reproduce**
I have the same setup described here https://github.com/stripe/stripe-terminal-react-native/pull/441 (with `simulated: true`). I know it shouldn't work with simulated readers, but I think running it this way helped uncover this other potential issue. So I am able to connected to the local mobile simulated reader, create a payment intent and afterwards when I try to collect payment method (and built-in tap to pay screen has to show) the app crashes with this message
```
Exception 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.' was thrown while invoking collectPaymentMethod on target StripeTerminalReactNative with params...
```
This issue is unrelated to this thread, but after this happens I am not able to run any SDK command again. If I reload the app, and go through the same flow again, it crashes when creating a payment intent with error described above.

**Expected behavior**
I should be able to run createPaymentIntent after collectPaymentMethod fails

**Stripe Terminal React Native SDK version**

Using main branch from this repo - c5019f5db560dc3c174d528b08c277ec3b91eeb2

**Smartphone (please complete the following information):**

- Device: simulated iPhone 14 Pro
- OS: iOS 16.2

**Comment by bric-stripe** [comment]
Sorry for the delay here. The native iOS SDK v3+ no longer fails with "busy with command" as it now queues up commands. The crash when simulated: true has also been fixed. We believe this should be working as expected now in the latest React Native version but please re-open if you're still an issue with the latest version.
