### ISSUE TITLE
Not able to find device initially for the first time.

### ISSUE THREAD

**Issue by AjaySinghPanwar2817** [stripe/stripe-terminal-react-native#451]
When I am trying to connect the stripe terminal device initially. Then, the sdk is not able to find it. But when I go back to previous screen and come to the pairing screen. Then the sdk is able to find the device. Does anybody else face this ?

**Comment by nazli-stripe** [comment]
hey @AjaySinghPanwar2817 this read mores like an integration issue and for those cases [support@stripe.com](support@stripe.com) is the best first step as they are better equipped to assist and debug. If the issue is still persisting I recommend reaching out to them.
