### ISSUE TITLE
Support Cancel when Connecting to a reader and Acquire reader information without connecting to it.

### ISSUE THREAD

**Issue by trungh97** [stripe/stripe-terminal-react-native#453]
### **I have 2 concerns that I want to confirm with you. Please help me to give more information about it**

- When my device is connecting to a reader (status is `connecting`). Do we have any way to cancel it?
- Could we get some reader information like battery status, firmware version,... without connecting to it? In my assumption, we can only get those information when we connect to that device.

**Comment by nazli-stripe** [comment]
- Connect attempt is not cancelable
- Yep, in order to get more information on the reader you need to connect to it first
