### ISSUE TITLE
Regarding tap to pay

### ISSUE THREAD

**Issue by AjaySinghPanwar2817** [stripe/stripe-terminal-react-native#456]
Hey all. There is an issue we are facing right now regarding tap to pay. The issue is Stripe Terminal React Native SDK uses 2.13 version of iOS SDK and Tap to pay on iPhone is available in 2.18 version. There is a version conflict in here. We have implemented stripe terminal in our react native app and we also want to implement tap to pay. How can we do this ?

**Comment by AjaySinghPanwar2817** [comment]
Seems like there is already a discussion here https://github.com/stripe/stripe-terminal-react-native/issues/439#issuecomment-1456154390 regarding this. So, Is there any ETA for this. Thanks

**Comment by chenzesam** [comment]
I have the same problem, but I solved it by publishing the main branch of this repo and replacing the module(@stripe/stripe-terminal-react-native) with my published version. @AjaySinghPanwar2817

**Comment by chenzesam** [comment]
@billfinn-stripe Do we have a planned release time?

**Comment by chr-stripe** [comment]
Hi folks, thanks for reaching out to us about getting support for Tap to Pay in the React Native SDK. Right now we’re targeting a new release for end of May at the latest. We’ll update this thread as well once the next release lands.

**Comment by karmatradeDev** [comment]
hi, just wanted to check on the ETA of this are you still targeting end of May?

**Comment by nazli-stripe** [comment]
Hi folks, thanks for your patience. We are planning on releasing the new version with Tap to Pay Android and iOS support by end of this week.

**Comment by nazli-stripe** [comment]
Tap to Pay support added in the latest release: https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.12
