### ISSUE TITLE
Location permissions

### ISSUE THREAD

**Issue by mihaildu** [stripe/stripe-terminal-react-native#458]
Hello!

I was wondering why we need the location permission for this package. From the documentation
```
<key>NSLocationWhenInUseUsageDescription</key>
<string>Location access is required in order to accept payments.</string>
```

If we use the package for tap to pay, and create a location on the backend and only use the id of it on the mobile app, is there any other reason for the location permission?

It also seems that if we select "Allow Once" for location, the SDK will error out. I will investigate this a bit more to see why, but do you guys have any ideas on this?

Thank you!

**Comment by bric-stripe** [comment]
> is there any other reason for the location permission?

👋 hi, yes the Terminal SDK internally collects and reports the current location from the device when `processPayment` is called. This is independent of the Stripe location object id passed in when connecting to the reader and is a requirement for processing payments with the SDK.

**Comment by mihaildu** [comment]
Ok, thanks! I will close this issue, it's all I wanted to know :)

Regarding this
> It also seems that if we select "Allow Once" for location, the SDK will error out. I will investigate this a bit more to see why, but do you guys have any ideas on this?

It turned out to be a different problem
