### ISSUE TITLE
reader auto-reconnection due to unexpected disconnection or proximity

### ISSUE THREAD

**Issue by xalec30** [stripe/stripe-terminal-react-native#470]
Hello! 

i am working on my dev app with physical readers, i want to keep the readers autoreconnection by proximity or when the app is in the background. is there any way to make the respective configuration as in the native SDKs?.

**Comment by nazli-stripe** [comment]
We are working on adding support for reconnection by end of this month. I'll update this issue once we have updates on a new release.

**Comment by nazli-stripe** [comment]
@xalec30 we added auto reconnection support in the latest release. You can now pass `autoReconnectOnUnexpectedDisconnect` to connectBluetoothReader to enable it
