### ISSUE TITLE
The `tokenProvider` is triggered 2 times when initializing app

### ISSUE THREAD

**Issue by trungh97** [stripe/stripe-terminal-react-native#476]
**Describe the bug**
When I go to the app for the first time, I see that the `tokenProvider` method in the `StripeTerminalProvider` is triggered 2 times, and it leads to the redundant call of the Create Connection Token API.

**To Reproduce**
- Go to the app for the first time and watch.

**Expected behavior**
I'm not sure if it is a bug, but according to me, the API should be called 1 times, so please help to correct if I missed anything.

**Stripe Terminal React Native SDK version**

- (`^0.0.1-beta.11`)

**Smartphone (please complete the following information):**

- Simulator: [e.g. iPhone14 Pro]

**Additional context**
I have also tried in my code, and it gave the similar result, although the `Root` component only mount 1 time.

**Comment by billfinn-stripe** [comment]
Is this causing a problem for you? It's not entirely unexpected, and your application should, ideally, not have to care how many times a connection token is fetched.

**Comment by trungh97** [comment]
yep, thanks @billfinn-stripe, I just wonder about that behavior and only want to learn more about it.

**Comment by billfinn-stripe** [comment]
Ah, got it. The Terminal SDK makes some stripe.com requests using a connection token, and other times it can use a previously-cached token for the requests. In certain cases, the connection token is exchanged and invalidated for a longer-lived token, so the Terminal SDK must request new connection tokens after it has consumed any previous connection tokens.

As mentioned earlier, ideally, the integration and POS application should not care how often or how many times the SDK fetches a connection token.
