### ISSUE TITLE
App crash on Android when calling initialize() with device location turned off

### ISSUE THREAD

**Issue by guillaumetea** [stripe/stripe-terminal-react-native#484]
Describe the bug:
On android, when calling the `initialize()` function from  the `useStripeTerminal()` hook with location services accepted but turned off, it throws an irrecuperable error:
<img width="371" alt="Screenshot 2023-06-20 at 3 00 03 PM" src="https://github.com/stripe/stripe-terminal-react-native/assets/90262410/d161e6e9-42e7-4275-9e7e-5ab3ba448b8d">

The `initialize()` function does not return a response since it crash before. A try catch block does not catch this error and neither an ErrorBoundary.

Expected behavior:
An error returned from the function or an alert asking the user to turn on the location services

- SDK version: 0.0.1-beta.12

- Device: Google pixel 6
- OS: Android 13

**Comment by tmbax0098** [comment]
**First check permissions**

```
 const granted = await requestNeededAndroidPermissions({
            accessFineLocation: {
              title: "Location Permission",
              message: "Stripe Terminal needs access to your location",
              buttonPositive: "Accept"
            }
          });
          if (granted) {
            // Initialize the SDK
            //here call initial method

          } else {
            console.error(
              "Location and BT services are required in order to connect to a reader."
            );
          }
```

**Comment by nazli-stripe** [comment]
Fixed in https://github.com/stripe/stripe-terminal-react-native/pull/491
