### ISSUE TITLE
Need Tap to pay

### ISSUE THREAD

**Issue by Dhaval1905** [stripe/stripe-terminal-react-native#485]
Hello Stripe Team,

I want to implement the Tap and Pay method with React Native Technology. So is there any way to achieve the same functionality using React Native?

**Comment by billfinn-stripe** [comment]
Please use the latest release in this repo. We currently have no published ReactNative-specific docs, but you should be able to follow the iOS or Android docs the same:
https://stripe.com/docs/terminal/payments/setup-reader/tap-to-pay

**Comment by Dhaval1905** [comment]
@billfinn-stripe  I have performed the step given in this document. But not able to discoveredRedaer for local mobile.
