### ISSUE TITLE
Tap and Pay in React Native

### ISSUE THREAD

**Issue by Dhaval1905** [stripe/stripe-terminal-react-native#487]
Hello Stripe developers,

Would you please help me with implementing the Tap and Pay method using React Native? I have tried with Android and ios both ways but not get any results.

Also want to know that is the reader is required for discover near field communication ?

**Comment by billfinn-stripe** [comment]
Hi @Dhaval1905 -- please start with emailing support@stripe.com. If you've found a bug or have a partially working integration, please fill out the issue template to make it easier for us to answer any questions you have.
