### ISSUE TITLE
Bluetooth disabled on android does not behave as expected

### ISSUE THREAD

**Issue by FabulouSebas** [stripe/stripe-terminal-react-native#490]
**Describe the bug**
On Android, when the bluetooth is disabled, no feedback is given during reader discovery. The discoverReaders will search indefinitely.
On iOS, when the bluetooth is disabled, the discoverReaders fails with a 'BluetoothDisabled' error.

**To Reproduce**
Steps to reproduce the behaviour:

1. Ensure your bluetooth is not enabled
2. Initialize the StripeProvider and StripeTerminal hook
3. Call discoverReaders with discoveryMethod = 'bluetoothScan'
4. Discovery keeps going infinitively

Additional information:
5. Enable bluetooth
6. Stop the discovery with cancelDiscovering
7. Call discoverReaders again
8. Discovery keeps going infinitively

**Expected behaviour**
I would expect it to behave alike iOS and throw a 'BluetoothDisabled' when the discovery is launched. I would also expect the same thing when a user disable the bluetooth during discovery.

A good temporary fix would be that you can recall discoverReaders after the bluetooth is enabled, and the discoverReaders now works.

**Stripe Terminal React Native SDK version**
- 0.0.1-beta.12

**Smartphone :**
SDK version: 0.0.1-beta.12
Device: Google pixel 6
OS: Android 13

**Comment by chr-stripe** [comment]
Thanks for the bug report @FabulouSebas! This will be fixed in the Android SDK first, and then the change will be pulled into a future version of the React Native SDK as well. I'll provide updates in this ticket for when we expect to see this fixed in an upcoming SDK release.

**Comment by chr-stripe** [comment]
We just published version `0.0.1-beta.13`, which now depends on a version of the Android SDK that includes this fix! You should now receive an error on Android when attempting to discover Bluetooth readers while Bluetooth is disabled.

**Comment by FabulouSebas** [comment]
@chr-stripe Thank you! Great work!
