### ISSUE TITLE
Facing Location error

### ISSUE THREAD

**Issue by Dhaval1905** [stripe/stripe-terminal-react-native#499]
Hello, Stripe team I am facing a location issue. 

{"code": "PAYMENT_ERROR.DECLINED_BY_STRIPE_API", "message": "Terminal is currently only available in certain countries. For more information, see https://stripe.com/docs/terminal."}

currentLongitude: -99.35563277907312
currentLatitude: 34.058595855363116

**Comment by nazli-stripe** [comment]
Hi @Dhaval1905  -- please start with emailing [support@stripe.com](mailto:support@stripe.com). If you've found a bug or have a partially working integration, please fill out the issue template to make it easier for us to answer any questions you have.

**Comment by Satya5614** [comment]
I am also facing the same error when I am trying to run the example-app from a non-available country
@Dhaval1905 Did you managed to solve this?
