### ISSUE TITLE
Stripe terminal initialise. 

### ISSUE THREAD

**Issue by Dhaval1905** [stripe/stripe-terminal-react-native#504]
Hello,

I am trying to initialize the Stripe terminal with react native. but getting issues regarding location.  I am following the below steps for the achieve the functionality. 

https://stripe.com/docs/terminal/payments/setup-integration?terminal-sdk-platform=react-native

**Comment by nazli-stripe** [comment]
Hi @Dhaval1905 -- please start with emailing [support@stripe.com](mailto:support@stripe.com). If you've found a bug or have a partially working integration, please fill out the issue template to make it easier for us to answer any questions you have.
