### ISSUE TITLE
Regarding implementation of tap to pay using react native SDK

### ISSUE THREAD

**Issue by AjaySinghPanwar2817** [stripe/stripe-terminal-react-native#505]
Hi stripe developers, Thanks for your hard work adding support for implementing stripe tap to pay feature in react native stripe terminal SDK. Since, there is no updation in documentation. So, it is a little bit difficult for us to implement this feature like how should we proceed ? Since, I am not a native developer of IOS or Android. Hence, I am totally dependent  on react native SDK for the same. Let me know how can I implement this ? 
Thanks

**Comment by nazli-stripe** [comment]
We are in the process of updating our documentation. In the meantime you can take a look at the [Example application](https://github.com/stripe/stripe-terminal-react-native/tree/main/example-app) in this repo to see how tap to pay is implemented.
