### ISSUE TITLE
Post Api Method

### ISSUE THREAD

**Issue by Shivendra437** [stripe/stripe-terminal-react-native#508]
Implemention (Wisepad 3)  ... Trying to fetch the connection Token for Android device  passing post Api -method but in response getting network error ..meanwhile get method is working but not able got get the point why post -Api is giving network error as from code syntax (header) perspective i checked same code in another react-native project their getting response but getting network error while executing in given sdk...

**Comment by nazli-stripe** [comment]
Hi @Shivendra437  -- please start with emailing support@stripe.com. If you've found a bug or have a partially working integration, please fill out the issue template to make it easier for us to answer any questions you have.
