### ISSUE TITLE
Must have a country code to connect to a Tap to Pay reader.

### ISSUE THREAD

**Issue by ljesus** [stripe/stripe-terminal-react-native#511]
**Describe the bug**
On the `connectLocalMobileReader` callback I'm getting an error "Must have a country code to connect to a Tap to Pay reader." on a specific device. This is happening on an Android Redmi 12C device and on an Android Samsung Galaxy A04s and I'm not sure where I should add this country code.

For reference, everything is working correctly with the same code on a Xiaomi 9T.

**To Reproduce**
1 . Call `connectLocalMobileReader` after `discoverReaders`.

**Stripe Terminal React Native SDK version**

- `^0.0.1-beta.12`

**Smartphone (please complete the following information):**

- Device: Redmi 12C
- OS: Android 12

- Device: Samsung Galaxy A04s
- OS: Android 12

**Comment by nazli-stripe** [comment]
Are you passing a location id as shown here: https://github.com/stripe/stripe-terminal-react-native/blob/8454a922/dev-app/src/screens/DiscoverReadersScreen.tsx#L209-L212

The location address should have a country set

**Comment by ljesus** [comment]
I did, this is only affecting two phones, on my Mi 9T it works just fine with the same code.

**Comment by nazli-stripe** [comment]
Hey @ljesus upon looking into this further it seems like that error is returned when the device is having trouble connecting to Stripe backend. The device needs to fetch the location object using the id you pass, and if that call fails this error is returned. We are going to do improvements on our side to return a appropriate error message. There shouldn't be a device specific difference for `connectLocalMobileReader`, can you check if all devices are running the same version of your app and there are no network issues?

**Comment by ljesus** [comment]
It seemed to be an issue with connecting indeed. Would be nice to have some better errors around this, but I'm closing this one for the time being. Thank you!
