### ISSUE TITLE
Stuck on connectBluetoothReader

### ISSUE THREAD

**Issue by aliwaqassi** [stripe/stripe-terminal-react-native#517]
**Describe the bug**
i am using Android 10, physical device is discover but when i try to hit the connectBluetoothReader method, that method is not return the success or any error, stuck in await

**Stripe Terminal React Native SDK version**

0.0.1-beta.12

**Smartphone (please complete the following information):**

- Device: Anroid
- OS: 10

**Comment by Satya5614** [comment]
@aliwaqassi how did you solved the issue
I am able to connect with the simulated reader, but getting stuck on connectBluetoothReader when trying to connect with a physical reader

**Comment by aliwaqassi** [comment]
> @aliwaqassi how did you solved the issue I am able to connect with the simulated reader, but getting stuck on connectBluetoothReader when trying to connect with a physical reader

Could you kindly provide the code.
