### ISSUE TITLE
Update example-app to Use Latest Expo SDK Version

### ISSUE THREAD

**Issue by jd615645** [stripe/stripe-terminal-react-native#518]
**Is your feature request related to a problem? Please describe.**
The current version of example-app is using an outdated Expo SDK version, which is causing compatibility issues and limitations. The app relies on expo-cli that is marked as "not supported in the local CLI." This leads to potential roadblocks and an inability to leverage the latest features and improvements offered by the newer Expo SDK versions.

**Describe the solution you'd like**
I would like to request an update for the example-app to use the latest version of Expo SDK. This update would involve migrating the app to a newer version of Expo SDK, ensuring compatibility with the most recent tools and technologies. By doing so, we can take advantage of the enhanced features, bug fixes, and optimizations that Expo provides, and we can also eliminate any obstacles related to using an unsupported version of expo-cli.

**Describe alternatives you've considered**
As an alternative, we could continue using the current version of example-app with its outdated Expo SDK. However, this would mean missing out on important updates, features, and improvements introduced by Expo in recent versions. Additionally, it may result in compatibility issues with other packages and libraries that have moved forward.

**Additional context**
I strongly emphasize the importance of referring to the official guidance provided in the Expo blog post ([link](https://blog.expo.dev/expo-sdk-48-ccb8302e231)), which outlines the benefits and instructions for migrating to Expo SDK 48. By adhering to Expo's recommendations, we can ensure that example-app remains modern, efficient, and in alignment with industry standards. The transition process may involve code refinements, configuration updates, and possibly revised documentation, all of which will be meticulously addressed to ensure a seamless migration. Given these factors, I urge the prompt adoption of Expo SDK 48 or a higher version in example-app.

**Comment by nazli-stripe** [comment]
Updated in https://github.com/stripe/stripe-terminal-react-native/pull/590
