### ISSUE TITLE
Beta countries not available when connecting a LocalMobileReader

### ISSUE THREAD

**Issue by lletfrix** [stripe/stripe-terminal-react-native#519]
**Describe the bug**
When connecting to a LocalMobile reader on Expo Android with `simulated: false` on a Beta Available country (as seen [here](https://stripe.com/docs/terminal/payments/setup-reader/tap-to-pay), e.g. Spain), it returns the error `{"code": "NETWORK_ERROR.STRIPE_API_ERROR", "message": "country ES is not supported"}`.

**To Reproduce**

1. On an Android Expo project run discover readers with:
```javascript
await discoverReaders({
    discoveryMethod: 'localMobile',
    simulated: false,
});
```
2. Connect to a discovered reader with:
```javascript
const { reader, error } = await connectLocalMobileReader({
    reader: _reader,
    locationId: 'LOCATION_ID',
});
```
3. Log the error from the return value of `connectLocalMobileReader` to see the error.

**Expected behavior**
The app connects to the reader successfully.

**Stripe Terminal React Native SDK version**

- `^0.0.1-beta.12`

**Smartphone**

- Device: Pixel 6
- OS: Android 13

**Comment by nazli-stripe** [comment]
hey @lletfrix the RN SDK is built on an older version of Android SDK and currently doesn't support Tap to Pay in all available regions. From release notes:

> Tap to Pay Android is supported in the Australia, Canada, France, Germany, Ireland, New Zealand, Singapore, the UK and the US.

We are planning to do a new release with Android 2.23 by the end of the month to get it to parity.
