### ISSUE TITLE
Are bluetooth/location permissions required for Tap-to-Pay?

### ISSUE THREAD

**Issue by isaachinman** [stripe/stripe-terminal-react-native#521]
Just getting started with this package. Our use case is _solely_ Tap-to-Pay (both iOS and Android).

If I understand correctly, this feature has only been available since the latest release, `v0.0.1-beta.12`.

I've installed the package in a managed Expo app as per the docs, and submitted to Apple. They flagged the release:

> Your app declares support for bluetooth-central in the UIBackgroundModes key in your Info.plist but we are unable to locate any Bluetooth Low Energy functionality.

Are bluetooth/location permissions required by `@stripe/stripe-terminal-react-native` when only using Tap-to-Pay?

**Comment by bric-stripe** [comment]
@isaachinman you can remove `bluetooth-central` form the background modes list if you don't support Bluetooth readers.

But note the SDK will still require that your application has a `NSBluetoothPeripheralUsageDescription` set even if you don't use a Bluetooth reader. But my understanding is that shouldn't cause an issue in app review (of course, let us know if it does).
