### ISSUE TITLE
Is a connection token required for Tap-to-Pay?

### ISSUE THREAD

**Issue by isaachinman** [stripe/stripe-terminal-react-native#522]
It's clear from all Stripe docs that use of a physical device requires a connection token. However, is a connection token required to solely use Tap-to-Pay? Is a location/location ID required to solely use Tap-to-Pay?

**Comment by billfinn-stripe** [comment]
> However, is a connection token required to solely use Tap-to-Pay?

Yep, it is. The connection token is used to authenticate your merchant account, so the SDK can identify which account is making the requests.

> Is a location/location ID required to solely use Tap-to-Pay?

Yep. All readers must be associated with a location. Locations are used to configure the readers, for example, via [the configuration API](https://stripe.com/docs/api/terminal/configuration).
