### ISSUE TITLE
Location Address displayName typed incorrectly, should be display_name

### ISSUE THREAD

**Issue by theericharms** [stripe/stripe-terminal-react-native#526]
**Describe the bug**

@stripe > stripe-terminal-react-native > lib > typescript > src > types > index.d.ts > Location 

Using the Node Stripe Terminal SDK, displayName is typed incorrectly than what is coming back from Stripe Node Api

stripe.terminal.locations.list

should be display_name

when this is incorrect, on DiscoverReadersScreen, it won't show the picked location name in the ListItem, and does not show the correct name when selecting a location on LocationsScreen

To reproduce, use the node stripe terminal api, set a location

```
const address = {
    "display_name": "Home", // this param needs to be display_name
    "address": {
        "line1": "123 street",
        "city": "Somewhere",
        "postal_code": "91210",
        "state": "CA",
        "country": "US"
    }
const location = await stripe.terminal.locations.create(address)
```

and then retrieving

```
const locations = await stripe.terminal.locations.list({
      limit: 3,
    });
```

it will show as display_name

I thought maybe if you post it as displayName the Stripe API would accept it, but it does if fact expect display_name

maybe its just the Node SDK?  I would think all the SDKs would be talking to the same backend, but please let me know if I am incorrect.

thanks!

**Comment by nazli-stripe** [comment]
Unfortunately Stripe's node SDK is typed differently than Stripe and Terminal React Native SDK. For now, we are planning on sticking to parity with Stripe React Native and keep the types camelCase
