### ISSUE TITLE
App crashes on real device (Expo)

### ISSUE THREAD

**Issue by semrebayrak** [stripe/stripe-terminal-react-native#528]
I have been trying to connect the M2 reader to my expo app ( development build ) . But whenever I try to run discoverReaders function, the app crashes without any errors. I have test it and it's not happening with other functions I exported from useStripeTerminal. When I debug it I realized that it causes some infinite re-render or something. I have the latest version of the SDK. But the interesting thing is it doesn't happen when I run on my simulator.

I am sure that I have set up the StripeTerminalProvider and initialize correctly.

I also did the configuration with my app.config.js

plugins: [
   // Other permissions,
    [
      "@stripe/stripe-terminal-react-native",
      {
        bluetoothBackgroundMode: true,
        locationWhenInUsePermission:
          "Location access is required in order to accept payments.",
        bluetoothPeripheralPermission:
          "Bluetooth access is required in order to connect to supported bluetooth card readers.",
        bluetoothAlwaysUsagePermission:
          "This app uses Bluetooth to connect to supported card readers.",
      },
    ],
  ],

Here is my code.

import AddPayment from "@/components/Onboarding/AddPayment";
import ProgressBar from "@/components/Onboarding/ProgressBar";
import { Colors } from "@/constants";
import { useStripeTerminal } from "@stripe/stripe-terminal-react-native";
import { useCallback, useEffect } from "react";
import { StyleSheet, ScrollView } from "react-native";

export default function AddPaymentPage() {
  const { discoverReaders, discoveredReaders } = useStripeTerminal({
    didUpdateDiscoveredReaders: (readers) => {
      // After the SDK discovers a reader, your app can connect to it.
    },
  });

  useEffect(() => {
    const handleDiscoverReaders = async () => {
      const { error } = await discoverReaders({
        discoveryMethod: "bluetoothScan",
        simulated: true,
      });
    };
    handleDiscoverReaders();
  }, []);

  return (
    <ScrollView
      style={{ backgroundColor: Colors.background }}
      contentContainerStyle={styles.contentContainerStyle}
    >
      <ProgressBar step={5} />
      <AddPayment />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  contentContainerStyle: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
    gap: 16,
    width: "100%",
    backgroundColor: Colors.background,
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
});

**Comment by jd615645** [comment]
Maybe you can try to use adb logcat to get the crash log. I have the same problem, and the crash log is:

```
08-30 11:38:38.965 31806 31839 E StripeTerminal: class=Terminal
08-30 11:38:38.965 31806 31839 E StripeTerminal: java.security.ProviderException: Failed to generate key pair
08-30 11:38:38.965 31806 31839 E StripeTerminal:     at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:515)
```

I've asked on the official technical support Discord, and customer service said that it might be related to my device being rooted (I ran it on another physical device that is not rooted, and it works normally.). You could try to check that.

But so far, I haven't found a solution 😢

**Comment by semrebayrak** [comment]
@jd615645 I had this error on an IOS device. But thanks for sharing!

**Comment by nazli-stripe** [comment]
It looks like this issue is related to integration support. The fastest way to get support for your integration is to reach out directly to our support team: https://support.stripe.com/contact. Gitlab issues should only be submitted for bug reports or feature requests.

**Comment by semrebayrak** [comment]
It's not an integration support. I am trying to use a function from this library and the app crashes

**Comment by willwelo** [comment]
Hello @semrebayrak 
Were you able to resolve your issue. I am getting a similar issue on iIOS, I managed to get the crash log

`*** Assertion failure in -[CBUUID initWithString:safe:], CBUUID.m:219
Exception 'String  does not represent a valid UUID' was thrown while invoking discoverReaders on target StripeTerminalReactNative with params (
        {
        discoveryMethod = bluetoothScan;
        simulated = 0;
    },
    2676,
    2677
)
callstack: (
	0   CoreFoundation                      0x000000018048d8a8 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018008409c objc_exception_throw + 56
	2   Foundation                          0x0000000180d1ba5c _userInfoForFileAndLine + 0
	3   CoreBluetooth                       0x000000019af546c8 -[CBUUID initWithString:safe:] + 464
	4   CoreBluetooth                       0x000000019af5492c +[CBUUID UUIDWithString:] + 44
	5   CoreBluetooth                       0x000000019af22468 -[CBCentralManager initWithDelegate:queue:options:] + 1036
	6   StripeTerminal                      0x0000000107073000 -[DP_BT4_Discovery init] + 176
	7   StripeTerminal                      0x0000000107072f40 +[DP_BT4_Discovery sharedInstance] + 40
	8   StripeTerminal                      0x0000000107076af4 -[DP_BT4_GenericBTv4Controller init] + 172
	9   StripeTerminal                      0x0000000107076a0c +[DP_BT4_GenericBTv4Controller sharedInstance] + 40
	10  StripeTerminal                      0x000000010707bc60 -[DP_GenericChannelController isConnectedBTv4Device] + 20
	11  StripeTerminal                      0x00000001070174b4 -[DP_MainController init_resetCommModeAndControllerState] + 36
	12  StripeTerminal                      0x0000000107016d64 -[DP_MainController init] + 104
	13  StripeTerminal                      0x0000000107016c68 +[DP_MainController sharedController] + 40
	14  StripeTerminal                      0x00000001070623e4 -[DP_BBDeviceController setDelegate:] + 120
	15  StripeTerminal                      0x0000000106f484ec -[SCPBbposAdapter initWithConfigStore:] + 204
	16  StripeTerminal                      0x0000000106f2837c -[SCPBbposBluetoothScanAdapter initWithConfigStore:] + 44
	17  StripeTerminal                      0x0000000106f81578 -[SCPTerminal adapterForConfiguration:] + 368
	18  StripeTerminal                      0x0000000106f80ef0 -[SCPTerminal discoverReaders:delegate:completion:] + 944`

This is with iOS 17.0.1 on both the Simulator and the actual device. 
It does not happen when I set simulated to true when calling discoverReaders

**Comment by rachelanordgren** [comment]
Having this issue on ios with an M2 reader. Has anyone been able to resolve?

**Comment by willwelo** [comment]
I was able to fix my issues. 
The problem I was having was that the changes I made to Info.plist to add the permissions (https://stripe.com/docs/terminal/payments/setup-integration?platform=ios)  in XCode weren't being reflected in the filesystem (maybe due to some iCloud issue not syncing, had my project in iCloud folder. ) After I managed to add the permissions to info.plist the issue disappeared. It now works both simulated and on a real device.

for reference:
iOS 17.1.2
@stripe/stripe-terminal-react-native": "0.0.1-beta.13

**Comment by semrebayrak** [comment]
I was able to run it after trying few months later. Right now if you do your setup correctly it should be working. Please check you are correctly initializing the stripe terminal and giving the permissions.

**Comment by erick-repo** [comment]
I'm getting similar error on on expo for android. Any more ideas?

```
 ERROR  TypeError: Cannot read property 'getConstants' of null, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```
