### ISSUE TITLE
Availability of Tap to Pay on iOS in the UK

### ISSUE THREAD

**Issue by DrChrispoper** [stripe/stripe-terminal-react-native#536]
I'm testing the new build on iOS and getting `The Tap to Pay reader is not supported in the United Kingdom (GB)`
Are the beta countries not available yet on iOS?

**Stripe Terminal React Native SDK version**
- (e.g., `^0.0.1-beta.13`)
- iOS

**Comment by albertpco** [comment]
its only for US/AU i believe currently on iOS. I sadly haven't even reached that point with the terminal, the docs are so heavy.

**Comment by DrChrispoper** [comment]
On this docs page it says it's also the UK.
https://stripe.com/docs/terminal/payments/setup-reader/tap-to-pay?platform=ios

<img width="638" alt="Screenshot 2023-09-04 at 08 11 29" src="https://github.com/stripe/stripe-terminal-react-native/assets/1864825/f6613df2-9ff6-4160-9358-9801e49d1606">

**Comment by bric-stripe** [comment]
Hi, the UK beta is a private beta at the moment. There's a small note about that on that linked page just under the AU/UK entries with how to request access:

> Platforms and businesses located outside the US aren’t permitted to use Tap to Pay on iPhone unless participating in our international beta program. If you’re interested in joining the beta program, please [contact us](https://stripe.com/contact/sales).
