### ISSUE TITLE
More granular Terms and Conditions control

### ISSUE THREAD

**Issue by Eric-Can** [stripe/stripe-terminal-react-native#537]
Currently trying to integrate this SDK for Tap to Pay but could use some more granular terms and conditions control. For example, if I only want an admin to be able to accept the terms and conditions (which is even a use case mentioned on item 2 in Apple's [best practices](https://developer.apple.com/design/human-interface-guidelines/tap-to-pay-on-iphone#Best-practices), I'd have to know whether or not they've already been accepted or at least have some feedback regarding when they've accepted them so I can save that. Or even just being able to call the terms and conditions without having to connect to a reader.

Is the support for this type of granularity on the roadmap? I can see them in the [ProximityReaderAPI](https://developer.apple.com/documentation/proximityreader/paymentcardreader/linkaccount(using:)) (and maybe the stripe IOS SDK but I can't tell) so I know it exists but not sure if itll be supported soon.

**Comment by nazli-stripe** [comment]
Hey did you get a chance to review the discussion in https://github.com/stripe/stripe-terminal-ios/issues/252? In the next release we are adding support for [tosAcceptancePermitted](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPLocalMobileConnectionConfiguration.html#/c:objc(cs)SCPLocalMobileConnectionConfiguration(py)tosAcceptancePermitted) field in the connect configuration. Would that help your case?

**Comment by Eric-Can** [comment]
Hey! This seems like it could be pretty useful for some of my needs but could this be utilized to determine if an account or hasn't accepted the terms and conditions? There are some features where I'd like to conditionally show some things if the terms have been accepted but I can't think of a nice way to do that with this?

**Comment by nazli-stripe** [comment]
Unfortunately that's not possible today, best way is to see if they made a payment already. I'll close this issue in favor of the one in stripe-terminal-ios repo (https://github.com/stripe/stripe-terminal-ios/issues/252) as the feature would need to exist in the iOS SDK first for us to be include in React Native.
