### ISSUE TITLE
Bluetooth permissions should not be required when only using only Tap-to-Pay

### ISSUE THREAD

**Issue by dakkor71** [stripe/stripe-terminal-react-native#539]
Hello,

I'm developing an EXPO app that would use only the Tap-to-pay feature. Right now I'm forced to ask the user for Bluetooth permission even if we don't need it for tap-to-pay at all. My Bluetooth is turned off all the time and all is working like a charm. 

I guess this permission is needed only when working with external terminals that have to be connected via it.

Is it possible to make this permission optional?

Thanks!

**Comment by bric-stripe** [comment]
@dakkor71 can you clarify what platform you're seeing this on? If you're seeing this on Android the fix will be coming when we update the native SDKs to be on 3.0.0 (expected in a release in October likely). If this is iOS it shouldn't be prompting the user but the SDK still requires the "Privacy - Bluetooth Peripheral Usage Description" but it can be left out from the "Required background modes".

**Comment by dakkor71** [comment]
@bric-stripe Yes, this is only an Android issue only. Nice! I can't wait to start using 3.0.0. Thanks!

**Comment by Brunowilliang** [comment]
hi @dakkor71 Did you manage to do tap to pay? I'm facing some problems recognizing the app's reader

```shell
discoverReaders error {"code": "ConnectionTokenProviderCompletedWithError", "message": "Connecting to the reader failed because the app completed fetchConnectionToken with an error."}
```


my code
```tsx
const { discoverReaders, discoveredReaders } = useStripeTerminal({
    onUpdateDiscoveredReaders: (readers) => {
      console.log('onUpdateDiscoveredReaders', readers)
    },
  })

  useEffect(() => {
    handleDiscoverReaders()
  }, [])

  const handleDiscoverReaders = async () => {
    const { error } = await discoverReaders({
      discoveryMethod: 'localMobile',
    })

    if (error) {
      console.log('discoverReaders error', error)
    }
  }
  ```
