### ISSUE TITLE
Tap to pay input screen looks weird on Oppo A9

### ISSUE THREAD

**Issue by dakkor71** [stripe/stripe-terminal-react-native#541]
**Description**

We are developing an Expo App using the tap-to-pay feature from this SDK. We are testing it on multiple devices and noticed that the tap-to-pay input screen looks bad on the Oppo A9 which is marked as a supported phone.

**Expected behavior**

The hold-on button should be placed in the correct position (centered)

**Screenshots**

<img src="https://github.com/stripe/stripe-terminal-react-native/assets/7247735/8c13349c-6452-4063-9272-276550220841" width="150">

**Version**

- ^0.0.1-beta.13`

**Smartphone**

- Device: Oppo
- Modal: A9
- OS: Android 11

**Comment by chr-stripe** [comment]
Hi @dakkor71, thanks for your report. As part of being recognized as a supported phone for Tap to Pay on Android, the Terminal SDK defines a [Device-specific NFC tap zone UI](https://stripe.com/docs/terminal/payments/setup-reader/tap-to-pay?platform=android#device-specific-nfc-tap-zone-ui) based on where we believe the NFC hardware is physically located on the device. On the Oppo A9, this would be near the top-left corner.

Do you find that tapping in the center of the back of the phone is more responsive than where the tap zone is indicated? The indicated section _should_ be the best area, but please let us know if that's not the case!

**Comment by dakkor71** [comment]
Please watch the video made by my teammate (we are using Stripe Test CC). We could do some more tests if that's really needed but it looks like the NFC range is quite big on that phone. If the NFC hardware is located on the top-left my suggestion is only to move the indicating icon to the top-center. Otherwise, it looks really weird. 

https://github.com/stripe/stripe-terminal-react-native/assets/7247735/888942ea-9746-4897-a277-c9adac9f4110

**Comment by dakkor71** [comment]
We actually did some more tests and you are completely right. Even if this screen looks "bad" it indicates where NFC hardware is located so we can assume that it's working as expected.
