### ISSUE TITLE
Tap to Pay screen should rotate when holding the phone upside down to a customer

### ISSUE THREAD

**Issue by niekvolkert** [stripe/stripe-terminal-react-native#542]
**Is your feature request related to a problem? Please describe.**
After seeing a [video of Tap to Pay on iPhone](https://youtu.be/208sSXwB0iQ?t=11), I saw that the elements on the screen flip vertically when holding it upside down, which in my opinion is a must-have functionality for something like Tap to Pay.

**Describe the solution you'd like**
Make the elements on the screen flip vertically when the phone is slightly tilted.

Please let me know if you need more information.

**Comment by sidhant-stripe** [comment]
Hi niekvolkert! This functionality has already been implemented in our native SDKs. The UI elements should already be flipping on iOS builds, whereas on android we have it queued up for our next release which should be out soon.

We are in the process of migrating the React Native SDK to our latest 3.0.0 native SDKs, and we'll be sure to follow up with an update soon!

**Comment by niekvolkert** [comment]
Ok! Great to hear :) Thanks for the reply!
