### ISSUE TITLE
Update min version to ios 12.0 min target version?

### ISSUE THREAD

**Issue by theericharms** [stripe/stripe-terminal-react-native#545]
With the release of xcode 15 and ios 17, pods need to be updated to min target version 12.0.  This repo is currently only supporting 11.0 and Im not able to build for production with xcode 15.

Can we please get an update pod?  Or is there another way we can do this ourselves?  I tried to spec 12.0 in the pod build settings in xcode but doesnt seem to work for me.

Please let me know the best way to proceed.

Thanks!

**Comment by nazli-stripe** [comment]
There is a PR in the works to update the min version to 13.0, that should be merged soon 🤞 
https://github.com/stripe/stripe-terminal-react-native/pull/544

**Comment by nazli-stripe** [comment]
Min version updated to 13 on the latest release: https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.14
