### ISSUE TITLE
How translate texts on Tap to Pay screen?

### ISSUE THREAD

**Issue by dakkor71** [stripe/stripe-terminal-react-native#546]
Hey team!

Is the translation of the texts on the Tap to Pay screen possible? If yes, then please share the instructions on how to make it happen.

Also is it any way to customize the background and button colors to align it with the app typography?

Thanks!

<img class="ZoomableImage" src="https://b.stripecdn.com/docs-statics-srv/assets/tap-to-pay-android-default.69624d1e861554360ba072e708f36b31.gif" width="200px">

**Comment by niekvolkert** [comment]
Hello, can someone have a look at this request?

**Comment by nazli-stripe** [comment]
Hey all, localization for Tap to Pay texts are currently in the works and will be available in a future release. We don't currently have plans for customization but I'll post an update if that changes!
