### ISSUE TITLE
Import module error in expo react native.

### ISSUE THREAD

**Issue by akirus1228** [stripe/stripe-terminal-react-native#548]
I tried to use this module for Tap to pay in expo react native.
As soon as I import the module in my project, I met some errors like `Cannot read property "getConstants" of null`.
![image](https://github.com/stripe/stripe-terminal-react-native/assets/113614003/f3e1340d-2640-4785-858a-392bc6e2a9d6)

**Comment by nazli-stripe** [comment]
Hey @akirus1228 are you still running into this issue in the newest version?

**Comment by marcio** [comment]
Hi @nazli-stripe @akirus1228

@akirus1228, did you have success in fixing it?

I'm getting the same error here. I'm using:

`"@stripe/stripe-terminal-react-native": "^0.0.1-beta.14"`

![SCR-20231220-shbs](https://github.com/stripe/stripe-terminal-react-native/assets/6532/10d6fbb7-0646-488c-a618-ade7d6ee5cf0)

![image](https://github.com/stripe/stripe-terminal-react-native/assets/6532/b2ea6dec-2543-4485-b29a-fbce9121a45f)

**Comment by dmatthews-stripe** [comment]
Hi @akirus1228 , have you tested this with the latest version?

**Comment by nazli-stripe** [comment]
hey @akirus1228 @marcio are you still running into this issue? what version of Expo are you running? Trying to run the app by using the `npx expo run:android` command might help per this comment on another project: https://github.com/RonRadtke/react-native-blob-util/issues/310#issuecomment-1878983528

**Comment by jingchelangelo** [comment]
set newArchEnabled = true  in gradle.properties
