### ISSUE TITLE
SDK ^0.0.1-beta.13: collectPaymentMethod Errors on Optional Parameters after iOS Tap to Pay Update

### ISSUE THREAD

**Issue by amansoomro062** [stripe/stripe-terminal-react-native#549]
**Describe the bug**
After we've updated SDK to ^0.0.1-beta.13 to support IOS Tap to Pay, we're having issue with collectPaymentMethod.

Previously we had code like this

let paymentCollect = await collectPaymentMethod({
      paymentIntentId: paymentIntent.id
    });
    
AND

let paymentCollect = await collectPaymentMethod({
      paymentIntentId: paymentIntent.id,
      skipTipping: true,
      tipEligibleAmount: 1500,
      updatePaymentIntent: false,
    });

We are aware that using  tipEligibleAmount: 1500 is returning error:  Error collecting payment: {"error": {"code": "FeatureNotAvailableWithConnectedReader", "message": "This feature is currently not available for the selected reader."}, "paymentIntent": undefined} But removing the tipEligibleAmount: 1500 throws error: 

Error collecting payment: {"error": {"code": "InvalidRequiredParameter", "message": "A required parameter was invalid or missing."}, "paymentIntent": undefined}

Even though it is optional as defined below:

export declare type CollectPaymentMethodParams = {
    paymentIntentId: string;
    skipTipping?: boolean;
    tipEligibleAmount?: number;
    updatePaymentIntent?: boolean;
};

**To Reproduce**

1. Connect Tap 2 Pay reader on ios using

const { reader, error } = await connectLocalMobileReader({
      reader: selectedReader,
      locationId: locationId,
    });

2. Create payment intent setup

let i = await createPaymentIntentFunction(token, body);

const { paymentIntent, error } = await retrievePaymentIntent(clientSecret);

    if (error) {
      // Placeholder for handling exception
      console.log("ERROR", error);
      return;
    }

    const paymentIntentIdDict = { paymentIntentId: paymentIntent.id };
    let paymentCollect = await collectPaymentMethod({
      paymentIntentId: paymentIntent.id,
      skipTipping: true,
      tipEligibleAmount: 1500,
      updatePaymentIntent: false,
    });

    if (paymentCollect.error) {
      console.log("Error collecting payment:", paymentCollect);
     }
4. You should be able to see the error
5. If you remove other parameters, It'll still throw error.

**Expected behavior**
The collect method should ignore if we are not passing other parameters which are not required and the payment should progress.

**Stripe Terminal React Native SDK version**
^0.0.1-beta.13

**Smartphone (please complete the following information):**

- Device: iPhone 12 pro and iPhone 15 pro
- OS: 16.6.1 and 17.0.2

**Comment by UrbanChrisy** [comment]
I am getting the same issue, did you manage to find a work around. 

Seems like tap to pay iOS is not ready for production use yet.

**Comment by UrbanChrisy** [comment]
Hey @amansoomro062 we got in contact with Stripe and they where able to debug the issue for us which might be the same with you.

Because we had created a payment intent on our backend for a stripe connect account you need to supply the account id of said account in the terminal connection using the `onBehalfOf` field.

```typescript
const {reader, error} = await connectLocalMobileReader({
      reader: selectedReader,
      locationId: 'tml_...',
      onBehalfOf: 'acct_...',
    });
```

**Comment by nazli-stripe** [comment]
hey all, @UrbanChrisy is right on the cause of the issue. @amansoomro062 if that doesn't fix it for you let us know. The error message is unfortunately not helpful in this case, but it will be fixed in a future release.

**Comment by amansoomro062** [comment]
Hi @nazli-stripe 

I've tried above, still the same:

const { reader, error } = await connectLocalMobileReader({
      reader: selectedReader,
      locationId: userData?.terminalLocationId,
      onBehalfOf: userData?.id
    });
    
Error collecting payment: {"error": {"code": "FeatureNotAvailableWithConnectedReader", "message": "This feature is currently not available for the selected reader."},}

**Comment by amansoomro062** [comment]
Thanks @UrbanChrisy and @nazli-stripe 

I was able to sort the issue by removing 

skipTipping: true,
tipEligibleAmount: 1500,
updatePaymentIntent: false,

and adding 

onBehalfOf: 'acct_...',

Appreciate the support 👍
