### ISSUE TITLE
autoReconnectOnUnexpectedDisconnect missing on Tap to Pay iPhone (Local Mobile Reader)

### ISSUE THREAD

**Issue by amansoomro062** [stripe/stripe-terminal-react-native#565]
Tap to pay on iPhone disconnects as soon as the app goes in the background, but when opening the app again, it doesn't connect and has to connect manually.

It would be ideal to introduce the same **autoReconnectOnUnexpectedDisconnect** on mobile readers. (It is currently available for USB Reader and Bluetooth Reader).

Currently, we are manually forcing the reconnect but it does come up with some errors sometimes, we believe it would be more efficient to handle it using autoReconnectOnUnexpectedDisconnect.

**Comment by nazli-stripe** [comment]
Hey @amansoomro062 in the native iOS and Android SDKs the `autoReconnectOnUnexpectedDisconnect` feature is only available for USB and Bluetooth, so React Native SDK is limited to that. Good news is this is on our roadmap for next year and we'll add React Native support once it's added to native SDKs!

**Comment by nazli-stripe** [comment]
@amansoomro062 support for this was added in the latest release: https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.16
