### ISSUE TITLE
Get Stripe commission when payment attempt is processed and response status is correct

### ISSUE THREAD

**Issue by xalec30** [stripe/stripe-terminal-react-native#566]
**Is your feature request related to a problem? Please describe.**
hi how are you, I am implementing a point of sale with the sdk, and I need to reduce the amount of calls to stripe to make the payment flow as fast as possible, and I need to get additional information regarding the payment made.

**Describe the solution you'd like**
be able to implement a response with additional information at the time of the payment process or in the case of implementing a manual capture, be able to obtain it in the capture.

**Comment by nazli-stripe** [comment]
hey @xalec30 what additional information do you need exactly? most of the calls to Stripe are managed by the SDK, what calls are you making and trying to avoid?

**Comment by xalec30** [comment]
hello, I need additional information corresponding to the charge (transaction information) made when the payment has been made successfully by card, at this moment it only returns basic information, (amount, description, payment attempt, status).

I try to avoid making a call to stripe on the server side just to get extended information of the payment attempt and speed up the payment flow.

**Comment by nazli-stripe** [comment]
@xalec30 can you give a list of exact fields as documented on the Stripe API docs? https://stripe.com/docs/api/payment_intents

**Comment by nazli-stripe** [comment]
We added the missing fields RN SDK missing in this PR: https://github.com/stripe/stripe-terminal-react-native/pull/665 The list is limited to what is available by the Terminal iOS SDK [0] and RN SDK will continue to get updated as we add new fields to native SDKs. 

[0] https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPPaymentIntent.html
