### ISSUE TITLE
Unable to connect to reader, tap-to-pay android

### ISSUE THREAD

**Issue by soyoh** [stripe/stripe-terminal-react-native#567]
**Describe the bug**
Hi! I'm testing the integration with RN and expo, I would like to be able to test it on my device (Pixel 3XL) but everytime I try to discover readers I get the error:

```
{"code": "INTEGRATION_ERROR.LOCAL_MOBILE_DEBUG_NOT_SUPPORTED", "message": "Debuggable applications are not supported in the production version of the localmobile reader. Please use a simulated version of the reader by setting `DiscoveryConfiguration.isSimulated` to true."}
 LOG  [Stripe terminal]: didFinishDiscoveringReaders {"error": {"code": "INTEGRATION_ERROR.LOCAL_MOBILE_DEBUG_NOT_SUPPORTED", "message": "Debuggable applications are not supported in the production version of the localmobile reader. Please use a simulated version of the reader by setting `DiscoveryConfiguration.isSimulated` to true."}}
```

As I have a physical test card I would like to test it with it, is there some configuration or anything I'm missing?
If I set `simulated: true` I get a button to `simulate payment` which is not what I want.

Is it possible to use on android having it connected via USB? (as its easier to iterate)

Thanks a lot!

**To Reproduce**

1. Install app oon device
2. use `discover` 

**Expected behavior**

**Screenshots**

**Stripe Terminal React Native SDK version**

- @stripe/stripe-terminal-react-native@^0.0.1-beta.13

**Smartphone (please complete the following information):**

- Device: Pixel 3XL
- OS: Android 12

**Additional context**
I'm using expo, I tried running it via USB and deploying a `development` version to my app, but still no luck.

**Comment by nazli-stripe** [comment]
For security and compliance reasons Tap to Pay doesn't work with debuggable applications. You can set debuggable to false in your build file to be able to test it with a real card.

**Comment by soyoh** [comment]
Thanks @nazli-stripe! that's what I was trying to figure out. wasn't clear from the docs ;)

**Comment by Brunowilliang** [comment]
hey @soyoh, in this case you generated a new build with "developmentClient: false" was that it? and how did you get the logs?

**Comment by marcoripa96** [comment]
I am also trying to figure this out using Expo. Did you find a solution?
