### ISSUE TITLE
Unexpected layout rotation at tap-to-pay screen when calling collectPaymentMethod

### ISSUE THREAD

**Issue by abdulmananqureshi** [stripe/stripe-terminal-react-native#571]
Hello,

I recently implemented the POS on a mobile device and everything was functioning as expected. I intended for the POS app to run on a tablet device. However, I encountered an issue with the screen rotation when navigating to the tap-to-pay screen. The device is configured to remain in portrait mode, but when accessing the tap-to-pay screen, there is a glitch that causes the layout to switch to landscape mode. This issue is particularly problematic when attempting to collect payment information. I am utilizing an [8-inch tablet](https://www.gsmarena.com/samsung_galaxy_tab_active3-10476.php) and require the app to remain in portrait orientation at all times.

![Screenshot_20231116_143659_pos_024529](https://github.com/stripe/stripe-terminal-react-native/assets/113908659/52e07619-bf95-4564-8ea4-3611e2102758)

**Comment by nazli-stripe** [comment]
hey @abdulmananqureshi this behavior is expected, for tablets tap to pay is set to landscape by default and we don't allow specifying the device orientation. I raised this with the team and we'll look into it as a future fix

**Comment by abdulmananqureshi** [comment]
I’ve already changed the app orientation to landscape. It would indeed be handy to have customizable tap-to-pay screens, allowing users to display relevant information just like on the checkout page. This would enhance the overall user experience.
