### ISSUE TITLE
If reader remains connected, payment cannot be processed due to expired connection token

### ISSUE THREAD

**Issue by ts-candide** [stripe/stripe-terminal-react-native#573]
**Describe the bug**
After leaving the app for a while, without disconnecting a reader, calling `processPayment` results in an error:

```
Error: Could not process payment (code: SessionExpired): Expired API Key provided: pss_test_YW*********************************************************************_******NCBG. Platform access may have been revoked.
```

**To Reproduce**

1. Initialise the terminal SDK, discover a reader and connect to it
2. Wait for a while (not exactly sure how long - 60 mins or so? But could be shorter)
3. Call `retrievePaymentIntent` to fetch a payment intent
4. Call `collectPayment`, scan a card on the device
5. Call `processPayment`

**Expected behavior**
The connection token should be automatically refreshed as it has expired. Instead, an error is returned after calling `processPayment`.

**Stripe Terminal React Native SDK version**

- 0.0.1-beta.13

**Smartphone (please complete the following information):**

- Device: iPad 10th generation
- OS: iOS 16.4

**Additional context**

Since we supply a `fetchTokenHandler` to the `StripeTerminalProvider`, I was anticipating that the SDK would handle the lifecycle of the connection token. Perhaps I am doing something wrong. Under what circumstances will the SDK fetch a new token?

**Comment by billfinn-stripe** [comment]
Hi @ts-candide -- thanks for the report here. We have fixed this issue in the underlying native iOS SDK, and we are working to update the ReactNative SDK to depend on the latest iOS SDK version.

The next RN SDK release should fix this issue, and we'll let you know when it's ready.

**Comment by ts-candide** [comment]
Thank you for the reply @billfinn-stripe 

I notice that the current version released to npm (0.0.1-beta.13) is targeting v2.23.1 of the underlying iOS SDK. This issue is a bit of a dealbreaker for us adopting the Stripe terminal. Do you have any idea when a new version based on v3 of the iOS SDK will be available?

In the meantime, would you advocate for us pointing to the `main` branch as this appears to target the newer SDK?

**Comment by billfinn-stripe** [comment]
> In the meantime, would you advocate for us pointing to the main branch as this appears to target the newer SDK?

That would be great to confirm that the `main` branch picking up the latest iOS SDK does, in fact, fix your issue. I'm fairly sure it will, but in case it does not, can you provide your reader serial number, reproduce the problem, and a timestamp in UTC for when you encountered the most recent instance of the problem?

**Comment by ts-candide** [comment]
Hi, I haven't tested with the `main` branch yet, I will wait now until the new version has dropped.

**Comment by ts-candide** [comment]
Unfortunately the project I was working on has been shelved in the short term, so it's unlikely I will be able to perform any more testing on this issue.

**Comment by nazli-stripe** [comment]
@ts-candide sorry to hear that 😕 I am going to close the issue as resolved with the new release, feel free to reopen if someone runs into it still
