### ISSUE TITLE
Bug: DiscoverReaders Method Incorrectly Shows Battery Level as 0 for Discovered Readers

### ISSUE THREAD

**Issue by itbeginswithi** [stripe/stripe-terminal-react-native#588]
**Bug description**
I am using the discoverReaders method to identify nearby card readers via Bluetooth. However, upon discovering readers and displaying their data, the reported battery level is consistently 0. Please note that the connectedReader property extracted from the useStripeTerminal hook successfully returns a reader object that includes a valid battery level. 
This issue does not seem to be related to rendering problems, as the discoverReaders method continually scans for available readers.

**To Reproduce**
1. Find nearby physical readers by using the discoverReaders function from useStripeTerminal.
2. Display their data, you'll see the batteryLevel at 0

**Expected behavior**
When displaying discovered readers, we should get their actual battery level, and not 0. 

**Screenshots**
![image](https://github.com/stripe/stripe-terminal-react-native/assets/34143618/a08bfb96-8a5d-41d1-a8d3-fabfaf917bac)
![image](https://github.com/stripe/stripe-terminal-react-native/assets/34143618/60876318-d829-462f-b0de-017abe2efe4d)

**Stripe Terminal React Native SDK version**
0.0.1-beta.13

**Comment by nazli-stripe** [comment]
Which discovery method are you using? Unfortunately, reader battery level is only available after connection unless you are using `Bluetooth Proximity` method, which is only available for iOS

**Comment by itbeginswithi** [comment]
I'm using Bluetooth scan fore reader discovery.
By 'Bluetooth Proximity', are you referring to the `connectBluetoothReader` method?

**Comment by itbeginswithi** [comment]
I'm using Bluetooth scan for reader discovery.
By 'Bluetooth Proximity', are you referring to the `connectBluetoothReader` method?

**Comment by nazli-stripe** [comment]
@itbeginswithi I am referring to this discoveryMethod option: https://github.com/stripe/stripe-terminal-react-native/blob/0ff34ac0/src/types/Reader.ts#L30

The correct behavior for the SDK should be returning `null` (or basically not returning a battery level field at all) during the discovery phase as we actually do not know the reader's battery before connection
