### ISSUE TITLE
Mismatch between documentation and types file when calling createSetupIntent

### ISSUE THREAD

**Issue by Laulhus** [stripe/stripe-terminal-react-native#591]
**Describe the bug**
When calling function createSetupIntent, params ask to pass a property **customerId** with a string containing the ID of the customer we want to create the setup intent for. If passed like this, property in the API resolves to nullish and therefore, doesn't attach a provided payment method to the customer when calling other functions. This is because the actual name of the property in Stripe API is **customer**, as it says in the documentation.

**To Reproduce**

1. Create a setup intent using the SDK passing a property **customerId**
2. Check the logs in your Stripe dashboard and the setup intent object created will have property customer:null
3. Create a setup intent using the SDK passing a property **customer**
4. Check the logs in your Stripe dashboard and the setup intent object created will have property customer: {{string provided}}

**Expected behavior**
When creating a setup intent passing a customer ID, the object that returns should contain this string in the property customer

**Screenshots**
With property _customerId_:

<img width="496" alt="Captura de pantalla 2023-12-13 a las 11 58 52" src="https://github.com/stripe/stripe-terminal-react-native/assets/94909601/adce4e66-bfb2-46c4-bfe5-a75ed30f49a0">

![Captura de pantalla 2023-12-13 a las 12 03 07](https://github.com/stripe/stripe-terminal-react-native/assets/94909601/e1fa16c8-3261-41f3-9a03-f63d9ce4c8f7)

**Stripe Terminal React Native SDK version**

With property _customer_:
<img width="516" alt="Captura de pantalla 2023-12-13 a las 12 04 04" src="https://github.com/stripe/stripe-terminal-react-native/assets/94909601/8c829ed0-9b37-4ab6-8ef5-2b40f2511747">

![Captura de pantalla 2023-12-13 a las 12 00 35](https://github.com/stripe/stripe-terminal-react-native/assets/94909601/28d389c5-5d4c-456d-b8b1-6052067baa47)

**Stripe Terminal React Native Version**
- ^0.0.1-beta.14

**Comment by nazli-stripe** [comment]
Fixed in https://github.com/stripe/stripe-terminal-react-native/pull/766

**Comment by nazli-stripe** [comment]
This is now publicly available with the release of beta.23
