### ISSUE TITLE
When creating a new react native project and adding the sdk, it fails to build.

### ISSUE THREAD

**Issue by igscl** [stripe/stripe-terminal-react-native#593]
**Describe the bug**
If you follow these steps you'll be able to reproduce the problem. I confirmed with a Stripe engineer on your Discord server and suggested to create an issue.

**To Reproduce**

1- create a new react app using `npx react-native init`
2- `npm i @stripe/stripe-terminal-react-native`
3- change the minSdkVersion to 26 on `build.gradle`
3- build for android

**Expected behavior**
It will error out:
> 'compileDebugJavaWithJavac' task (current target is 17) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version. Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain * Try:

I tried solving by playing with these settings unsuccessfully on the `build.gradle` file

```
        compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
kotlin {
    jvmToolchain(17)
}
```

**Stripe Terminal React Native SDK version**

- `^0.0.1-beta.14`

Thank you!

**Comment by igscl** [comment]
```
    "react": "18.2.0",
    "react-native": "0.73.0"
```

**Comment by simonbengtsson** [comment]
I was getting the same thing. I was able to build by changing `kotlinOptions.jvmTarget` from 18 to 17 (same as the `jvmToolchain` version) in both our `app/build.gradle` and `node_modules/@stripe/stripe-terminal-react-native/android/build.gradle`.

In the stripe-terminal-react-native/build.gradle I I also updated the stripe-terminal-android version to the  just released 3.2.1 version which supports api level 34.

**Comment by igscl** [comment]
We solved this one earlier today by doing something similar, but we changed the sourceCompatibility options as well for `node_modules/@stripe/stripe-terminal-react-native/android/build.gradle`, so your solution might be the right way to do it. Thanks so much for responding! This one caused so much pain to debug.

```
        compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
```

**Comment by igscl** [comment]
We solved this one earlier today by doing something similar, but we changed the sourceCompatibility options as well for `node_modules/@stripe/stripe-terminal-react-native/android/build.gradle`, so your solution might be the right way to do it. Thanks so much for responding! This one caused so much pain to debug.
```
        compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
```

**Comment by prcostello** [comment]
Any updates on amore automatic solution for this at the project level? This is causing additional setup time for our development team and we are having a hard time finding a solution. As well since this is a package `build.gradle` file we cannot commit these changes for others to use.

**Comment by eladgel** [comment]
"react": "18.2.0",
    "react-native": "0.72.6",
    "@stripe/stripe-terminal-react-native": "^0.0.1-beta.14",
Same issue

**Comment by Noitidart** [comment]
> Seeing this as well.
> 
> I'm confused why the versions of `(source/target)Compatibility` and `jvmTarget` would be set to `1.8` for this package in the first place if the `jvmToolchain` is set to `17`. Will have to patch this package for now until this is fixed which isn't a great experience.

Can you please share the solution you did?

**Comment by TheDunco** [comment]
> > Seeing this as well.
> > I'm confused why the versions of `(source/target)Compatibility` and `jvmTarget` would be set to `1.8` for this package in the first place if the `jvmToolchain` is set to `17`. Will have to patch this package for now until this is fixed which isn't a great experience.
> 
> Can you please share the solution you did?

Of course! I used the [`patch-package`](https://www.npmjs.com/package/patch-package) package to locally modify this package on install. The fix was to modify the `@stripe/stripe-terminal-react-native/android/build.gradle` file to have a consistent Java version of 17. 

I just looked at the PRs for this repo and saw [somebody made one with the exact fix I did locally,](https://github.com/stripe/stripe-terminal-react-native/pull/616/files) so hopefully this will be fixed for real soon.

**Comment by Noitidart** [comment]
Thank you very much! <3

**Comment by huzaifa-turkois** [comment]
Has this issue been fixed? Because I am still getting this issue and had to change the Java Versions in the node-modules which does work for now but isn't a permanent solution. Have the devs fixed it?

**Comment by hungcaovn** [comment]
I am getting the same issue, I need to release a new Android version asap. Please release new version soon

**Comment by nazli-stripe** [comment]
hey everyone, we just released a new version with the proposed updates: https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.16

**Comment by hungcaovn** [comment]
Hello guys, after upgrading to v0.0.1-beta.16 I am unable to run npx expo start. It says: 
`PluginError: Failed to resolve plugin for module "@stripe/stripe-terminal-react-native" relative to "....(path to my project)"`

**Comment by MBasiak** [comment]
Same issue as @hungcaovn

**Comment by abhijitCN** [comment]
> hey everyone, we just released a new version with the proposed updates: https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.16
> 
> let us know if upgrading resolves the issues

still, the error is happening after updating to v0.0.1-beta.16 
ERROR =>
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.    
   > Failed to transform jackson-core-2.16.1.jar

**Comment by nazli-stripe** [comment]
@hungcaovn @MBasiak we just released https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.17 to address the Expo plugin issue

@abhijitCN the jackson issue is something separate and is due to the update in the native Terminal SDKs: https://github.com/stripe/stripe-terminal-react-native/issues/653
