### ISSUE TITLE
Linking account on iOS

### ISSUE THREAD

**Issue by dakkor71** [stripe/stripe-terminal-react-native#596]
Hey Guys!

Is there any way to get the state of the linked account? Maybe I just can't find it but it would be nice if such info would be available from the SDK to have better control of initial onboarding flow for iOS.

Thanks!

**Comment by nazli-stripe** [comment]
@dakkor71 what do you mean by the state of the linked account? whether they accepted the terms and conditions?

**Comment by nazli-stripe** [comment]
We don't have a programmatic way of querying that right now, but from our documentation: 

`Users are presented with Apple’s Tap to Pay on iPhone Terms and Conditions the first time they connect to the reader. To register with Apple, you must specify a valid Apple ID representing your business before accepting the terms presented by Apple. You only need to perform this once per Stripe account. This flow isn’t presented on subsequent connections using the same Stripe account, including on other mobile devices.`

does this help keep track of whether the screen will be displayed?
