### ISSUE TITLE
When calling collectPaymentMethod, the tuple returned is {undefined, undefined}.

### ISSUE THREAD

**Issue by LeBabsou** [stripe/stripe-terminal-react-native#604]
**Describe the bug**
When calling collectPaymentMethod, the tuple returned is {undefined, undefined}. I confirmed with a Stripe engineer on your Discord server and suggested to create an issue.

**To Reproduce**

1- `create an expo app`
2- `npm i @stripe/stripe-terminal-react-native`
3- connect to a reader (reproducible with simulated reader)
4- createPaymentIntent
5- retrievePaymentIntent
6- collectPaymentMethod
`const { paymentIntent, error } = await collectPaymentMethod({
      paymentIntent: payment_intent
    });`
7- Log paymentIntent content
8-` npx expo prebuild`
9- `eas build --profile development --platform android`
10- `npx expo start --dev-client`

**Expected behavior**
According to the documentation, if you `await `the collectPaymentMethod to return, it must return a {paymentIntent, error} tuple defined as including the local paymentIntent.

**Stripe Terminal React Native SDK version**

- "@stripe/stripe-terminal-react-native": "^0.0.1-beta.14"
- "react": "18.2.0"
- "react-native": "0.72.6"

**Smartphone (please complete the following information):**

- Device: Tablet
- OS: Android 11

**Additional context**
I am using BBPOS WisePad 3 terminal and paymentMethod : ['card', 'card_present']

**Comment by nazli-stripe** [comment]
Hey @LeBabsou we are not able to reproduce the issue. Is it possible to share an example application you have?
