### ISSUE TITLE
Android client and server-side payment intent creation fails

### ISSUE THREAD

**Issue by kitzj** [stripe/stripe-terminal-react-native#606]
**Describe the bug**
A payment intent fails to be created on the client side, as I get the following error: {"code": "UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR", "message": "Unexpected failure"}. It should be noted that the exact same react native code works perfectly on iOS, so that rules out it being an issue with my code.

On the server-side, payment intents are created successfully, but it is missing the **sdkUuid** parameter, so when **collectPaymentMethod** is subsequently called (taking in the paymentIntent), it fails, citing the **sdkUuid** being missing as the reason.

**To Reproduce**

1. Do the usual configuration, you can just set `simulated` to `true` on the `discoverReaders` function call
2. Create a payment intent on client/server side, then call **collectPaymentMethod**. Make sure to log the errors.
3. Run on Android/iOS to confirm error only occurs on Android

**Expected behavior**
No errors :)

**Screenshots**

**Stripe Terminal React Native SDK version**

^0.0.1-beta.14

**Smartphone (please complete the following information):**

- Device: Any android (simulated device is fun)
- Version: SDK version 33/34

**Additional context**

**Comment by kitzj** [comment]
It goes without saying, but creating a payment intent server side creates the same missing sdkUuid issue for iOS.

**Comment by nazli-stripe** [comment]
> On the server-side, payment intents are created successfully, but it is missing the sdkUuid parameter, so when collectPaymentMethod is subsequently called (taking in the paymentIntent), it fails, citing the sdkUuid being missing as the reason.

Are you using the `retrievePaymentIntent` method to get the PaymentIntent through the SDK after creating it server-side? Using that should ensure there is an `sdkUuid` attached.

**Comment by nazli-stripe** [comment]
Closing this issue as stale, feel free to open a new one if it still persists when using the `retrievePaymentIntent` method.

**Comment by hariharank6** [comment]
I'm facing the same issue. @nazli-stripe If you have a solution, please share it if you can.
