### ISSUE TITLE
Weird error when compatible reader connecting to location

### ISSUE THREAD

**Issue by abdulmananqureshi** [stripe/stripe-terminal-react-native#610]
During initial testing, we successfully connected the reader (Samsung Galaxy A33) phone and were able to initiate payments. However, when we transitioned to using tablets/phablets from China, we encountered an error while establishing a connection to the reader. After searching for a few devices, we found a device that met the requirements listed.

- Contains a functioning NFC antenna and chipset
- Isn’t rooted and the device bootloader is locked and unchanged 
- Runs a current version of Android (Android 10 or above) 		
- Uses Google Mobile Services 	
- Has a hardware-backed keystore 	
- A stable connection to the internet

Despite meeting the compatibility requirements, the connection attempt failed with an unexpected error message. Please provide further guidance on troubleshooting this issue.

`{
  code: 'UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR',
  message:
    "Contactless transaction failed java.lang.IllegalStateException: App Error: SERVER_ERROR 'An unknown error has occurred: java.lang.NoSuchMethodError: No static method reportErrorAsync$default(Lcom/stripe/sentry/http/ErrorReporter;Ljava/lang/Throwable;ZILjava/lang/Object;)V in class Lcom/stripe/sentry/http/ErrorReporter; or its super classes (declaration of 'com.stripe.sentry.http.ErrorReporter' appears in /data/app/~~564MMBgbQ0ntUjd22Hj66w==/com.pos-SpmCVwUvrJyttHHVM8ti2g==/base.apk!classes4.dex)'",
}`

![IMG_0512](https://github.com/stripe/stripe-terminal-react-native/assets/113908659/6b4da2a4-7729-4396-89f6-96f90e944496)

**Comment by abdulmananqureshi** [comment]
Here's a better description after updating the `@stripe/stripe-terminal-react-native` package to `0.0.1-beta.15`

```
|ReactNativeJS 'connectionError', { code: 'UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR',
                              message: 'Failed to generate key pair.' }
```

**Comment by gliu-stripe** [comment]
Resolved in a support ticket thread
