### ISSUE TITLE
Set Timeout for Bluetooth Discovery Scan

### ISSUE THREAD

**Issue by rachelanordgren** [stripe/stripe-terminal-react-native#631]
**Is your feature request related to a problem? Please describe.**
I would like to be able to set a timeout so that I can display a proper empty state if no readers are found during discovery. The [RN docs indicate you can set a timeout](https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=react-native&reader-type=bluetooth#discover-readers) on discovery but not seeing that in params. 

**Describe the solution you'd like**
Ability to set a timeout on discover readers

**Describe alternatives you've considered**
Alternative solution would be to set a timeout then call cancel discovery 

**Additional context**
N/A

**Comment by nazli-stripe** [comment]
Being added in https://github.com/stripe/stripe-terminal-react-native/pull/662
