### ISSUE TITLE
stripe_stripe-terminal-react-native:compileDebugKotlin

### ISSUE THREAD

**Issue by Kashifrafiq** [stripe/stripe-terminal-react-native#637]
I have Strip-terminal -react-native setup in my project, my iOS build is working fine but for my android build it's giving this error:
![image](https://github.com/stripe/stripe-terminal-react-native/assets/101122178/ce46058a-e16a-42df-8655-ebe5ef74fa37)
I have met all the SDK version requirements.

**Stripe Terminal React Native SDK version**

"@stripe/stripe-terminal-react-native": "^0.0.1-beta.13",

**Smartphone (please complete the following information):**

Android Version Tested:

Android: 11 , 12 ,13
Mobile Devices Tested: pixel 4a
Google API Level: 31, 32, 33

**Comment by nazli-stripe** [comment]
hey @Kashifrafiq can you run into this issue with the later SDK releases?
