### ISSUE TITLE
Calling `simulateReaderUpdate` has no effect 

### ISSUE THREAD

**Issue by rachelanordgren** [stripe/stripe-terminal-react-native#645]
**Describe the bug**
I'm trying to use `simulateReaderUpdate` to test out handling software updates. I'm following what the [documentation](https://docs.stripe.com/terminal/references/testing#simulated-reader-updates) entails but not receiving a `didStartInstallingUpdate` callback.

**To Reproduce**

1. Invoke `simulateReaderUpdate('required')`
2. Call `connectBluetoothReader`
3. See `didStartInstallingUpdate` is never received by `useStripeTerminal`

**Stripe Terminal React Native SDK version**

- `0.0.1-beta.15`

**Smartphone (please complete the following information):**

- Device: iPhone 12 Pro Max
- OS: iOS 16.6.1

**Comment by erick-repo** [comment]
Make sure you are importing the functions and make sure you are passing the `simulated: true`
```import {
  collectPaymentMethod,
  confirmPaymentIntent,
  createPaymentIntent,
  retrievePaymentIntent,
  connectLocalMobileReader,
  disconnectReader,
  setSimulatedCard,
} from "@stripe/stripe-terminal-react-native/src/functions";
```
Then you can discover the readers
```
 const { discoverReaders, connectedReader, discoveredReaders } =
    useStripeTerminal({
      onUpdateDiscoveredReaders: (readers) => {
        // access to discovered readers
        //console.log("readers >>>>", readers);
        if (readers.length > 0 && !reader) setReader(readers[0]);
      },
      onDidChangeConnectionStatus: (status) => {
        // access to the current connection status
      },
    });

  useEffect(() => {
    const discoverReadersAsync = async () => {
      const { error } = await discoverReaders({
        discoveryMethod: "bluetoothScan",
        simulated: true,
      });
      if (error) {
        console.log("error_discoverReadersAsync >>>", error);
      }
    };

    discoverReadersAsync();
  }, [discoverReaders]);
  ```

**Comment by rachelanordgren** [comment]
@erick-repo Does `simulateReaderUpdate` only work with simulated readers?

**Comment by rachelanordgren** [comment]
Missed in the documentation that `simulateReaderUpdate` only works with simulated readers. 🤦‍♀️ Closing this as that works.
