### ISSUE TITLE
Support `Stripe-Account` (connect account)

### ISSUE THREAD

**Issue by ALiangLiang** [stripe/stripe-terminal-react-native#647]
**Is your feature request related to a problem? Please describe.**

I want my terminal and payment to be set up under the customer's connect accounts. But this SDK doesn't seem to support it.

**Describe the solution you'd like**

Add a param `stripeAccountId` on every functions.

**Describe alternatives you've considered**

Or add a `setStripeAccountId` function to set it globally

**Additional context**

We use Stripe Reader M2

**Comment by erick-repo** [comment]
I was able to achieve this by using the onBehalfOf field while creating the payment intent.
```
    const { paymentIntent, error } = await createPaymentIntent({
          amount: invoice_total_milicents,
          currency: "usd",
          onBehalfOf: stripe_account_id,
          transferDataDestination: stripe_account_id,
          applicationFeeAmount: platform_fee_milicents,
        });
        
```

**Comment by ALiangLiang** [comment]
> I was able to achieve this by using the onBehalfOf field while creating the payment intent.
> 
> ```
>     const { paymentIntent, error } = await createPaymentIntent({
>           amount: invoice_total_milicents,
>           currency: "usd",
>           onBehalfOf: stripe_account_id,
>           transferDataDestination: stripe_account_id,
>           applicationFeeAmount: platform_fee_milicents,
>         });
>         
> ```

Is it used for `direct charges`? I only find this in `destination charges` and `separate charges`

**Comment by billfinn-stripe** [comment]
Please see https://docs.stripe.com/terminal/features/connect#direct-payment-intents-client-side.

**Comment by ALiangLiang** [comment]
> Please see https://docs.stripe.com/terminal/features/connect#direct-payment-intents-client-side.

Thanks for your reminder. We solved the issue.

`The iOS, Android, and React Native SDKs create the PaymentIntent on the same connected account the ConnectionToken belongs to.`

**Comment by zaidmaknojia** [comment]
**I am receiving this error:**
`Error collecting payment method: {"code": "Unknown", "message": "A required parameter was invalid or missing. Collecting a PaymentMethod for a PaymentIntent `on_behalf_of` a Connected Account requires providing that Connected Account's ID in `SCPLocalMobileConnectionConfiguration`"}`


**Here is my code to create Payment Intent:**
` const {error, paymentIntent} = await createPaymentIntent({
                amount: parseInt(inputValue),
                currency: 'usd',
                captureMethod: 'automatic',
                },`

**Here is my ConneectionToken Code:**

> const response = await fetch('${url}/api/create-account-connection-token', {
>     method: 'POST',
>     headers: {
>       'Content-Type': 'application/json',
>       'Authorization': `Bearer ${bearerToken}`,
>     },
>     body: JSON.stringify({
>       account_id: stripeAccount,
>       location_id: locationId
>     }),
>   })


API Code:

> `async createAccountConnectionToken(req, res) {
> 		try{
> 			const token = await stripe.terminal.connectionTokens.create({
> 					location: req.body.location_id},
> 			{
> 				stripeAccount: req.body.account_id
> 			});
> 			res.json({secret: token.secret});
> 		} catch(err){
> 			res.send(JSON.stringify({
> 				error: err.type,
> 				message: err.message}));
> 		}
> 	}`
