### ISSUE TITLE
Offline Initialization Issue with Wisepad 3

### ISSUE THREAD

**Issue by jongbelegen** [stripe/stripe-terminal-react-native#668]
Hey Stripe Team,

I'm encountering an issue with the Stripe Terminal React Native SDK on iOS for offline payments on the Wisepad 3. 
Offline payments work awesome when initializing the SDK when the device is online.

When starting the app without an internet connection I get the following error:
```
ERROR Couldn't fetch connection token. Please check your tokenProvider method
```

The hook also keeps returning`isInitialized` to `false`. I'm experiencing this behavior in dev mode. 
On production builds it seems to get initialized as you would expect. (Maybe some HTTP caching?)

Here's what I need to know:

Should I be caching the last successful requested token for offline use in my fetchTokenProvider function like this pseudo code, or should the stripe SDK handle this internally?  

```javascript
const fetchTokenProvider= async () => {
  try {
    const response = await fetch(`api/stripe-terminal`, { method: "POST", headers: { "Content-Type": "application/json" } });
    const { secret } = await response.json();
    lastSecret = secret;
    return secret;
  } catch (e) {
    return lastSecret;
  }
};
```

Some documentation about this would also be helpful I think.

Thanks in advance!

**Comment by nazli-stripe** [comment]
hey @jongbelegen are you still running into this issue?

**Comment by nazli-stripe** [comment]
@jongbelegen there are not requirements to keep the device in physical proximity unless you have an active BT connection. 

we'll update the docs to better reflect that token fetching can fail and that's fine
