### ISSUE TITLE
Privacy Manifest file

### ISSUE THREAD

**Issue by SudoPlz** [stripe/stripe-terminal-react-native#670]
Hey there,

are there any plans to add a privacy manifest file for this SDK?

I know that for your other react-native repo you're [working on it](https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#unreleased) but here I don't see any similar efforts.

Thank you for all your great work.

**Comment by nazli-stripe** [comment]
This was added to the native SDK in the latest release, which we'll pick up in our next release ~end of May: https://github.com/stripe/stripe-terminal-ios/releases/tag/3.5.0

**Comment by nazli-stripe** [comment]
The privacy manifest for Terminal iOS SDK is published here: https://github.com/stripe/stripe-terminal-ios/blob/master/Example/StripeTerminal.xcframework/ios-arm64/StripeTerminal.framework/PrivacyInfo.xcprivacy You can directly add it to your application till RN SDK is released with the latest iOS SDK under the hood

**Comment by nazli-stripe** [comment]
Another thing to keep in mind is this requirement is going to affect new apps or new dependencies added to existing apps: 

> Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update.

From: https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by nazli-stripe** [comment]
The beta.18 release bumps iOS SDK to include the privacy manifest
