### ISSUE TITLE
Populate PaymentIntent when there is an error after calling collectPaymentMethod(), confirmPaymentIntent(), etc.

### ISSUE THREAD

**Issue by willwelo** [stripe/stripe-terminal-react-native#674]
**Is your feature request related to a problem? Please describe.**
When calling collectPaymentMethod() or confirmPaymentIntent(), etc. where the return value is a promise of the type PaymentIntentResultType and an error occurs, paymentIntent property is undefined.

` confirmPaymentIntent: (paymentIntent: PaymentIntent.Type) => Promise<import("../types").PaymentIntentResultType>;`

`export declare type PaymentIntentResultType = {
    paymentIntent: PaymentIntent.Type;
    error?: undefined;
} | {
    paymentIntent?: undefined;
    error: StripeError;
};`

So if there is an error paymentIntent is not set. 
It would be useful to know which state the payment intent is in after the error has occurred. 

This functionality seems to be present for other approaches per the documentation
[Handle Failures](https://docs.stripe.com/terminal/payments/collect-payment?terminal-sdk-platform=react-native&lang=php#handling-failures)

**Comment by abhijitCN** [comment]
and you also get this error? calling retrievePaymentIntent(IntentId) then at the time of calling collectPaymentMethod({ paymentIntent: paymentIntent?.id }) this function I gating this error.

  const processPayment = async () => {
    try {
      const { paymentIntent, error } = await retrievePaymentIntent(IntentId);
      if (error) {
        console.log('retrievePaymentIntent Error >> ', error);
        return;
      }
      console.log('paymentIntent?.id for next phase >> ', paymentIntent?.id);
      if (paymentIntent?.id) {
        const { paymentIntent: payment, error: err } = await collectPaymentMethod({ paymentIntent: paymentIntent?.id });
        console.log('Payment Pass >> ', payment);
        if (err) {
          console.log('Payment Error >> ', err);
          return;
        }
      } else {
        console.log('No paymentIntent ID found');
      }
    } catch (error) {
      console.log('An error occurred during the payment process:', error);
    }
  };

![Screenshot_1713784529](https://github.com/stripe/stripe-terminal-react-native/assets/113179261/947fa421-038f-4f88-8f99-26f11a8db19c)

**Comment by nazli-stripe** [comment]
@willwelo being added in https://github.com/stripe/stripe-terminal-react-native/pull/707

**Comment by nazli-stripe** [comment]
@willwelo this has been added in the `beta.19` release: https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.19

**Comment by willwelo** [comment]
> @willwelo this has been added in the `beta.19` release: https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.19

Awesome, thank you! Will upgrade and start using it.
