### ISSUE TITLE
Android 14: "Contactless transaction failed com.stripe.core.aidlrpc.AidlRpcException: Service never connected."

### ISSUE THREAD

**Issue by dakkor71** [stripe/stripe-terminal-react-native#676]
**Describe the bug**

User is not able to discover devices on Android 14

**To Reproduce**

call:
```
await discoverReaders({
        discoveryMethod: 'localMobile',
        simulated: false,
      })
```      
      

**Expected behavior**
The user should be able to discover local devices

**Stripe Terminal React Native SDK version**

- `^0.0.1-beta.17`

**Smartphone (please complete the following information):**

- Device: SAMSUNG Galaxy S23 -SM-S918B 
- OS: Android 14

**Comment by nazli-stripe** [comment]
hey @dakkor71 can you share your account id so we can look at logs for this? thanks

**Comment by ermankos** [comment]
Hi @nazli-stripe. 

I received this error for one of our Android users as well. Reader id was -> b98b57ab-2589-4dd2-b0b5-64a0899322f3

**Comment by nazli-stripe** [comment]
@ermankos which RN SDK version are you on?
