### ISSUE TITLE
Unable to prepare built in card reader on IOS for tap to pay

### ISSUE THREAD

**Issue by MugheesAwan** [stripe/stripe-terminal-react-native#677]
**Describe the bug**
We have tap to pay feature integrated in our App. It was working great, but in last couple of days we are unable to connect to our reader on IOS devices. We are able to connect to the simulated reader but AppleBuiltIn reader is not able to connect even in live mode. Discovery of readers is successful as I get this reader:
`{"availableUpdate": null, "batteryLevel": null, "batteryStatus": "unknown", "deviceSoftwareVersion": null, "deviceType": "appleBuiltIn", "id": null, "ipAddress": null, "isCharging": null, "label": "Apple Built-In (…a659)", "location": {"address": {"city": "Wilmington", "country": "US", "line2": "", "postalCode": "19807", "state": "Delaware"}, "displayName": "Nomod LLC", "livemode": false}, "locationStatus": "set", "simulated": false, "status": "offline"}`
but on trying to connect I get this error:
`{"code": "AppleBuiltInReaderFailedToPrepare", "message": "Unable to prepare the built-in card reader to accept payments. Reconnect the app to the reader."}`

**Stripe Terminal React Native SDK version**
`^0.0.1-beta.15`

**Smartphone (please complete the following information):**

- Device: iPhone11
- OS: 17.4.1

**Comment by nazli-stripe** [comment]
hey @MugheesAwan if you can share your serial number we can look into this further, but in the most likely case for this error unfortunately there is nothing we can do at the moment as we are waiting to hear back from Apple on a potential fix.

**Comment by IkjotCreates** [comment]
Hey @nazli-stripe  the same error is also surfacing on my end. This error "Unable to prepare the built-in card reader to accept payments. Reconnect the app to the reader." is being thrown from Stripe SDK. 
Is there any way to remove linked Tap To Pay reader with apple from Stripe so that we can try the basic resetting of this?

**Comment by MMavrisPaleBlue** [comment]
@nazli-stripe @IkjotCreates @MugheesAwan Any update on this? Some of our users in UK reported this as well.

**Comment by nazli-stripe** [comment]
This seems to be a general issue on 17.4.1, as we wait for a fix from Apple one potential workaround is to follow the steps in this guide: https://support.apple.com/en-ca/101582

**Comment by jedwardblack** [comment]
I recently update to 17.5 on the device where I see this error, but am still seeing it. Any suggestions @nazli-stripe ?

**Comment by jedwardblack** [comment]
I recently updated to 17.5 on the affected device, but am seeing the same issue. The error message is attached. Any suggestions @nazli-stripe ?

`Error Domain=com.stripe-terminal Code=3910 "Unable to prepare the built-in card reader to accept payments. Reconnect the app to the reader." UserInfo={NSLocalizedDescription=Unable to prepare the built-in card reader to accept payments. Reconnect the app to the reader., com.stripe-terminal:PrepareFailedReason=Reader could not be prepared (2999), com.stripe-terminal:ReaderMessage=Error that indicates preparation failed., com.stripe-terminal:Message=Unable to prepare the built-in card reader to accept payments. Reconnect the app to the reader.}`

**Comment by nazli-stripe** [comment]
This is reported to be fixed on 17.5.1, updating iOS versions to the latest should help alleviate the problem

**Comment by tayicheri** [comment]
> This seems to be a general issue on 17.4.1, as we wait for a fix from Apple one potential workaround is to follow the steps in this guide: https://support.apple.com/en-ca/101582

Hello, I encountered the same error on an iPhone running iOS 18.1.1. After following the instructions to reset the iPhone, it started working again. However, this solution is clearly not viable, as I cannot ask all my users to reset their phones. Are there any other solutions?

**Comment by AlbertoAbruzzo** [comment]
> > This seems to be a general issue on 17.4.1, as we wait for a fix from Apple one potential workaround is to follow the steps in this guide: https://support.apple.com/en-ca/101582
> 
> Hello, I encountered the same error on an iPhone running iOS 18.1.1. After following the instructions to reset the iPhone, it started working again. However, this solution is clearly not viable, as I cannot ask all my users to reset their phones. Are there any other solutions?

hello, we have the same problem too but only one some iPhones, others are working
