### ISSUE TITLE
Samsung Tab Active 5 compatibility.

### ISSUE THREAD

**Issue by RambokDev** [stripe/stripe-terminal-react-native#679]
**Is your feature request related to a problem? Please describe.**

We are working with stripe tap to pay on samsung Tab active 3 and Tab active 5. Every things are working fine on the Tab active 3 but on the active 5 we are facing a UI problem when the tap to pay screen is displaying. This one is not the same than the one on the tab active 3. We know that this Tab is no referenced on the Stripe documentation but the payment SDK is working well with only a different UI, so maybe there is somethings that we missed. 

This is the active 5 with no horizontal display (Bug UI)
![active5](https://github.com/stripe/stripe-terminal-react-native/assets/97283640/c43d39a7-5615-4633-a8c3-de15790fbe3e)

This is what we have on the active 3 (good Stripe UI)
![active3](https://github.com/stripe/stripe-terminal-react-native/assets/97283640/be66a178-082f-4b8a-b5eb-d45bf8aff46a)

**Describe the solution you'd like**

Do you have any idea about a possible compatibility soon or a patch ? 

Thanks for your time

**Comment by KillianLarcher** [comment]
We are facing the same problem here!

**Comment by nazli-stripe** [comment]
hey all which version of the SDK are you using?

**Comment by nazli-stripe** [comment]
We made improvements to our tablet detection in the Android SDK in later versions. Can you upgrade to `beta.17` and let us know if it works in landscape mode on Tab Active 5? That upgrade should also help out with Java 17 compatibility!

**Comment by KillianLarcher** [comment]
> We made improvements to our tablet detection in the Android SDK in later versions. Can you upgrade to `beta.17` and let us know if it works in landscape mode on Tab Active 5? That upgrade should also help out with Java 17 compatibility!

When I try to update to beta 17, I can’t build, I have an error related to react-native-reanimated (which looks a bit like this one : https://github.com/stripe/stripe-terminal-react-native/issues/650)

**Comment by nazli-stripe** [comment]
Unfortunately it's not possible to get landscape mode on Active 5 in the earlier SDK versions. If there is an issue related to our SDK in terms of upgrading feel free to open a new issue and we can look into it
