### ISSUE TITLE
Unable to connect to simulated m2 reader on Tap To Pay for iOS (reader id is null)

### ISSUE THREAD

**Issue by sidd-sharma** [stripe/stripe-terminal-react-native#680]
I'm trying to implement Stripe Tap To Pay feature on my React Native app. I'm testing on a simulator. When I call discoverReaders I get the list of simulated readers but none of them has id. Since reader id seems to be required for my next call connectLocalMobileReader, it is not able to connect to the reader

I get the following response with discoveryReader: 'localMobile'

 didUpdateDiscoveredReaders [{"availableUpdate": null, "batteryLevel": null, "batteryStatus": "unknown", "deviceSoftwareVersion": null, "deviceType": "appleBuiltIn", "id": null, "ipAddress": null, "isCharging": null, "label": null, "location": {"address": [Object], "displayName": "Stripe HQ", "id": "st_simulated", "livemode": false}, "locationId": "st_simulated", "locationStatus": "set", "serialNumber": "APPLEBUILTINSIMULATOR-1", "simulated": false, "status": "offline"}]

I get the following response with discoveryReader: 'bluetoothScan' (I believe I'm supposed to use bluetoothScan)

 [{"availableUpdate": null, "batteryLevel": null, "batteryStatus": "unknown", "deviceSoftwareVersion": null, "deviceType": "chipper2X", "id": null, "ipAddress": null, "isCharging": null, "label": null, "location": {"address": [Object], "displayName": "Stripe HQ", "id": "st_simulated", "livemode": false}, "locationId": "st_simulated", "locationStatus": "set", "serialNumber": "CHB20SIMULATOR2", "simulated": true, "status": "offline"}, {"availableUpdate": null, "batteryLevel": null, "batteryStatus": "unknown", "deviceSoftwareVersion": null, "deviceType": "wisePad3", "id": null, "ipAddress": null, "isCharging": null, "label": null, "location": {"address": [Object], "displayName": "Stripe HQ", "id": "st_simulated", "livemode": false}, "locationId": "st_simulated", "locationStatus": "set", "serialNumber": "WPC32SIMULATOR1", "simulated": true, "status": "offline"}, {"availableUpdate": null, "batteryLevel": null, "batteryStatus": "unknown", "deviceSoftwareVersion": null, "deviceType": "stripeM2", "id": null, "ipAddress": null, "isCharging": null, "label": null, "location": {"address": [Object], "displayName": "Stripe HQ", "id": "st_simulated", "livemode": false}, "locationId": "st_simulated", "locationStatus": "set", "serialNumber": "STRM2SIMULATOR1", "simulated": true, "status": "offline"}]

Here is my code:

  const {initialize} = useStripeTerminal();
  useEffect(() => {
    initialize()
  },[])
  
  const { discoverReaders, connectedReader, discoveredReaders } =
  useStripeTerminal({
    onUpdateDiscoveredReaders: (readers) => {
      console.log('readers >>>>>>>>>>>>>> ', readers)
      setReaders(readers[2]);
    },
  });

  useEffect(() => {
    setTimeout(() => {
      if(isInitialized){
        handleDiscoverReaders();
      }
    },3000);
  }, [discoverReaders]);
  
  const handleDiscoverReaders = async () => {
    const {error, readers: discoveredReaders} = await discoverReaders({
      discoveryMethod:  'bluetoothScan',//'internet', //'localMobile',
      simulated: true,
    });
    console.log(error, '===');
  };

iOS version: 17.2
Stripe version: ^0.0.1-beta.15

Not sure if this is a bug or I'm missing something. Please let me know.

Thanks.

**Comment by nazli-stripe** [comment]
For the connection call you pass the full reader object returned from the discover call, see example: https://github.com/stripe/stripe-terminal-react-native/blob/7535dd89/dev-app/src/screens/DiscoverReadersScreen.tsx#L221-L225

This in general is more integration support than SDK bug, for those reaching out to support@stripe.com will get the fastest response

**Comment by sidd-sharma** [comment]
Okay great. Thanks a lot. Will try that out. If you could also update the Stripe Doc which still refers to the reader.id that would be great.

https://docs.stripe.com/terminal/payments/connect-reader?terminal-sdk-platform=react-native&reader-type=simulated

const handleConnectBluetoothReader = async (id) => {
    const { reader, error } = await connectBluetoothReader({
      readerId: discoveredReaders[0].id,
      // Since the simulated reader is not associated with a real location, we recommend
      // specifying its existing mock location.
      locationId: discoveredReaders[0].locationId,
    });
