### ISSUE TITLE
[Tap to Pay] Is there a way to cancel the payment screen on iOS?

### ISSUE THREAD

**Issue by phil-moonward** [stripe/stripe-terminal-react-native#682]
Currently I am unable to programatically dismiss the screen that prompts the user to tap their card to pay on iOS. I would like to be able to set a manual timeout, currently Apple just informs the user that the reader has timed out and prompts them to try again. I thought this might not be possible due to restrictions by Apple, until I came across this in their documentation. https://developer.apple.com/documentation/proximityreader/paymentcardreadersession/cancelread()

Is there any way to achieve this using the Stripe RN SDK? I have tried a few methods following what's written in the docs & SDK reference with no luck.

**Comment by nazli-stripe** [comment]
Hey @phil-moonward unfortunately this is not supported by the native iOS SDK today, but the team is going to add support in an upcoming release. Once it's released on iOS SDK we'll include it in RN SDK.

**Comment by AsaMitakaIT** [comment]
> Hey @phil-moonward unfortunately this is not supported by the native iOS SDK today, but the team is going to add support in an upcoming release. Once it's released on iOS SDK we'll include it in RN SDK.嘿，不幸的是，今天原生 iOS SDK 不支持这个，但团队将会在即将发布的版本中添加支持。一旦它在 iOS SDK 上发布，我们会将其包含在 RN SDK 中。

Sorry to bother you. . . Can you tell me how to do this on the **native iOS SDK**? I can't find anything like this in the documentation and have wasted too much time on supporting forms.

**Comment by nazli-stripe** [comment]
@AsaMitakaIT for native iOS SDK use https://github.com/stripe/stripe-terminal-ios

**Comment by AsaMitakaIT** [comment]
@nazli-stripe Of course... I just don't know how to do it.

**Comment by AsaMitakaIT** [comment]
> [@AsaMitakaIT](https://github.com/AsaMitakaIT) for native iOS SDK create an issue on https://github.com/stripe/stripe-terminal-ios

@nazli-stripe Hello, can you tell me how to do it in React Native SDK? I couldn't find this in the documentation.

**Comment by caretapps-developer** [comment]
@nazli-stripe @AsaMitakaIT , any update/timeline on resolving this issue?
