### ISSUE TITLE
On device handoff payment on a S700 reader, "Current Activity is missing"

### ISSUE THREAD

**Issue by Sheaffy** [stripe/stripe-terminal-react-native#683]
**Describe the bug**
We are implementing the handoff type with a S700 dev kit, discovery is working as expected without issues on all discovery methods.

Upon collectPaymentMethod, it fails and goes no further. When looking at the device logs with logcat we see the following

`Reference to the app's current Activity is missing. Did you call TerminalApplicationDelegate::onCreate before calling initTerminal`

After some investigation and digging, I can see in "StripeTerminalReactNativeModule.kt" line 117
`UiThreadUtil.runOnUiThread { onCreate(context.applicationContext as Application) }`
Is being called in a UIThread.

This occasionally causes this message in the logs when calling initialize `StripeTerminal: class=Terminal message="TerminalApplicationDelegate::onCreate was not called before initTerminal.`

**It is worth noting, I do have this working...** By first adding the below into the build.gradle
`implementation("com.stripe:stripeterminal-core:3.4.0")`
`implementation("com.stripe:stripeterminal-handoffclient:3.4.0")`

Then importing the below into MainApplication.kt
`import com.stripe.stripeterminal.TerminalApplicationDelegate`

Then adding 
`TerminalApplicationDelegate.onCreate(this)`
just below the super.onCreate()

However I would imagine the expected behaviour of this library is that it can simply be installed and have the handoff work "on device" without having to edit your MainApplication.kt or am I wrong?

**To Reproduce**

1. Create a react native application for "on device" POS
2. Side load and start up the application on a S700
3. Start logcat or your logger of preference
4. Initialise the sdk from the function returned by useStripeTerminal()
5. Discover and connect to a handoff device.
6. Start a payment (createPaymentIntent -> collectPaymentMethod)
7. Check the logs and notice the error

**Expected behavior**
A handoff payment on a S700 should work using the react native sdk implementation.

**Screenshots**
![IMG_4718](https://github.com/stripe/stripe-terminal-react-native/assets/17023749/7464d8a5-cae6-4ecd-a8fd-1c893b467e00)
![IMG_4716](https://github.com/stripe/stripe-terminal-react-native/assets/17023749/b18f6406-388f-4913-aaee-71565f6d33e9)

**Stripe Terminal React Native SDK version**
0.0.1-beta.17

**Smartphone (please complete the following information):**

- Device: S700, reader version 2.22.2

**Comment by nazli-stripe** [comment]
hey @Sheaffy unfortunately for handoff mode you will need to edit your MainApplication.kt file. We haven't gotten around to updating the documentation yet, but refer to this PR where we added handoff support for our dev-app: https://github.com/stripe/stripe-terminal-react-native/pull/578/files#diff-9164d5d9dc4cce265ff214d6771592da55824301dac5bb2588bc771b6afcfc96R58

You need to import `com.stripeterminalreactnative.TerminalApplicationDelegate;` and call its `onCreate()` method.

**Comment by Sheaffy** [comment]
Ahh, so my solution is correct then. 
thank you for the clarification.

**Comment by sammwashere** [comment]
Hi, if I can ask, how would I achieve this fix in an Expo app?
As far I can tell, I can't edit the Kotlin files, since there are non in the project files.
The problem appears on the first load of the dev server after starting "npx expo start", if I update any code and it gets pushed to the dev server, it starts working.
