### ISSUE TITLE
Crash issue when connecting via Bluetooth with the M2 reader

### ISSUE THREAD

**Issue by saiDev1999** [stripe/stripe-terminal-react-native#684]
**Describe the bug**
Upon attempting to connect via Bluetooth, the application crashes after discovering devices.

**To Reproduce**
Discover devices.
Click to connect, resulting in app crash.

**Expected behavior**
Successful connection with the device

**Screenshots**
logs from android studio

![Screenshot 2024-05-03 at 3 44 39 PM](https://github.com/stripe/stripe-terminal-react-native/assets/147069591/2239ae23-dc14-4067-a34c-8b8e4b78b93a)

![Screenshot 2024-05-03 at 3 57 19 PM](https://github.com/stripe/stripe-terminal-react-native/assets/147069591/4e1f1860-28c7-4673-96bb-7a87b8b13176)

![Screenshot 2024-05-03 at 11 20 37 AM](https://github.com/stripe/stripe-terminal-react-native/assets/147069591/da2a1d51-56ba-4696-8fdc-f369c8e9a750)

**Stripe Terminal React Native SDK version**
v0.0.1-beta.17

**Additional context**
I suspect the issue might stem from the requirement of registering the location ID with the device for connection. I haven't registered the readers in the dashboard. Is this step necessary for reader connection (Location ID server setup)? What could be the root cause? Can anyone provide assistance with this?

**Comment by nazli-stripe** [comment]
hey @saiDev1999 the logs say it's due to missing the `autoReconnectOnUnexpectedDisconnect` param. We had this issue in an earlier version: https://github.com/stripe/stripe-terminal-react-native/issues/532 but fixed it in v0.0.1-beta.14

It's a bit confusing you are running into this on beta.17. Does it work if you pass that value?

**Comment by saiDev1999** [comment]
Thanks for your response. I've added the autoReconnectOnUnexpectedDisconnect parameter. Now the device is communicating with the SDK. This point isn't mentioned anywhere in the Stripe SDK terminal docs.

**Comment by nazli-stripe** [comment]
That is an optional parameter and you shouldn't need to pass it on `beta.17`. We'll take a look if there is a regression and fix it if needed
