### ISSUE TITLE
Tap to pay "Direct charge" collectPaymentMethod returns "A required parameter was invalid or missing."

### ISSUE THREAD

**Issue by yaromyrshmid** [stripe/stripe-terminal-react-native#695]
**Describe the bug**
When trying to use tap to pay for direct charge, collectPaymentMethod step fails with 
`  "error": {
    "code": "InvalidRequiredParameter",
    "message": "A required parameter was invalid or missing."
  }`

**To Reproduce**

1. Use connectLocalMobileReader from useStripeTerminal to connect to mobile reader, passing locationId param (will return error regardless if you pass onBehalfOf and locationId).
2. Get client secret from API.
3. Use client secret to get payment intent using retrievePaymentIntent.
Payment intent example:
`{"error": undefined, "paymentIntent": {"amount": 5500, "amountDetails": {"tip": [Object]}, "amountTip": 0, "captureMethod": "manual", "charges": [], "created": "1715784108000", "currency": "usd", "id": "pi_3PGj1cCQlMOfJ9yD1GCyVuSC", "metadata": {...}, "offlineDetails": null, "paymentMethod": null, "paymentMethodId": null, "sdkUuid": "47631244-38BE-4B2A-B86C-DB5F05AE2BE4", "statementDescriptor": null, "statementDescriptorSuffix": null, "status": "requiresPaymentMethod"}}`
4. Pass payment intent to collectPaymentMethod:
`const paymentMethodResponse = await collectPaymentMethod({
        paymentIntent: paymentIntentResponse.paymentIntent,
        updatePaymentIntent: true,
      });`
5. Receive error in paymentMethodResponse:
`{
  "error": {
    "code": "InvalidRequiredParameter",
    "message": "A required parameter was invalid or missing."
  }
}`

**Expected behavior**
A screen to collect payment should be visible.

**Stripe Terminal React Native SDK version**

- `^0.0.1-beta.18`

**Smartphone (please complete the following information):**

- Device: iPhone SE (3rd generation) - simulator
- OS: iOS 17.2

**Additional context**
This issue appeared after we switched to direct charges on server side.

**Comment by nazli-stripe** [comment]
Are you creating the location, reader and connection tokens with the Stripe Account header?

**Comment by KindBear** [comment]
Hey!
@nazli-stripe 

I am a team member with @yaromyrshmid 
Yes, we are creating the location, reader and connection tokens with the Stripe Account header

**Comment by yaromyrshmid** [comment]
Issue not reproducible anymore.

**Comment by nabilfreeman** [comment]
I had this error due to not specifying `card_present` at the time of creating the payment intent

**Comment by nazli-stripe** [comment]
@nabilfreeman with the latest release, `beta.19`, the SDK will automatically create PaymentIntents with `card_present` set if you don't specify
