### ISSUE TITLE
[iOS] collectPaymentMethod throws unexpected error and gets stuck from proceeding

### ISSUE THREAD

**Issue by asher5** [stripe/stripe-terminal-react-native#697]
**Describe the bug**
[V0.0.1-beta.18](https://github.com/stripe/stripe-terminal-react-native/blob/10d1d3d7911717563cc66edb7e43f475675e6a3e/ios/Mappers.swift#L622) is crashing when collecting payment on an M2 card reader with the error below
```
[I] <MMKV.cpp:1179::sync> MMKV::sync, SyncFlag = 1
stripe_terminal_react_native/Mappers.swift:647: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```
**To Reproduce**

1. Call collectPaymentMethod with the following params ```{"paymentIntent":{"sdkUuid":"2CD3EF5A-231F-4DFC-8685-4E65F39EFAF8","status":"requiresPaymentMethod","created":"1715808917000","currency":"usd","captureMethod":"manual","paymentMethodId":null,"statementDescriptor":null,"statementDescriptorSuffix":"Asher S","paymentMethod":null,"amountTip":0,"id":"pi_3PGpTlBc6uwoDriN1iqTOhV0","metadata":{"transaction_uuid":"2f56eb0c-7f94-40ce-972f-4d061f4280da","chargeable_type":"Appointment","charge_guid":"2a116dfce6","chargeable_id":"10980610","client_id":"3633713","transaction_designation":"payment","organization":"Standard","user_email":"asher_test@glossgenius.com","transaction_payment_type":"payment_card_terminal","application_fee":"140","user_id":"55091"},"charges":[],"amount":5400,"amountDetails":{"tip":{"amount":null}},"offlineDetails":null},"updatePaymentIntent":true}```
2. Tap the card on the M2 card reader
3. See error

**Expected behavior**
The collectPaymentMethod should return will result that is either a paymentIntent or error

**Screenshots**

**Stripe Terminal React Native SDK version**
`^0.0.1-beta.18`

**Smartphone (please complete the following information):**

- Device: iPhone 15 Pro
- OS: 17.4.1

**Additional context**

**Comment by nazli-stripe** [comment]
This seems to be a bug with how we are doing mapping for PaymentIntents, fixing in this PR: https://github.com/stripe/stripe-terminal-react-native/pull/698

**Comment by asher5** [comment]
@nazli-stripe is there a timeline to release the fixes?

**Comment by nazli-stripe** [comment]
we are aiming for early June

**Comment by nazli-stripe** [comment]
hey @asher5 we just release `beta.19`. Can you upgrade and let us know if it fixes the issue? Thanks!
