### ISSUE TITLE
Unable to discover BT hardware on android

### ISSUE THREAD

**Issue by jdivock-stripe** [stripe/stripe-terminal-react-native#70]
android:
pixel 5a, android12

Physical BT devices never show up on BT Scan

no error shown, just devices do not display

have my iPhone on the same build open and it correctly is displaying my M2

logcat: https://gist.github.com/jdivock-stripe/96f0aaa5583f218caf5672ef7f1d42ae

**Comment by AlanCasal** [comment]
having the same issue here
