### ISSUE TITLE
Android 14 : Unable to build because of react-native-reanimated

### ISSUE THREAD

**Issue by KillianLarcher** [stripe/stripe-terminal-react-native#702]
**Describe the bug**

When I try to build my app, I always have an error, apparently related to react-native-reanimated.
This bug only appears with 0.0.1-beta.17 and 0.0.1-beta.18. It's working fine with 0.0.1-beta.15 (but with a patch to fix a java version issue).

**Logs**

`> Configure project :react-native-reanimated
Android gradle plugin: 8.1.1
Gradle: 8.3

> Task :app:processDebugMainManifest
/home/killian-larcher/IdeaProjects/onetip-tablet-app/android/app/src/debug/AndroidManifest.xml:6:5-162 Warning:
        application@android:usesCleartextTraffic was tagged at AndroidManifest.xml:6 to replace other declarations but no other declaration present
/home/killian-larcher/IdeaProjects/onetip-tablet-app/android/app/src/debug/AndroidManifest.xml Warning:
        provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:0 to replace other declarations but no other declaration present

> Task :app:checkDebugDuplicateClasses FAILED

> Task :stripe_stripe-terminal-react-native:compileDebugKotlin
w: file:///home/killian-larcher/IdeaProjects/onetip-tablet-app/node_modules/@stripe/stripe-terminal-react-native/android/src/main/java/com/stripeterminalreactnative/Mappers.kt:211:33 Unnecessary safe call on a non-null receiver of type Map<String, String>
w: file:///home/killian-larcher/IdeaProjects/onetip-tablet-app/node_modules/@stripe/stripe-terminal-react-native/android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt:406:46 Unchecked cast: Map<String!, Any!> to Map<String, String>
w: file:///home/killian-larcher/IdeaProjects/onetip-tablet-app/node_modules/@stripe/stripe-terminal-react-native/android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt:537:13 Name shadowed: paymentIntent
w: file:///home/killian-larcher/IdeaProjects/onetip-tablet-app/node_modules/@stripe/stripe-terminal-react-native/android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt:596:17 Name shadowed: paymentIntent
w: file:///home/killian-larcher/IdeaProjects/onetip-tablet-app/node_modules/@stripe/stripe-terminal-react-native/android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt:683:17 Name shadowed: setupIntent
w: file:///home/killian-larcher/IdeaProjects/onetip-tablet-app/node_modules/@stripe/stripe-terminal-react-native/android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt:705:17 Name shadowed: setupIntent
w: file:///home/killian-larcher/IdeaProjects/onetip-tablet-app/node_modules/@stripe/stripe-terminal-react-native/android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt:885:34 Name shadowed: i
w: file:///home/killian-larcher/IdeaProjects/onetip-tablet-app/node_modules/@stripe/stripe-terminal-react-native/android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt:926:21 Parameter 'eventName' is never used
w: file:///home/killian-larcher/IdeaProjects/onetip-tablet-app/node_modules/@stripe/stripe-terminal-react-native/android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt:931:25 Parameter 'count' is never used
w: file:///home/killian-larcher/IdeaProjects/onetip-tablet-app/node_modules/@stripe/stripe-terminal-react-native/android/src/main/java/com/stripeterminalreactnative/ktx/TerminalExtensions.kt:144:5 'when' is exhaustive so 'else' is redundant here
w: file:///home/killian-larcher/IdeaProjects/onetip-tablet-app/node_modules/@stripe/stripe-terminal-react-native/android/src/main/java/com/stripeterminalreactnative/listener/RNReaderReconnectionListener.kt:32:18 This declaration overrides deprecated member but not marked as deprecated itself. This deprecation won't be inherited in future releases. Please add @Deprecated annotation or suppress. See https://youtrack.jetbrains.com/issue/KT-47902 for details

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform jackson-core-2.16.1.jar (com.fasterxml.jackson.core:jackson-core:2.16.1) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /home/killian-larcher/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.16.1/9456bb3cdd0f79f91a5f730a1b1bb041a380c91f/jackson-core-2.16.1.jar.
         > Failed to transform '/home/killian-larcher/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.16.1/9456bb3cdd0f79f91a5f730a1b1bb041a380c91f/jackson-core-2.16.1.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 65. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).
`

**To Reproduce**

Build a react native project with @stripe/stripe-terminal-react-native and react-native-reanimated

**Stripe Terminal React Native SDK version**

- `^0.0.1-beta.17`
- `^0.0.1-beta.18`

**Smartphone:**

- Device: Samsung Tab Active 5
- OS: Android 14

**Comment by nazli-stripe** [comment]
hey @KillianLarcher this is happening due to the update to our Terminal Android SDK. Did you see this thread? https://github.com/stripe/stripe-terminal-react-native/issues/653

**Comment by KillianLarcher** [comment]
I didn't see it, the bug is fixed. Thank you!
