### ISSUE TITLE
Option to use functions directly instead of via hooks.

### ISSUE THREAD

**Issue by ashleyww93** [stripe/stripe-terminal-react-native#714]
**Is your feature request related to a problem? Please describe.**
We have a React Native (expo) application that is used for omnichannel shopping experiences.

We have a payment service so that our core application can always call the same expected functions, and we handle the other payment solutions (Viva, Adyan, etc...) under the hood.

Because of this, we can't use hooks, as our application just calls something like:

```js
PaymentService.Charge({price: 123.54, currency: GBP, id: "01HYZV2Y8P6MQTFFW6C7TP61GW"})
```

The application already knows (after it loads configuration from our backend) which payment provider to use, so this allows us to have the PaymentService owning it's single responsibility to handle payments.

**Describe the solution you'd like**
You already offer a [terminal-js](https://github.com/stripe/terminal-js) option for javascript/typescript users, and we would like to be able to use the functions in the same way.

Instead of forcing us into the provider & hooks, why not just let us handle it ourselves if we so wish?

**Describe alternatives you've considered**
I have considered [terminal-js](https://github.com/stripe/terminal-js), but it is not supported with React Native.

**Additional context**
We have at least one customer waiting to start using Stripe (with a BBPOS Wise ePOS E terminal) with our solution, without support/documentation for not using hooks, we will have to advise that they use another solution.

**Comment by nazli-stripe** [comment]
hey @ashleyww93 we have a similar issue to track this: https://github.com/stripe/stripe-terminal-react-native/issues/614 with one user sharing a potential workaround. Unfortunately we don't have bandwidth to fully look into this right now, but we'll consider it for the future. 

closing this issue and will continue monitoring the other one
