### ISSUE TITLE
Inconsistent requiredAt for availableUpdate

### ISSUE THREAD

**Issue by FabulouSebas** [stripe/stripe-terminal-react-native#718]
**Describe the bug**
The `availableUpdate` object on the `connectedReader` object returned by the hook `useStripeTerminal` is inconsistent between android and iOS. The android's `requiredAt` is 1000 times bigger than it should be.

Actual example received from simulated terminals, but I can confirm the issue is also present with a real stripe m2 terminal.
iOS: `"requiredAt": "1717781856496"`
Android: `"requiredAt": "1717781756363000"`

To fix this, I have to do: `new Date(Platform.OS === 'android' ? requiredAt / 1000 : requiredAt)`

**To Reproduce**
The example-app on your repository has the issue, if you connect to a simulated terminal on iOS vs Android.

**Expected behavior**
I would expect the requiredAt to be the same across both platform.

**Stripe Terminal React Native SDK version**

"@stripe/stripe-react-native": "0.38.0",
"@stripe/stripe-terminal-react-native": "0.0.1-beta.18",

**Smartphone (please complete the following information):**

* Tested on simulator: iPhone SE 3rd generation VS Pixel_4a_API_34
* Tested on real devices: iPhone 12 VS Huawei P20 Pro

**Comment by nazli-stripe** [comment]
This issue has been fixed in `beta.20` release: https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.20
