### ISSUE TITLE
Reset reader to original firmware 

### ISSUE THREAD

**Issue by Satya5614** [stripe/stripe-terminal-react-native#719]
**Describe the bug**
I have a BBPOS WisePad 3, which I want to reset to original firmware which was before updating the reader

I want to debug issues when reader updates itself after connecting for first time, Is there any way I can reset the physical reader to original firmware version. So I can test the upgrading process with the real reader

I tried using simulated reader, but everything works fine. I want to test with the real reader

**Comment by silveur** [comment]
I also need to develop the update process for the Swift views.
Would love to reinitiate the update process to ensure users understand why the reader doesn't connect for a while

**Comment by silveur** [comment]
@Satya5614 actually there seems to be a pin hole on the side to reset the firmware.
It does not seem to reset the firmware nor starting a firmware update on the next connect

**Comment by nazli-stripe** [comment]
It is not possible to change the reader firmware on real devices, and we recommend using the simulated reader to test upgrade flows
