### ISSUE TITLE
Android or iOS Tap to Pay apps cannot detect Amex Titanium contactless cards (metal cards)

### ISSUE THREAD

**Issue by tzecheng** [stripe/stripe-terminal-react-native#720]
**Describe the bug**
We have examples of contactless payment failures on both iPhone and Android when using AMEX Titanium Contactless cards (metal cards).  The device does NOT detect the AMEX Titanium Contactless card. However, the transaction is successful on a physical terminal.

Details are as follows. Could you please assist us in investigating this Stripe Terminal SDK Tap to Pay issue?

Tap to Pay on Android: pi_3PNOtvEcr8OExvfT03brzXED

Physical terminal: DOMESTIC, American Express, non-chip, contactless, No CVM required, CREDIT clear and concise description of what the bug is.

**To Reproduce**
Use an Amex Titanium metal card with either an iOS or Androd Tap to Pay app.

**Expected behavior**
Android or iOS TTP app should be able to detect the metal card and show the payment screen.

**Stripe Terminal React Native SDK version**
- ^0.0.1-beta.18

**Smartphone (please complete the following information):**
- Device: Galaxy S21 5G
- OS: Android 13

**Comment by tzecheng** [comment]
Thanks for the quick response.  We will let our users know and ask them to try it out.

**Comment by rossilazuardi** [comment]
Hi, I’m experiencing a very similar issue on Android Tap to Pay.

In my case, Visa and Mastercard are detected normally, but AMEX consistently fails. The payment flow always ends with a tap error, and the adb logs show repeated presence check failures:

```
nativeNFCTog_doPresenceCheck: tog absent<br>
nativeNFCTog_doPresenceCheck: tog absent
nativeNFCTog_doPresenceCheck: tog already deactivated
```

I have tested this on Sunmi V2s and Sunmi V3H, and the behavior is the same on both devices.

It looks very close to the symptoms described in this thread.

Is there any update, workaround, or additional guidance from the Stripe team regarding this issue?
I want to confirm whether AMEX support on Tap to Pay might be affected by the same underlying problem.

Thanks in advance!
