### ISSUE TITLE
FeatureNotAvailableWithConnectedReader when calling collectPaymentMethod

### ISSUE THREAD

**Issue by 123pappu** [stripe/stripe-terminal-react-native#727]
Hello Team 
Subject : Integration Tap To Pay 

I am getting the following message in the console
{"code": "FeatureNotAvailableWithConnectedReader", "message": "This feature is currently not available for the selected reader."}
immediately after calling
await collectPaymentMethod({paymentIntent: paymentIntentObject});

To Reproduce
Steps to reproduce :
Discover readers ->connect to reader with location-> create paymentIntent using terminalSDK-> call collectPaymentMethod with the paymentIntent

LOG [Stripe terminal]: Connected to the reader return => { availableUpdate:  null, batteryLevel: null,batteryStatus: "unknown", deviceSoftwareVersion: null, deviceType: "appleBuiltIn", id: "tmr_FmUDnwR7QWY0cn", ipAddress: null, isCharging: null, label: "Apple Built-In (…12ae)", location:  {livemode: false, id: 'tml_FmUDnAS4yacSvd', displayName: 'Peculi jar limited', address: {…}}
locationId: "tml_FmUDnAS4yacSvd", locationStatus:  "set", serialNumber: "13a106f4a7384d6f204d4b23176d4bfb3a04a7749a9398535a795058f14712ae", simulated: false, status: "offline"}

LOG [Stripe terminal]: createPaymentIntent return => {amount:30, charges:  [], created: "1718107656000", currency: "gbp",  id: "pi_3PQTUCHlYLnCaamG0HXrG3VW", metadata: {}. offlineDetails: null, paymentMethodId:  null, sdkUuid: "526B11DC-F5E2-41C8-AB2A-0F82AA0CB1E1", status: "requiresPaymentMethod"}

LOG [Stripe terminal]: collectPaymentMethod return => code: "FeatureNotAvailableWithConnectedReader", message: "This feature is currently not available for the selected reader."

Stripe Terminal React Native SDK version
"_id": "@stripe/stripe-terminal-react-native@0.0.1-beta.17",
using with CLI

Smartphone (please complete the following information):

Device: iPhone 11
IOS: 17.5.1

Kindly help to resolve this issue
Thanks in advance

**Comment by nazli-stripe** [comment]
Hm I'm not seeing anything in our logs for device `13a106f4a7384d6f204d4b23176d4bfb3a04a7749a9398535a795058f14712ae` and that error code. Is that the serialNumber of the device you ran into issues with?

**Comment by 123pappu** [comment]
Hello team ,

Here is the readers serialNumber  screenshot
[image: Screenshot 2024-06-12 at 10.30.21 AM.png]


*Thanks,*
*Pappu Chauhan*
Tech Team Lead
Pixelperinches Technologies Pvt Ltd.
http://www.pixelperinches.com/

**Comment by nazli-stripe** [comment]
@123pappu can you attach the screenshot directly on Github? It's not showing up right now

**Comment by 123pappu** [comment]
@nazli-stripe, Here is the screenshot 
![Screenshot 2024-06-12 at 10 31 12 AM](https://github.com/stripe/stripe-terminal-react-native/assets/95117974/037f5e12-ed64-4f2f-bc47-3235ca40eed0)

**Comment by 123pappu** [comment]
Hi @nazli-stripe , Any update on above issue ?

**Comment by 123pappu** [comment]
Hi @nazli-stripe , Kindly revert to the issue stated above, this is delaying the app launch for the user testing.

**Comment by nazli-stripe** [comment]
hey @123pappu thanks for your patience. From our logs it looks like on collectPaymentMethod call you are setting `enableCustomerCancelation` to true. There is a known bug on iOS SDK when that field is passed for TTP: https://github.com/stripe/stripe-terminal-ios/issues/301 This will be fixed in iOS 3.7.0 for native users and beta.20 for RN users.

For now we recommend setting that field to false. Can you let me know if that solves the issue?

**Comment by 123pappu** [comment]
Hi Nazil

Thank You for the response

 I have changed enableCustomerCancelation to false but now I have got this
issue

 {"code": "Unknown", "message": "A required parameter was invalid or
missing. Collecting a PaymentMethod for a PaymentIntent `on_behalf_of` a
Connected Account requires providing that Connected Account's ID in
`SCPLocalMobileConnectionConfiguration`"}


*Thanks,*
*Pappu Chauhan*
Tech Team Lead
Pixelperinches Technologies Pvt Ltd.
http://www.pixelperinches.com/

**Comment by 123pappu** [comment]
Hi Nazil

I have changed CustomerCancellation from true to false and removed the
'on_behalf_of' from the createPaymentIntent and then tap to pay is working
for me.

Not sure if this action will have any impact on existing app


*Thanks,*
*Pappu Chauhan*
Tech Team Lead
Pixelperinches Technologies Pvt Ltd.
http://www.pixelperinches.com/

**Comment by nazli-stripe** [comment]
This issue has been fixed in `beta.20` release with the 3.7.0 native SDK upgrade: https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.20
