### ISSUE TITLE
A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction

### ISSUE THREAD

**Issue by Kadir-flipcause** [stripe/stripe-terminal-react-native#739]
Getting the solution from : https://github.com/stripe/stripe-terminal-react-native/issues/653
to solve the error Failed to transform jackson-core-2.16.1.jar according to [https://github.com/stripe/stripe-terminal-react-native/issues/653#issuecomment-2030956397](url)

changed android.enableJetifier = true from android.enableJetifier = false
and after this change getting this error

**Screenshots**
![image](https://github.com/stripe/stripe-terminal-react-native/assets/165893347/b436fa6d-ff22-4954-bd43-adccdc1c43f7)

**React Native SDK version**
        buildToolsVersion = "34.0.0"
        minSdkVersion = 26
        compileSdkVersion = 34
        targetSdkVersion = 31
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.22"
        
        "@stripe/stripe-terminal-react-native": "^0.0.1-beta.19",
        "react-native": "0.74.0",

- Device: android

**Comment by Kadir-flipcause** [comment]
Hello @nazli-stripe can you please help on this facing this from last 7 days please check and respond as soon as possible

**Comment by Kadir-flipcause** [comment]
Hi any update on this

**Comment by ebarrenechea-stripe** [comment]
@Kadir-flipcause you might need to add a `packaging` block to your build.gradle.kts file to address the duplicates.

```
packaging {
        resources {
            pickFirsts += "org/bouncycastle/x509/CertPathReviewerMessages_de.properties"
        }
    }
```

**Comment by nazli-stripe** [comment]
@Kadir-flipcause is this issue resolved?

**Comment by nazli-stripe** [comment]
@Kadir-flipcause what version are you on?

**Comment by Kadir-flipcause** [comment]
> @Kadir-flipcause what version are you on?

currently I'm using "@stripe/stripe-terminal-react-native": "^0.0.1-beta.19"

**Comment by nazli-stripe** [comment]
@Kadir-flipcause can you upgrade to beta.21 and report back? We released a fix for how we handle connection tokens that cause an issue for connections on first run of the app, that sounds similar to what you are describing

**Comment by Kadir-flipcause** [comment]
> @Kadir-flipcause can you upgrade to beta.21 and report back? We released a fix for how we handle connection tokens that cause an issue for connections on first run of the app, that sounds similar to what you are describing

hi @nazli-stripe thanks for your response as you mentioned now its working at initial installation thanks for your help
