### ISSUE TITLE
collectInputs return type differs on iOS from those documented in the API docs

### ISSUE THREAD

**Issue by asher5** [stripe/stripe-terminal-react-native#743]
**Describe the bug**
When trying the [workaround for iOS collectInputs bug](https://github.com/stripe/stripe-terminal-react-native/issues/742) to pass a dummy collectInputs parameter we had other issues, it look like SDK doesn't return the documented object types in the result. It returns an object that is as follows

When FormType.SELECTION used
```
{
  "selectionResult": {
    "skipped": false,
    "selection": "Custom Amount",
    "toggles": []
  }
}
```
When FormType.NUMERIC used
```
{
  "numericResult": {
    "skipped": false,
    "toggles": [],
    "numericString": "20"
  }
}
```
which is different from what the SDK types defined are i.e.
```
export interface ICollectInputsResults {
    collectInputResults?: ICollectInputsResult[];
    error: StripeError;
}
export interface ICollectInputsResult {
    skipped: boolean;
    email?: string;
    numericString?: string;
    phone?: string;
    selection?: string;
    signatureSvg?: string;
    text?: string;
    toggles: ToggleResult[];
}
```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Stripe Terminal React Native SDK version**

- (e.g., `^0.0.1-beta.19`)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nazli-stripe** [comment]
hey @asher5 thanks a lot for flagging this issue. We are working on fixing this in the new release to align iOS and Android types, and it is scheduled for end of July.

**Comment by nazli-stripe** [comment]
We unified the types in the beta.23 release
