### ISSUE TITLE
The PaymentMethod provided (card_present) is not allowed for this PaymentIntent

### ISSUE THREAD

**Issue by 123pappu** [stripe/stripe-terminal-react-native#745]
Hello Team
Subject : Integration Tap To Pay

I am getting the following message in the console
{"code": "StripeAPIError", "message": "The PaymentMethod provided (card_present) is not allowed for this PaymentIntent. Please attach a PaymentMethod of one of the following types: card. Alternatively, update the allowed payment_method_types for this PaymentIntent to include "card_present""}

immediately after calling
await confirmPaymentIntent({paymentIntent});

To Reproduce
Steps to reproduce :
Discover readers ->connect to reader with location-> create paymentIntent using terminalSDK-> call collectPaymentMethod with the paymentIntent -> create Payment Intent -> collect Payment Method -> confirm Payment Intent

LOG [Stripe terminal]: create Payment Intent=> { amount: 358, charges: [],created: "1719838582000", currency:  "gbp", id: "pi_3PXjmMHlYLnCaamG1DUJr8hW", metadata: {}, offlineDetails: null, paymentMethodId: null, sdkUuid: "75F07D2A-417D-4F42-A3D9-1AEDBE4E9056",status:  "requiresPaymentMethod"}

Create Payment Intent Payload :   
          const { error, paymentIntent } = await createPaymentIntent({
                'amount': parseInt(amount.toString().replace('.', '')),
                'currency': "GBP",
                'payment_method_types': ['card'],
            });

LOG [Stripe terminal]: collect Payment Method return => { amount: 358, charges: [],created: "1719838582000", currency:  "gbp", id: "pi_3PXjmMHlYLnCaamG1DUJr8hW", metadata: {}, offlineDetails: null, paymentMethodId: null, sdkUuid: "75F07D2A-417D-4F42-A3D9-1AEDBE4E9056",status:  "requiresConfirmation"}

LOG [Stripe terminal]: confirmPaymentIntent return => code: "StripeAPIError", message: "The PaymentMethod provided (card_present) is not allowed for this PaymentIntent. Please attach a PaymentMethod of one of the following types: card. Alternatively, update the allowed payment_method_types for this PaymentIntent to include "card_present""

Stripe Terminal React Native SDK version
"_id": "@stripe/stripe-terminal-react-native@0.0.1-beta.17",
using with CLI

Smartphone (please complete the following information):

Device: iPhone 11
IOS: 17.5.1

Kindly help to resolve this issue
Thanks in advance

**Comment by nazli-stripe** [comment]
hey @123pappu, when you create the PaymentIntent did you pass `card_present` in the `paymentMethodTypes` field? In the earlier versions of the SDK not passing this field creates PaymentIntents only for `card` payment method. We have fixed this starting with beta.19 release: https://github.com/stripe/stripe-terminal-react-native/pull/724

**Comment by 123pappu** [comment]
Yes, it worked!
