### ISSUE TITLE
confirmPaymentIntent throwing random error in production but no server-side logs

### ISSUE THREAD

**Issue by inzqne** [stripe/stripe-terminal-react-native#746]
**Describe the bug**
The user goes through the tap to pay flow and taps a card on iPhone 14 Pro and the SDK attaches the card to the payment intent (seen in the screenshot below) with the collectPaymentMethod function with iPhone Tap to Pay but fails on the confirmPaymentIntent method with a non-decline error but no server logs. Not sure why this happens and we currently have no logging for this in production so any guidance is appreciated 😄. I also attached the Stripe API logs below, I noticed that there were no calls to the /confirm endpoint for this payment intent, only the creation endpoint which is weird so no logs there either. 

Here is the device UUID if it helps:
caab148b1603981a9e4699adb523753e8c4748c2be5a2a48854dacf94ff9d319

If it would be helpful to have more info such as the Payment Intent ID please let me know and I can send it privately.

**Expected behavior**
For the payment intent to confirm and charge the customer's card that is attached to the payment intent

**Screenshots**
![image](https://github.com/stripe/stripe-terminal-react-native/assets/22850872/24808b73-c64a-48ab-9e40-c0d5dca7edbb)
![image](https://github.com/stripe/stripe-terminal-react-native/assets/22850872/997ef517-2579-4d4f-b6a4-1b1734c303fc)

**Stripe Terminal React Native SDK version**
^0.0.1-beta.16

**Smartphone:**
- Device: iPhone 14 Pro
- OS: iOS 17.5.1
- UUID: caab148b1603981a9e4699adb523753e8c4748c2be5a2a48854dacf94ff9d319

**Comment by nazli-stripe** [comment]
@inzqne can you let us know the failing PaymentIntent ID as well?

**Comment by inzqne** [comment]
> @inzqne can you let us know the failing PaymentIntent ID as well?

It ended up being an issue with location permissions, I was not aware that if you had location permissions off you can still go through the whole Tap to Pay flow and tap a card without location perms.
