### ISSUE TITLE
[feature request] Android equivalent for "appleBuiltIn" deviceType

### ISSUE THREAD

**Issue by nabilfreeman** [stripe/stripe-terminal-react-native#750]
**Is your feature request related to a problem? Please describe.**
When calling `supportsReadersOfType()`, a `deviceType` value must be passed in.

When searching for Tap to Pay reader on iOS, `appleBuiltIn` can be specified as the device type.

However on Android, it appears that there is no equivalent. 

**Describe the solution you'd like**
A key such as `androidBuiltIn`, or clear documentation how to use the `supportsReadersOfType` method on Android

**Describe alternatives you've considered**
Tried looking for the source code of Android Terminal SDK but it appears to be proprietary

**Additional context**
None

**Comment by iatanasov37** [comment]
Hey there. I hope this helps, but I found out that the enum value is "cotsDevice", which appears to be assigned to Android devices.

**Comment by nazli-stripe** [comment]
@iatanasov37 is correct, `cotsDevice` is meant for Android TTP devices

**Comment by nabilfreeman** [comment]
We've just done the upgrade to Beta 24, and we have assumed that the new `tapToPay` enum value present on both iOS and Android is the one to use going forward. It seems to work in our testing.
