### ISSUE TITLE
[deadline] Google Play Store requires targetSdkVersion to be 34 or higher by August 31, 2024

### ISSUE THREAD

**Issue by nabilfreeman** [stripe/stripe-terminal-react-native#753]
**Describe the bug**
Update your target API level by August 31, 2024 to release updates to your app

We've detected that your app is targeting an old version of Android. To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements.

From August 31, 2024, if your target API level is not within 1 year of the latest Android release, you won't be able to update your app.

**To Reproduce**

1. Follow the instructions in the readme and set targetSdkVersion to 33
2. Submit an application to the Google Play Store

**Expected behavior**
This behaviour is expected, due to the current issues with SDK 34 and Stripe Terminal:

https://github.com/stripe/stripe-terminal-react-native?tab=readme-ov-file#android

https://github.com/stripe/stripe-terminal-android/issues/387

Questions:

- Are the Stripe team aware of the upcoming deadline?
- Have the compatibility issues with SDK version 34 been resolved yet, or are on track to resolve in time for the deadline?

**Screenshots**

<img width="953" alt="Screenshot 2024-07-08 at 11 15 15" src="https://github.com/stripe/stripe-terminal-react-native/assets/2470659/e557069c-bece-4ce4-a139-f35c0a20fbcd">

**Stripe Terminal React Native SDK version**

- `^0.0.1-beta.19`

**Additional context**

I understand the library is still in beta, and we really do appreciate you having this out there for us to use in the meantime!

**Comment by nazli-stripe** [comment]
that issue has been fixed since v0.0.1-beta.15, looks like we forgot to update the Readme. Can you set the target to 34 on the latest version?

**Comment by nabilfreeman** [comment]
Thanks for the update @nazli-stripe, I'll give it a try. Are the custom build settings generally still required? Assume yes, because we still need to force the minimum SDK version to 26?

**Comment by shreyaspathak11** [comment]
How to solve this if my app is build with react native expo

**Comment by Ryanhuang1124** [comment]
Is it ok that I only update target sdk but no changes on compileSdk(because newer compileSdk version makes app crush) ?

**Comment by patmisch** [comment]
I'm running version 0.0.1-beta.12, which does not seem to work (cannot discover readers) if targetSdkVersion is set to 34. I upgraded to version 0.0.1-beta.15, but this seems to depend on a newer version of react native, that I do not have the time to upgrade to, due to how many dependencies I have that it ends up breaking.

Am I completely out of luck here and need to upgrade react native? Or is there a work around that will allow me to get a small update to my app published to the Play Store?
