### ISSUE TITLE
react native stripe terminal not initialize in some pos-mashine like sunmi P2-SE or Urovo i9100

### ISSUE THREAD

**Issue by tahahaz1374** [stripe/stripe-terminal-react-native#756]
Hi there , 
we are developing  tap to pay on android device it's works fine  like Samsung  or xiaomi 
but not working on pos-mashine like sunmi P2-SE or Urovo i9100
this devices has requirment as stripe documentation.

**Comment by chr-stripe** [comment]
Hi @tahahaz1374, thank you for the report. I don't believe the SUNMI P2-SE or the Urovo i9100 are Google Play supported devices, and thus wouldn't fit the criteria listed in our [Supported Devices](https://docs.stripe.com/terminal/payments/setup-reader/tap-to-pay?platform=android#supported-devices) documentation for Tap to Pay. These manufacturers do have other devices that should be compatible though, for instance, the SUNMI V2s is a popular model that is compatible with Tap to Pay.

**Comment by SajithSadan** [comment]
@chr-stripe  Could you please update the [Supported Devices](https://docs.stripe.com/terminal/payments/setup-reader/tap-to-pay?platform=android#supported-devices) list with supported POS devices? This update would greatly assist developers working in the POS domain/niche.

**Comment by chr-stripe** [comment]
Is there a device that you wish to see added to the list? Or a device on the list that you are having difficulty using with Tap to Pay on Android?

**Comment by SajithSadan** [comment]
I have a Sunmi V2s, and I tried to implement tap to pay using react native. But I was getting GMS certification error. Please check [https://github.com/stripe/stripe-terminal-react-native/issues/860](https://github.com/stripe/stripe-terminal-react-native/issues/860)

**Comment by chr-stripe** [comment]
Hi @SajithSadan, we've reorganized and updated the list of supported devices to be more comprehensive! It also specifically calls out the scenario you are describing to ensure that consideration is taken for some manufacturer device models:

> Some manufacturers produce both GMS and non-GMS certified devices. If you’re using a non-GMS certified device you’ll receive an error when attempting to connect the device saying `ATTESTATION_FAILURE: Device is not Google Mobile Services (GMS) certified`. If this happens, contact the manufacturer to resolve the issue.
