### ISSUE TITLE
The Stripe Terminal ConnectionToken has already been redeemed

### ISSUE THREAD

**Issue by rlfrahm** [stripe/stripe-terminal-react-native#776]
**Describe the bug**

Using the example-app in internet discovery mode, when you disconnect and then reconnect to a reader using the `example-app` you receive the following error:

> connectInternetReader error: {"code": "PAYMENT_ERROR.DECLINED_BY_STRIPE_API", "message": "The Stripe Terminal ConnectionToken has already been redeemed. Please generate a new one using v1/terminal/connection_tokens."}

It seems like the same connection token is continually recycled.

I am running `stripe-terminal-react-native/example-app` and [example-terminal-backend](https://github.com/stripe/example-terminal-backend).

The reason I'm trying to test the `example-app` is because my own app is experiencing these same behaviors, whether from the emulator or an S700 Devkit.

**To Reproduce**

1. Run both the `example-app` and the `example-terminal-backend` (ruby)
2. Point the `example-app` to your ruby api
3. Change discovery method to "Internet"
4. Tap "Discover readers"
5. Select the "WisePOSE" reader
6. Disconnect or restart the app
7. Try to connect to the same reader again
8. (This simulates what happens with an S700 device)

**Expected behavior**

A new connection token should be refetched.

**Screenshots**

![Screenshot_1722600979](https://github.com/user-attachments/assets/20b02967-5466-4f39-a04f-fa5e0b152d28)

**Stripe Terminal React Native SDK version**

- `^0.0.1-beta.20`

**Smartphone (please complete the following information):**

- Device: Android emulator
- OS: VanillaIceCream (May 5, 2024) 
- Browser React Native
- Version N/A

**Additional context**

Logs:

>  LOG  pst_test_YWNjdF8xRGhJTGVDdGJ4NXlES0tlLEJWQWI0alB6QWMxR1hGUTh4Z0s0dUZkWWVNRWE4eVk_003Qok4tIc
 LOG  [Stripe terminal]: didChangeOfflineStatus {"reader": undefined, "sdk": {"networkStatus": "unknown", "offlinePaymentAmountsByCurrency": {}, "offlinePaymentsCount": 0}}
 LOG  {"reader": undefined, "sdk": {"networkStatus": "unknown", "offlinePaymentAmountsByCurrency": {}, "offlinePaymentsCount": 0}}
 LOG  StripeTerminal has been initialized properly
 LOG  pst_test_YWNjdF8xRGhJTGVDdGJ4NXlES0tlLEJWQWI0alB6QWMxR1hGUTh4Z0s0dUZkWWVNRWE4eVk_003Qok4tIc
 LOG  [Stripe terminal]: didChangeOfflineStatus {"reader": undefined, "sdk": {"networkStatus": "online", "offlinePaymentAmountsByCurrency": {}, "offlinePaymentsCount": 0}}
 LOG  {"reader": undefined, "sdk": {"networkStatus": "online", "offlinePaymentAmountsByCurrency": {}, "offlinePaymentsCount": 0}}
 LOG  [Stripe terminal]: didUpdateDiscoveredReaders [{"availableUpdate": null, "baseUrl": "", "batteryLevel": null, "bootloaderVersion": null, "configVersion": null, "deviceSoftwareVersion": "3.0.1.16", "deviceType": "verifoneP400", "emvKeyProfileId": null, "firmwareVersion": null, "hardwareVersion": "unknown", "id": "tmr_DsNvhA6mLpMH48", "ipAddress": "192.168.2.12", "label": "created-lamb-elephant", "location": {"address": null, "displayName": "Simulated Location", "id": "tml_simulated", "livemode": false}, "locationId": "tml_simulated", "locationStatus": "unknown", "macKeyProfileId": null, "pinKeyProfileId": null, "pinKeysetId": null, "serialNumber": "123-456-789", "settingsVersion": null, "simulated": true, "status": "online", "trackKeyProfileId": null}, {"availableUpdate": null, "baseUrl": "", "batteryLevel": null, "bootloaderVersion": null, "configVersion": null, "deviceSoftwareVersion": "2.12.0.8", "deviceType": "wisePosE", "emvKeyProfileId": null, "firmwareVersion": null, "hardwareVersion": "unknown", "id": "tmr_DsNvhA6mLpMH48", "ipAddress": "192.168.2.12", "label": "My WISEPOS_E", "location": {"address": null, "displayName": "Simulated Location", "id": "tml_simulated", "livemode": false}, "locationId": "tml_simulated", "locationStatus": "unknown", "macKeyProfileId": null, "pinKeyProfileId": null, "pinKeysetId": null, "serialNumber": "WSC51SIMULATOR", "settingsVersion": null, "simulated": true, "status": "online", "trackKeyProfileId": null}]
 LOG  [Stripe terminal]: didFinishDiscoveringReaders {}
 LOG  onFinishDiscoveringReaders success
 LOG  [Stripe terminal]: didChangeConnectionStatus connecting
 LOG  pst_test_YWNjdF8xRGhJTGVDdGJ4NXlES0tlLEJWQWI0alB6QWMxR1hGUTh4Z0s0dUZkWWVNRWE4eVk_003Qok4tIc
 LOG  [Stripe terminal]: didChangeConnectionStatus connected
 LOG  [Stripe terminal]: didChangePaymentStatus ready
 LOG  Reader connected successfully {"availableUpdate": null, "baseUrl": "", "batteryLevel": null, "bootloaderVersion": null, "configVersion": null, "deviceSoftwareVersion": "2.12.0.8", "deviceType": "wisePosE", "emvKeyProfileId": null, "firmwareVersion": null, "hardwareVersion": "unknown", "id": "tmr_DsNvhA6mLpMH48", "ipAddress": "192.168.2.12", "label": "My WISEPOS_E", "location": {"address": null, "displayName": null, "id": "tml_EBpwFaSnJv2eMl", "livemode": false}, "locationId": "tml_EBpwFaSnJv2eMl", "locationStatus": "set", "macKeyProfileId": null, "pinKeyProfileId": null, "pinKeysetId": null, "serialNumber": "WSC51SIMULATOR", "settingsVersion": null, "simulated": true, "status": "online", "trackKeyProfileId": null}
 LOG  [Stripe terminal]: didChangeConnectionStatus notConnected
 LOG  [Stripe terminal]: didChangePaymentStatus notReady
 LOG  [Stripe terminal]: didUpdateDiscoveredReaders [{"availableUpdate": null, "baseUrl": "", "batteryLevel": null, "bootloaderVersion": null, "configVersion": null, "deviceSoftwareVersion": "3.0.1.16", "deviceType": "verifoneP400", "emvKeyProfileId": null, "firmwareVersion": null, "hardwareVersion": "unknown", "id": "tmr_DsNvhA6mLpMH48", "ipAddress": "192.168.2.12", "label": "created-lamb-elephant", "location": {"address": null, "displayName": "Simulated Location", "id": "tml_simulated", "livemode": false}, "locationId": "tml_simulated", "locationStatus": "unknown", "macKeyProfileId": null, "pinKeyProfileId": null, "pinKeysetId": null, "serialNumber": "123-456-789", "settingsVersion": null, "simulated": true, "status": "online", "trackKeyProfileId": null}, {"availableUpdate": null, "baseUrl": "", "batteryLevel": null, "bootloaderVersion": null, "configVersion": null, "deviceSoftwareVersion": "2.12.0.8", "deviceType": "wisePosE", "emvKeyProfileId": null, "firmwareVersion": null, "hardwareVersion": "unknown", "id": "tmr_DsNvhA6mLpMH48", "ipAddress": "192.168.2.12", "label": "My WISEPOS_E", "location": {"address": null, "displayName": "Simulated Location", "id": "tml_simulated", "livemode": false}, "locationId": "tml_simulated", "locationStatus": "unknown", "macKeyProfileId": null, "pinKeyProfileId": null, "pinKeysetId": null, "serialNumber": "WSC51SIMULATOR", "settingsVersion": null, "simulated": true, "status": "online", "trackKeyProfileId": null}]
 LOG  [Stripe terminal]: didFinishDiscoveringReaders {}
 LOG  onFinishDiscoveringReaders success
 LOG  [Stripe terminal]: didChangeConnectionStatus connecting
 LOG  pst_test_YWNjdF8xRGhJTGVDdGJ4NXlES0tlLEJWQWI0alB6QWMxR1hGUTh4Z0s0dUZkWWVNRWE4eVk_003Qok4tIc
 LOG  [Stripe terminal]: didChangeConnectionStatus notConnected
 LOG  connectInternetReader error: {"code": "PAYMENT_ERROR.DECLINED_BY_STRIPE_API", "message": "The Stripe Terminal ConnectionToken has already been redeemed. Please generate a new one using v1/terminal/connection_tokens."}

**Comment by nazli-stripe** [comment]
In the logs provided the connection token is always the same: `pst_test_YWNjdF8xRGhJTGVDdGJ4NXlES0tlLEJWQWI0alB6QWMxR1hGUTh4Z0s0dUZkWWVNRWE4eVk_003Qok4tIc`
The token provider should return a new token every time it's called, otherwise the API will return this error

Make sure your backend is not caching the token and generating a new one every time your tokenProvider function is called

**Comment by rlfrahm** [comment]
The backend was indeed caching the token. Is it a bug that the library fetches multiple new connection tokens in one render cycle?

**Comment by rlfrahm** [comment]
That makes sense.
