### ISSUE TITLE
ERROR: You must provide paymentIntent that was returned from either createPaymentIntent or retrievePaymentIntent.

### ISSUE THREAD

**Issue by a-eid** [stripe/stripe-terminal-react-native#786]
**Describe the bug**
We're getting this error: `You must provide paymentIntent that was returned from either createPaymentIntent or retrievePaymentIntent.`, from the method collectPaymentMethod, even thou the passed `paymentIntent` is returned from the `retrievePaymentIntent` method call.

**To Reproduce**
```tsx
// 1- collection client secret.
const clientSecret = await api.post("endpoing", { amount });
// 2- retrievePaymentIntent from stripe 
const { paymentIntent, error } = retrievePaymentIntent(clientSecret);
// 3- collect payment method 
const { error: collectPaymentMethodError } = await collectPaymentMethod({
   paymentIntent,
   skipTipping: true,
});

// ERROR: `You must provide paymentIntent that was returned from either createPaymentIntent or retrievePaymentIntent.`

``` 

**Expected behavior**
for collectPaymentMethod to accept the paymentIntent returned from `retrievePaymentIntent`

**Stripe Terminal React Native SDK version**

- `^0.0.1-beta.20`

- Device: Iphone 15 Pro Max
- OS: IOS

**Comment by danmofo** [comment]
> any idea what this issue be, judging by the lack of comments I assume this is an issue on our part. any idea where could it be ?

Maybe because you are missing the `await` keyword on this line?

```ts
const { paymentIntent, error } = retrievePaymentIntent(clientSecret);
```

vs 

```ts
const { paymentIntent, error } = await retrievePaymentIntent(clientSecret);
```

**Comment by nabilfreeman** [comment]
We are experiencing this on beta 20 which I just upgraded to. Downgrading to beta 19 makes this error go away

**Comment by nazli-stripe** [comment]
@a-eid are you still running into this issue?

**Comment by a-eid** [comment]
@nazli-stripe no I am no longer able to reproduce this issue.
