### ISSUE TITLE
Issue connecting to reader

### ISSUE THREAD

**Issue by thelight413** [stripe/stripe-terminal-react-native#789]
**Describe the bug**
On a first install of the app(example-app), the app doesn't connect to the reader. It just errors out eventually with "Timed out waiting for connection token. But it does work if I reopen the app.
**To Reproduce**

1.  run example-app
2. accept the permissions
3. wait for the sdk to initialize 
4. click on discover readers
5. pick a reader
6. Wait till the error pops up.

**Expected behavior**
The reader should connect. It seems like the sdk/app doesn't attempt at getting a connection token at all so it can't connect to the reader.

**Screenshots**

**Stripe Terminal React Native SDK version**

- ^0.0.1-beta.20` 
- this issue does not happen on ^0.0.1-beta.19`

**Smartphone (please complete the following information):**

- Device: Pixel 6a or a Android Tablet
- OS: Android 
- Version 13/14

**Additional context**

**Comment by danmofo** [comment]
I'm experiencing the same issue. Reader failing to connect after initially installing the app, then working after re-opening. Downgrading to `0.0.1-beta.19` fixes the issue, and it seems [they are aware of it](https://github.com/stripe/stripe-terminal-react-native/pull/791)

**Comment by tzecheng** [comment]
Hi,

When we downgraded to `0.0.1-beta.19` , we saw a similar problem (I don't know whether it is related or not).

1. Build app
2. Fresh install of app (if app exists, delete it first)
3. Go to Tap to Pay button
4. Android - it shows a spinner at the Tap to Pay button; need to terminate app to use
5. iOS - similar, but it returns to the Tap to Pay button after a few minutes, after which it can be used

We are reluctant to release this version as new users will think the app is not working.

Any ideas?

**Comment by nazli-stripe** [comment]
beta.21 was just released and should address this issue. Can you give it a try and let us know?

**Comment by damianoserpetta** [comment]
I upgraded from `0.0.1-beta.20` to `0.0.1-beta.21` but have the same issue with in Android 14. However, after the first install, it works as expected. Anyone has some ideas?

**Comment by drobdymo** [comment]
I updated to `0.0.1-beta.21` and tested on iOS 18 and Android 11 and everything works as expected.

**Comment by maestrodrew** [comment]
I updated to 0.0.1-beta.21 and tested on iOS 18 and Android 11 and everything works as expected.

**Comment by nazli-stripe** [comment]
@tzecheng are you still running into issues on the latest release?

**Comment by tzecheng** [comment]
> @tzecheng are you still running into issues on the latest release?

Hi @nazli-stripe , will be testing in the next few days.

**Comment by tzecheng** [comment]
> > @tzecheng are you still running into issues on the latest release?
> 
> Hi @nazli-stripe , will be testing in the next few days.

Hi @nazli-stripe ,
Have upgraded to 0.0.1-beta.22.  Tested on iOS 17.6.1 and Android 12.  The problem reported earlier on Android spinner and iOS delay is no longer there.
