### ISSUE TITLE
Unable to Test Simulated Terminal SDK on Android Simulator - API level 33 - Getting Time out error

### ISSUE THREAD

**Issue by dharmeshgigs** [stripe/stripe-terminal-react-native#793]
**Describe the bug**
Testing Stripe Terminal SDK payment through android simulator with simulated features. Getting discovery readers with Internet method but after click on device getting time out error. 

**To Reproduce**
1) Run the example-app run from the demo project
2) Enable the Simulated radio button
3) Select discovery mode internet
4) Click on Discover Readers
5) Get 3 records in Near by device section
6) Click on any one device
7) Showing connecting status for a while
8) Time out error and waiting for connection token

**Expected behavior**
after 7th step it should connect to device reader and allow me to payment

**Screenshots**
(https://drive.google.com/file/d/1kSJojSqsRsbsfovMujTA9hCL4CG0Aif4/view?usp=sharing)
**Stripe Terminal React Native SDK version**
- 0.0.1-beta.20

**Smartphone (please complete the following information):**

- Device: Android Simulator - Pixel 6 Pro API 33
- OS: Android
- Browser - NA

**Comment by nazli-stripe** [comment]
Beta.20 has a bug with how it handles connection tokens. Can you try upgrading to beta.21 and try again?
