### ISSUE TITLE
App Hang SCPLogForwardingController

### ISSUE THREAD

**Issue by jacywang** [stripe/stripe-terminal-react-native#799]
**Describe the bug**
We started to see the crashes due to the `SCPLogForwardingController` in our react native app. 

I found that this crash issue was resolved in the [stripe-terminal-ios 3.8.3](https://github.com/stripe/stripe-terminal-ios/releases). See the thread here, https://github.com/stripe/stripe-terminal-ios/issues/317. 

I'm wondering when the fix will be brought into [stripe-terminal-react-native](https://github.com/stripe/stripe-terminal-react-native).

**Comment by tim-lin-bbpos** [comment]
Thanks for reaching out, yes, we'll definitely align our SDK to latest version.
We'll soon get back to you when it's released.

**Comment by nazli-stripe** [comment]
hey @jacywang we just released beta.21 with the iOS 3.8.3 upgrade. This issue should be fixed now
