### ISSUE TITLE
connectInternetReader throws certificate error on IOS in dev build

### ISSUE THREAD

**Issue by inzqne** [stripe/stripe-terminal-react-native#810]
**Describe the bug**
When attempting to connect to the Stripe S700 reader through connectInternetReader it throws this error:
{"code": "Unknown", "message": "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “192.168. (redacted local IP)” which could put your confidential information at risk."}

**To Reproduce**

- Attempt to use connectInternetReader in an IOS dev build to an internet-enabled reader

**Expected behavior**
It connects successfully

**Stripe Terminal React Native SDK version**

`^0.0.1-beta.16`
with an Expo Dev Build

**Smartphone:**

- Device: iPhone 13 Pro
- OS: iOS 17.6.1

**Comment by mindy-stripe** [comment]
Hi @inzqne, thanks for your report. This message sounds like it could be a local networking issue, are you able to reproduce when connected to a different network (eg. different Wifi, mobile hotspot)?

You can reference this guide for troubleshooting reader connection issues: https://support.stripe.com/questions/the-stripe-terminal-javascript-sdk-is-encountering-dns-errors-when-connecting-to-an-internet-reader 

If this is still reproducible, can you provide some more information about your setup? Reader serial numbers, timestamps of when this issue occurred would be helpful. Thanks!

**Comment by inzqne** [comment]
> Hi @inzqne, thanks for your report. This message sounds like it could be a local networking issue, are you able to reproduce when connected to a different network (eg. different Wifi, mobile hotspot)?
> 
> You can reference this guide for troubleshooting reader connection issues: https://support.stripe.com/questions/the-stripe-terminal-javascript-sdk-is-encountering-dns-errors-when-connecting-to-an-internet-reader
> 
> If this is still reproducible, can you provide some more information about your setup? Reader serial numbers, timestamps of when this issue occurred would be helpful. Thanks!

Hi @mindy-stripe, I was able to reproduce the same issue on mobile hotspot. It seems to be some security-level issue but not really sure what is causing it.

Serial Number: STR70Z1C411006425
Timestamp: 6:52 PM PST

**Comment by JulleR** [comment]
The cause of our problem was `expo-dev-client`. I removed it and iOS debug build could connect to the terminal just fine. This comment helped to figure that out https://github.com/expo/expo/issues/24096#issuecomment-2022538762
