### ISSUE TITLE
Accessibility options screen language

### ISSUE THREAD

**Issue by Sarrahadjayache2** [stripe/stripe-terminal-react-native#836]
**Describe the bug**
Is there a way to change the default language in english of the Accessibility options screen?

**To Reproduce**

1. Enter an amount that displays the pin screen such as 20,25
2. Click on Accessibility options
3. The content text is displayed in english

**Expected behavior**
Change default language to another one

**Comment by nazli-stripe** [comment]
Is this for the `setReaderSettings` method?

**Comment by dmatthews-stripe** [comment]
Hi @Sarrahadjayache2 could you please provide a screenshot or a video of what you are seeing?
