### ISSUE TITLE
Query: stripe-terminal-android/ios 4.0.0 builds for stripe-terminal-react-native

### ISSUE THREAD

**Issue by tzecheng** [stripe/stripe-terminal-react-native#843]
Hi,

Noticed that stripe-terminal-android/ios 4.0.0 have just been released and have breaking changes related to reader connection and discovery.

When will these versions be rolled into the react native version?

Thanks.

**Comment by nazli-stripe** [comment]
hey @tzecheng we will support v4 on React Native in early 2025.

**Comment by tzecheng** [comment]
OK, thanks for the update.

**Comment by nazli-stripe** [comment]
We will support v4

**Comment by chr-stripe** [comment]
Hi @sangeeta-myob, all 3.X versions of the Android Stripe Terminal SDK are already use Google Play Integrity, SafetyNet was only being used in those versions only as a fallback during our migration to full reliance on Play Integrity. Errors coming from existing SDKs that attempt to hit the SafetyNet API will be suppressed, so there should be no behaviour change if you continue to use a 3.X version of the SDK past January 2025.

**Comment by sangeeta-myob** [comment]
Thank you @chr-stripe. Appreciate the clarification!
