### ISSUE TITLE
Device freezes after tapping the card

### ISSUE THREAD

**Issue by abdulmananqureshi** [stripe/stripe-terminal-react-native#846]
**Describe the bug**
The Android device freezes when the collect payment method is invoked and the user taps their card on NFC. At this point, the payment intent hasn’t been confirmed, and no charge has been made to the user’s card. But the problem is we programmatically cancel this activity after a certain duration with the help of a patch since the Android package supports timeout, but it just hangs there and we have to restart the device manually. This issue is relatively rare.

**Expected behavior**
Should proceed to capture the payment and continue the app flow

**Screenshots**

![IMG_0838](https://github.com/user-attachments/assets/25362e74-4daa-4ac8-afb7-ba996b8ea202)

**Additional context**

- Device: Tap-to-pay (Generic Android)
- React Native version: 0.72.6
- Gradle version: 8.0.1
- Stripe version: 0.0.1-beta.15
- OS: Android 13

**Comment by nazli-stripe** [comment]
Can you reproduce this issue on the latest release, beta.22?

**Comment by abdulmananqureshi** [comment]
Reproducing the issue is quite hard. I'll roll out a new production version of the app with beta.22, and if the problem persists, I'll follow up accordingly.

**Comment by maggiewhite-stripe** [comment]
@abdulmananqureshi Can you share a payment intent ID from an instance where this issue occurs in the last 30 days so we can check the logs on our side?
